### ISSUE TITLE
Regression test crash on latest 9.5 HEAD

### ISSUE THREAD

**Issue by michaelpq** [plv8/plv8#114]
With recent PL handling changes in upstream Postgres, I am seeing a crash:
*** /home/ioltas/git/plv8/expected/json.out     2015-03-16 09:20:54.656451779 +0900
--- /home/ioltas/git/plv8/results/json.out      2015-03-16 09:27:00.890757874 +0900
***************
*** 25,38 ****
  COPY jsononly (data) FROM stdin;
  -- Call twice to test the function cache.
  SELECT get_key('ok', data) FROM jsononly;
!    get_key   
! -------------
!  {"ok":true}
! (1 row)
! 
! SELECT get_key('ok', data) FROM jsononly;
!    get_key   
! -------------
!  {"ok":true}
! (1 row)
! 
--- 25,31 ----
  COPY jsononly (data) FROM stdin;
  -- Call twice to test the function cache.
  SELECT get_key('ok', data) FROM jsononly;
! server closed the connection unexpectedly
!       This probably means the server terminated abnormally
!       before or while processing the request.
! connection to server was lost

**Comment by umitanuki** [comment]
#113 is merged.
