### ISSUE TITLE
missing cause of exception that is raised in plv8 function

### ISSUE THREAD

**Issue by alekbarszczewski** [plv8/plv8#117]
When exception is raised somewhere inside plv8 function (for example unique key violation) then instead of the original error, plv8 throws internal error (`XX000`) with only message property. All other original (root) error  properties such "code", "detail", "column", "table", "schema" etc are "lost". Here is small example to reproduce this issue:

```
CREATE EXTENSION IF NOT EXISTS plv8;
DROP TABLE IF EXISTS test_table;
CREATE TABLE test_table(col1 TEXT UNIQUE);
CREATE OR REPLACE FUNCTION plv8_exception_test()
RETURNS VOID
AS $$
  plv8.execute("INSERT INTO test_table VALUES ('a'), ('a')");
$$ LANGUAGE plv8;
```

```
SELECT plv8_exception_test(); 
-- ERROR: Error: duplicate key value violates unique constraint "test_table_col1_key"
-- SQL state: XX000
-- Detail: plv8_exception_test() LINE 2:   plv8.execute("INSERT INTO test_table VALUES ('a'), ('a')");
```

```
INSERT INTO test_table VALUES ('a'), ('a');
-- ERROR: duplicate key value violates unique constraint "test_table_col1_key"
-- SQL state: 23505
-- Detail: Key (col1)=(a) already exists.
```

I believe this code https://github.com/plv8/plv8/blob/master/plv8_func.cc#L281 needs some adjustments (there is even something like todo-comment there).
Without informations about root cause of the error it is impossible programatically react to certain error codes for example.

Also when using try/catch block around plv8.execute, cought error does not provide any informations about cause of the error (except message).

Using `pg 9.4` and `plv8 1.5.0-dev1`.

**Comment by umitanuki** [comment]
Right.  I guess we need to set detail, code etc as properties of the object thrown.  Currently it seems we are throwing string.  What's the best practice these days in JS?  Is it better to throw an object instead of string?  Or should we add those properties to string value?

**Comment by alekbarszczewski** [comment]
Well, in javascript the good practice is to always throw instance of `Error` (you can create and throw custom error by inheriting from javascript `Error` "class").

When I am connecting to db in node.js and some error occurs I get error in following format (example):

```
{ [error: insert or update on table "documents" violates foreign key constraint "type_fk"]
  name: 'error',
  length: 232,
  severity: 'ERROR',
  code: '23503',
  detail: 'Key (type)=(omglol) is not present in table "document_types".',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'documents',
  column: undefined,
  dataType: undefined,
  constraint: 'type_fk',
  file: 'ri_triggers.c',
  line: '3271',
  routine: 'ri_ReportViolation' }
```

but I am not sure what exactly receives pg client from db and how it transforms error response to javascript error.

**Comment by JerrySievert** [comment]
this has been merged, so going to close it up!
