### ISSUE TITLE
Make Travis-CI run faster

### ISSUE THREAD

**Issue by timdream** [plv8/plv8#121]
@clkao ask me to investigate what we could do about this, maybe skipping compiling v8 every time.

There are few choices

1. Roll out our own cache somewhere and write scripts to manually download it.
2. Use Travis-CI caching [1]

However it's worthy noting to go with (2), it is also states in [1] caching complied binary might not speed things up, although I don't really understand the reason there. (2) also comes with a requirement in which the build must switch to container-based infrastructure [2].

[1] http://docs.travis-ci.com/user/caching/#Things-not-to-cache
[2] http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/ 

Need some advice here to see what we want to do.

**Comment by JerrySievert** [comment]
i'm looking at fixing this right now.  most of it is coming down to a couple of things:

* lots of v8 and postgres versions
* compilation issues

**Comment by JerrySievert** [comment]
we cannot easily switch to container based architecture - i have 15 runs occurring in about 18 minutes, and all tests passing.  going to close this, feel free to re-open if there's some change in travis that allows us to go even faster (or if you have an idea about a different CI that would be more conducive to this project).
