### ISSUE TITLE
Seems not possible to call a non-plv8 function from within a plv8 function?

### ISSUE THREAD

**Issue by berlin-js** [plv8/plv8#122]
I try to call a function delivered by pgcrypt from within a plv8 function. It's not possible so far, right?
Thanks.

**Comment by berlin-js** [comment]
the only way seems to be via plv8.execute() ..

**Comment by JerrySievert** [comment]
functions run from context, which is currently javascript or plv8 only.  you can extend this using `plv8.start_proc`.

calls from javascript into the database use the same mechanism that `plv8.execute` uses - so running the command from javascript results in very little additional overhead.

it might be worth writing a function that gets executed in `plv8.start_proc` that queries for all of the available functions and their method signatures, and imports them into the global namespace with a `plv8.execute` wrapper.

this might have a fairly large startup overhead, so i don't think it would be best to make it the default.
