### ISSUE TITLE
Cannot call method 'elog' of null

### ISSUE THREAD

**Issue by apiel** [plv8/plv8#124]
I got the following error: TypeError: Cannot call method 'elog' of null

This is my function:

    create or replace function
    js(src text, input json) returns json as $$
      plv8.elog(NOTICE, 'test');
      //--plv8 = null; // previously this was uncommented, since then, commented or not the plv8 is null. The goal was to deactivate the access to plv8 functions inside the eval
      var evalRes = eval('var output=null; ' + src + '; output;');
      return JSON.stringify(evalRes);
    $$ LANGUAGE plv8;

    select js('var a = input.test; var output = []; for(k in a) { output.push(10+a[k]); };', '{"test": [1,2,3]}'::json)

**Comment by apiel** [comment]
If I restart the server, it's working again. But I still need to find a way to deactivate the access to plv8 in the eval. Any suggestion??

**Comment by schwebke** [comment]
A restart of the backend should be enough (disconnect, reconnect)  to get a newly initialized v8 context. 

You could place your eval in an anonymous function which contains a local plv8 var set to null. But I would propose a different approach - try to avoid eval, especially if the data evaled comes from an untrusted source.

**Comment by JerrySievert** [comment]
i'm going to go ahead and close this.
