### ISSUE TITLE
Automatically stringify objects when using plv8.execute.

### ISSUE THREAD

**Issue by sirisian** [plv8/plv8#129]
If I have a table foo(data jsonb) currently I have to do:

plv8.execute('insert into foo(data) values ($1)', [JSON.stringify({ a: 0 })]);

Would be nice to just do:

plv8.execute('insert into foo(data) values ($1)', [{ a: 0 }]);

**Comment by niquola** [comment]
:+1

**Comment by terrisgit** [comment]
+2

**Comment by rafaelveloso** [comment]
:+1:

**Comment by JerrySievert** [comment]
will look into this, but likely not part of the next release.

**Comment by seonixx** [comment]
:+1:

**Comment by pyramation** [comment]
I think this can be closed! I just rad this with no issues.

```sql
create table foo (data jsonb);

CREATE OR REPLACE FUNCTION bar()
 RETURNS setof foo
 LANGUAGE plv8
 SECURITY DEFINER
AS $function$
	return plv8.execute('insert into foo(data) values ($1) returning *', [{ a: 0 }]);
$function$;

SELECT * FROM bar();
```
