### ISSUE TITLE
More recent version of V8

### ISSUE THREAD

**Issue by ceymard** [plv8/plv8#138]
Some interesting updates were shipped with more recent versions of V8, such as arrow functions or for..of.

Would it be difficult to bump V8's version ?

**Comment by niquola** [comment]
:+1:

**Comment by JerrySievert** [comment]
it's a bit of a pain - the current version of `plv8` is as high as it can go in `v8` versions without a re-work of memory management in `plv8`, as there were some breaking changes.

see https://github.com/nodejs/node/issues/2308#issuecomment-132195767 and my conversation with @bnoorduis re: `v8::Object::SetIndexedPropertiesToExternalArrayData()`.

good luck, i don't have the time available to do the port right now.

**Comment by ceymard** [comment]
Aside from this change, are there other obstacles that you would know of to try and bump to a recent v8 version ? I might be inclined to try and do a PR (my C++ is pretty rusty though)

**Comment by bnoordhuis** [comment]
https://github.com/plv8/plv8/pull/141 - should work with V8 4.4 to 4.10.

**Comment by ceymard** [comment]
@bnoordhuis wow this is fantastic !

**Comment by JerrySievert** [comment]
@bnoordhuis let me get together a new release before the big v8 change, then i'm happy to work with you to try to get this merged.

**Comment by JerrySievert** [comment]
current master is tracking 4.4-4.10, going to close this.
