### ISSUE TITLE
Releases and Versions

### ISSUE THREAD

**Issue by TwentyOneSolutions** [plv8/plv8#139]
The readme.md file says that plv8 v1.4.4 is tested for PosgreSQL 9.4:
`plv8 is tested with: PG: version 9.3 and 9.4 (maybe older/newer are allowed)`

But the official distribution site at http://pgxn.org/dist/plv8/ shows 
`plv8 is tested with: PG: version 8.4, 9.0, 9.1, 9.2 and 9.3dev (maybe older are allowed)`

and apparently distributes the sources that are available here on github at https://github.com/plv8/plv8/releases

It would be great if someone could clarify which is correct.

Also, I downloaded binaries for Windows from http://www.postgresonline.com/journal/archives/341-PLV8-binaries-for-PostgreSQL-9.4-windows-both-32-bit-and-64-bit.html -- but it'd be really great if the binaries were included on an official site like github/plv8 or pgxn.org -- as compiling this on some operating systems is not as simple as on others.

Thank you!

**Comment by TwentyOneSolutions** [comment]
Regina Obe has published the binaries for Windows compiled for PostgreSQL 9.5 at http://www.postgresonline.com/journal/archives/360-PLV8-binaries-for-PostgreSQL-9.5-windows-both-32-bit-and-64-bit.html

**Comment by JerrySievert** [comment]
i'm working on getting a new release put together, and will try to address these.  i'm not sure about compiled binaries on windows, which is the only issue i have.

**Comment by ChristophBerg** [comment]
Debian would also very much appreciate a new release, 1.4.4 doesn't work with PostgreSQL 9.5. It compiles, but then the regression tests fail:

```
**** regression.diffs ****
*** /srv/projects/postgresql/plv8/plv8/build-9.5/expected/plv8.out	2016-01-09 21:57:15.000000000 +0100
--- /srv/projects/postgresql/plv8/plv8/build-9.5/results/plv8.out	2016-02-16 10:09:33.822532421 +0100
***************
*** 384,393 ****
  $$
  LANGUAGE plv8;
  SELECT test_sql();
! NOTICE:  {"i":1,"s":"s1","c":["pg_catalog","public"]} 1
! NOTICE:  {"i":2,"s":"s2","c":["pg_catalog","public"]} 1
! NOTICE:  {"i":3,"s":"s3","c":["pg_catalog","public"]} 1
! NOTICE:  {"i":4,"s":"s4","c":["pg_catalog","public"]} 1
   test_sql 
  ----------
          4
--- 384,393 ----
  $$
  LANGUAGE plv8;
  SELECT test_sql();
! NOTICE:  Àçmp-V
! NOTICE:  Àçmp-V
! NOTICE:  Àçmp-V
! NOTICE:  Àçmp-V
   test_sql 
  ----------
          4
```

Thanks!

**Comment by JerrySievert** [comment]
working on cleaning up and getting a release, have already been in contact with @robe2, who has provided a lot of amazing compilation knowledge.

leaving this open until we are able to release `1.5`

**Comment by JerrySievert** [comment]
v1.5.0 has been released.  please note, however, that plv8 v1.5.0 requires a bit more modern version of v8 than ubuntu supports (even as of 15.10).  ubuntu ships with v3.14.5.

you can get around this by running `make static`, which will build with 4.3.66.

**Comment by TwentyOneSolutions** [comment]
Great news, thanks!

So what version of v8 does plv8 work with by default now (without the `make static` switch)?

**Comment by JerrySievert** [comment]
currently, plv8 will work with any 4.x release up to 4.3.66 that you can compile.

you'll note the second half of that sentence, as the v8 project appears to have removed all tags older than 4.2.69, making it much more difficult to deal with older versions of v8.

it's a tradeoff, but if there needs to be a 1.4.5 release to better work with postgres 9.5, i can look into that.

but, the goal is to be able to track v8 and node.js, which should help distro maintainers in the future.

**Comment by JerrySievert** [comment]
v1.4.6 was a back port release for debian, closing this now
