### ISSUE TITLE
`make static` fails to find `-lv8_base` on OSX

### ISSUE THREAD

**Issue by aredridel** [plv8/plv8#142]
This fixes it:

```diff
diff --git a/Makefile b/Makefile
index 2ec6aa6..553041d 100644
--- a/Makefile
+++ b/Makefile
@@ -70,8 +70,6 @@ else
        UNAME_S := $(shell uname -s)
        ifeq ($(UNAME_S),Darwin)
                CCFLAGS += -stdlib=libstdc++
-               SHLIB_LINK := -stdlib=libstdc++
-               SHLIB_LINK += -lv8_base -lv8_libbase -lv8_libplatform -lv8_snapshot
        endif
 endif
```

and it looks like it was introduced in ca2fa002dafc1d7a229892d8f16b92ab61182a2c / b297981, which may have fixed dynamic linked v8, but breaks static.

**Comment by JerrySievert** [comment]
this should be fixed by #144 - just waiting for travis before merging.

**Comment by triplepointfive** [comment]
I had the same issue on fresh master on Ubuntu 14.04, resolved with removing
`SHLIB_LINK += -lv8_base -lv8_libbase -lv8_libplatform -lv8_snapshot`

**Comment by JerrySievert** [comment]
@triplepointfive can you try with the latest changes on master?  i set up a 14.04 vm, and was able to compile static without issue.

thanks!

**Comment by triplepointfive** [comment]
Now it's fine, I've no issues with build. Thank!

**Comment by JerrySievert** [comment]
great! going to close this, as all changes have been merged to master.
