### ISSUE TITLE
question: does plv8 keep cached versions of the compiled code in memory ?

### ISSUE THREAD

**Issue by ceymard** [plv8/plv8#143]
Or does it always recompile it from the database when the function is called for the first time in the session ?

**Comment by schwebke** [comment]
The functions are cached and reused for the entire run-time of a postgres server process. But postgres server processes are spawned by postmaster for every connection and therefore correspond 1-1 to a session (persistent connections or connection pooling would have an impact here).

**Comment by JerrySievert** [comment]
going to go ahead and close this.
