### ISSUE TITLE
pgx install fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by jcalderonzumba** [plv8/plv8#158]
This is the error i get:
```
vagrant@ftp:~/scm/plv8$ sudo pgxn install plv8
INFO: best version: plv8 1.5.0
INFO: saving /tmp/tmprU8Zif/plv8-1.5.0.zip
INFO: unpacking: /tmp/tmprU8Zif/plv8-1.5.0.zip
INFO: building extension
sed -e 's/^#undef PLV8_VERSION/#define PLV8_VERSION "1.5.0"/' plv8_config.h.in > plv8_config.h
g++ -Wall -O2 -std=c++11 -fno-rtti  -I. -I./ -I/usr/include/postgresql/9.5/server -I/usr/include/postgresql/internal -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/tcl8.6 -fPIC -c -o plv8.o plv8.cc
plv8.cc:9:37: fatal error: libplatform/libplatform.h: No such file or directory
 #include "libplatform/libplatform.h"
                                     ^
compilation terminated.
make: *** [plv8.o] Error 1
ERROR: command returned 2: make PG_CONFIG=/usr/bin/pg_config all
```

This are the libraries i have of postgres: 
```
vagrant@ftp:~/scm/plv8$ dpkg --list | grep postgres | cut -d" " -f3
pgdg-keyring
postgresql-9.5
postgresql-9.5-pgtap
postgresql-client-9.5
postgresql-client-common
postgresql-common
postgresql-contrib-9.5
postgresql-server-dev-9.1
postgresql-server-dev-9.2
postgresql-server-dev-9.3
postgresql-server-dev-9.4
postgresql-server-dev-9.5
postgresql-server-dev-all
```
This are the V8 libraries:
```
vagrant@ftp:~/scm/plv8$ dpkg --list | grep v8 | cut -d" " -f3
libv8-3.14.5
libv8-dev
```

However this works: 
``bash
vagrant@ftp:~/scm/plv8$ sudo pgxn install 'plv8=1.4.4'
``

Seems something is broken with 1.5.0, i'm testing because i would like to create a package for my 9.5 production servers and seeing the change-log i would prefer to use 1.5.X instead of 1.4.4 because it shows several bugfixes.

**Comment by ruimarinho** [comment]
v1.5.0 requires a more recent version of V8, such as 4.3.x. Unfortunately, there aren't packages for ubuntu or other debian-based distributions yet. You must compile V8 first by yourself (see .travis.yml) or compile plv8 statically linked to V8 (`make static` instead of using pgxn).

**Comment by jcalderonzumba** [comment]
Thanks for the reply but i'm afraid that due to the nature of our production systems, i would not feel confortable with compiling and installing on production servers.
As a standard for my company i would like to have an ubuntu package so i can just do in production server apt-get install postgres95-plv8

**Comment by ruimarinho** [comment]
Last information I've read was that recent versions of V8 were causing some
trouble for Debian package maintainers. Last V8 package is 3.14 on Debian
and 3.7 on Ubuntu I believe. I don't think you'll have another option other
than compile it yourself for now.

That or, if you're into Docker, you can simply do docker run
clkao/postgres-plv8:9.5 :)

On Saturday, February 27, 2016, Juan Francisco Calderón Zumba <
notifications@github.com> wrote:

> Thanks for the reply but i'm afraid that due to the nature of our
> production systems, i would not feel confortable with compiling and
> installing on production servers.
> As a standard for my company i would like to have an ubuntu package so i
> can just do in production server apt-get install postgres95-plv8
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plv8/plv8/issues/158#issuecomment-189643560>.
>


-- 
--
Rui Marinho

**Comment by jcalderonzumba** [comment]
I'm trying to create the ubuntu 9.5 package but i have some problems to compile.

**Comment by jcalderonzumba** [comment]
I manage to create the package but with 1.4.4 for 9.5:
````
vagrant@ftp:~/scm/plv8$ ll
total 448
drwxrwxr-x 13 501 dialout    442 Feb 27 15:02 ./
drwxr-xr-x 41 501 dialout   1394 Feb 26 19:39 ../
drwxrwxr-x 41 501 dialout   1394 Feb 27 15:02 plv8/
-rw-r--r--  1 501 dialout  21887 Feb 27 15:02 plv8_1.4.4.ds-1_amd64.build
-rw-r--r--  1 501 dialout   3671 Feb 27 15:02 plv8_1.4.4.ds-1_amd64.changes
-rw-r--r--  1 501 dialout   5176 Feb 27 15:01 plv8_1.4.4.ds-1.debian.tar.gz
-rw-r--r--  1 501 dialout   1387 Feb 27 15:01 plv8_1.4.4.ds-1.dsc
-rw-rw-r--  1 501 dialout 155693 Feb 27 14:48 plv8_1.4.4.ds.orig.tar.gz
-rw-r--r--  1 501 dialout  47876 Feb 27 15:02 postgresql-9.1-plv8_1.4.4.ds-1_amd64.deb
-rw-r--r--  1 501 dialout  47882 Feb 27 15:02 postgresql-9.2-plv8_1.4.4.ds-1_amd64.deb
-rw-r--r--  1 501 dialout  47672 Feb 27 15:02 postgresql-9.3-plv8_1.4.4.ds-1_amd64.deb
-rw-r--r--  1 501 dialout  48032 Feb 27 15:02 postgresql-9.4-plv8_1.4.4.ds-1_amd64.deb
-rw-r--r--  1 501 dialout  48124 Feb 27 15:02 postgresql-9.5-plv8_1.4.4.ds-1_amd64.deb
```

**Comment by ruimarinho** [comment]
With version 1.4.4 there should be no problem. Version 1.5.0 is trickier.

On Saturday, February 27, 2016, Juan Francisco Calderón Zumba <
notifications@github.com> wrote:

> I manage to create the package but with 1.4.4 for 9.5:
>
> vagrant@ftp:~/scm/plv8$ ll
> total 448
> drwxrwxr-x 13 501 dialout    442 Feb 27 15:02 ./
> drwxr-xr-x 41 501 dialout   1394 Feb 26 19:39 ../
> drwxrwxr-x 41 501 dialout   1394 Feb 27 15:02 plv8/
> -rw-r--r--  1 501 dialout  21887 Feb 27 15:02 plv8_1.4.4.ds-1_amd64.build
> -rw-r--r--  1 501 dialout   3671 Feb 27 15:02 plv8_1.4.4.ds-1_amd64.changes
> -rw-r--r--  1 501 dialout   5176 Feb 27 15:01 plv8_1.4.4.ds-1.debian.tar.gz
> -rw-r--r--  1 501 dialout   1387 Feb 27 15:01 plv8_1.4.4.ds-1.dsc
> -rw-rw-r--  1 501 dialout 155693 Feb 27 14:48 plv8_1.4.4.ds.orig.tar.gz
> -rw-r--r--  1 501 dialout  47876 Feb 27 15:02 postgresql-9.1-plv8_1.4.4.ds-1_amd64.deb
> -rw-r--r--  1 501 dialout  47882 Feb 27 15:02 postgresql-9.2-plv8_1.4.4.ds-1_amd64.deb
> -rw-r--r--  1 501 dialout  47672 Feb 27 15:02 postgresql-9.3-plv8_1.4.4.ds-1_amd64.deb
> -rw-r--r--  1 501 dialout  48032 Feb 27 15:02 postgresql-9.4-plv8_1.4.4.ds-1_amd64.deb
> -rw-r--r--  1 501 dialout  48124 Feb 27 15:02 postgresql-9.5-plv8_1.4.4.ds-1_amd64.deb
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plv8/plv8/issues/158#issuecomment-189660507>.
>


-- 
--
Rui Marinho

**Comment by JerrySievert** [comment]
thanks @ruimarinho!

@jcalderonzumba the largest request that we've seen has been for adding ES6/ES7 support via updating V8, though we are still 7 major versions behind in the 4.0 series (this will be changed with PLV8 2.0).  The current version of V8 is 5.0.99, we will be moving to track as close to the Node.js project as we can.

The oldest version that we can even build from source at this point was released in February, 2015 (4.2.69).  Google has removed the tags for any version older than this.

It is possible to later change the default PGXN install to build a static V8, and I can look at putting a dev release up there that does this, if that would help.

Also, the Postgres project maintains APT repositories that include PLV8: http://www.postgresql.org/download/linux/ubuntu/

As for 9.5, if you are running into issues, I can look at finding fixes and releasing a version at 1.4.5, with some changes back ported.

**Comment by jcalderonzumba** [comment]
@JerrySievert Thanks for the reply. Sadly there is no 9.5 plv8 done by postgres that's why i had to create the packages by myself.
I'll try to build a package with 1.5.0 let's hope I can remember how to do it. It's been a long time since I manually created packages for Debian/Ubuntu.

**Comment by ruimarinho** [comment]
@jcalderonzumba were you able to create the packages for 1.5.0?

**Comment by jcalderonzumba** [comment]
@ruimarinho Not yet, i've been having lot on my plate so this task is on hold (I was doing it due to company requirements) but we decided to go on another path due to the problems i was facing.
I'll try on my own free time which at the moment is not so much.

**Comment by ruimarinho** [comment]
Ok, let me know if you have any progress. I don't expect Debian to include V8
4.0+ anytime soon (meaning no plv8 1.5+).

On Saturday, April 16, 2016, Juan Francisco Calderón Zumba <
notifications@github.com> wrote:

> @ruimarinho <https://github.com/ruimarinho> Not yet, i've been having lot
> on my plate so this task is on hold (I was doing it due to company
> requirements) but we decided to go on another path due to the problems i
> was facing.
> I'll try on my own free time which at the moment is not so much.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/plv8/plv8/issues/158#issuecomment-210757789>
>


-- 
--
Rui Marinho
