### ISSUE TITLE
Include external JavaScript libraries

### ISSUE THREAD

**Issue by koh-osug** [plv8/plv8#159]
Is it possible to include external JavaScript libraries? I want to use some cryptographic functions from `crypto.js` which are not included in the PostgreSQL crypto plugin in and this library is rather big. Do I have to include all functions needed directly in the PL function?

**Comment by JerrySievert** [comment]
PLV8 is a _secure_ extension, meaning, among other things, that you cannot read anything directly from the file system.  you can, however, include code and functions at startup:  http://adpgtech.blogspot.com/2013/03/loading-useful-modules-in-plv8.html

i'm curious, though, which crypto functions you're looking to use that aren't available as an existing PG extension.

**Comment by koh-osug** [comment]
I have to migrate a database and the string fields are encrypted using PBEWITHSHA256AND256BITAES-CBC, i.e. password based encryption according to PKCS#5 and later using AES with the derived 256 bit key. AES is not a problem, but the PBE key derivation.

**Comment by JerrySievert** [comment]
hm.  on the PBE variant, you may be able to hack something together from the crypto.js code using the method above, but crypto.js is a fairly complicated module, so it might be quicker to pull it out of the db, do the crypto, then send it back in - i guess it depends a lot on your database.

i'd give the method above at least a good looking at, and see if it will work - that will be much faster than building an _insecure_ plv8 - though if you take that approach, it should only take about a week to get something robust and working.

**Comment by koh-osug** [comment]
Like a got it from the above link I can load store the crypto JS in a table, load it with `plv8.execute`, use it and that's it. It doesn't need to be available during the complete runtime and start up only for the migration decryption step.

**Comment by ruimarinho** [comment]
@JerrySievert is there any way of not exposing loaded modules in the global scope? Following the blog's example, `var foo = load_modules('bar');` would not leak `bar`'s objects.

**Comment by JerrySievert** [comment]
anything you assign to `this` would stay in the scope of the function, otherwise attaching to `plv8` would be in the global scope.

**Comment by ruimarinho** [comment]
One of the comments on that blogpost suggest using event triggers to load external modules. I find the current setup a bit cumbersome, but I'm afraid there isn't any better alternative. Do you think event triggers could help bundling external js dependencies?

**Comment by JerrySievert** [comment]
here's something you can try:

https://github.com/jerrySievert/plv8-modules

it works with cryptojs at least, but is a major work in progress (won't work with multi-file modules or dependencies yet).

**Comment by ruimarinho** [comment]
@JerrySievert what is the purpose of `plv8.context` there? It seems to be always empty - https://github.com/JerrySievert/plv8-modules/blob/master/sql/001-startup.sql#L12-L23.

**Comment by ruimarinho** [comment]
I can't seem to be able to get `plv8.require` to return the attached context of the module's code. I see that the Cromag module is testing `context.Cromag`, but what about a regular package like `lodash`?

**Comment by JerrySievert** [comment]
@ruimarinho currently it is always empty - but that is expected to change shortly.

i am going to be using `required` to traverse the module tree, ala `browserify`, and insert the context as part of the module name to avoid conflicts.

how i am planning on it working:

```
module (index.js)
      \_ lib/foo.js
      |_ lib/bar.js
      |_node_modules
        \_ dep (dep.js)
            |_ lib/baz.js
```

module names would be:

* module
* module/lib/foo.js
* module/lib/bar.js
* module/dep/dep.js
* module/dep/lib/baz.js

does that make sense?

**Comment by JerrySievert** [comment]
i haven't moved on to lodash yet, and that would be a great test case.  i will have a few hours these next couple of days, and will try to get it working with that.

**Comment by ruimarinho** [comment]
(Let me know if you'd like to move this discussion to the other repo)

Yes, that is quite interesting - I would loosely follow what `require.cache` does on node.js, as that seems to be work very well.

What about the  `return exports` part? What do you intend to do with that? I assume you've also created `modules` so that scripts testing for that or `exports` would return correctly.

**Comment by EvanCarroll** [comment]
https://github.com/plv8/plv8/issues/222
