### ISSUE TITLE
There is no "How To install plv8 in DB" in documentation.

### ISSUE THREAD

**Issue by alexandru-lazarev** [plv8/plv8#161]
Maybe it's a good idea to add in documentation, near phrase 

> Once you installed plv8 into your dabase, create language via

the steps of How To install plv8 in DB, for newbies like me, e.g.: 

```
make PG_CONFIG=path_to_postgresql_installation/bin/pg_config
make PG_CONFIG=path_to_postgresql_installation/bin/pg_config install
```

_Background_: I had to create test environment with PG and plv8 and got stuck for several days in how to install extension in DB. I did just `make static` then copy/paste manually in PG paths generate files and got a lot of errors. I even wrote a question on [SO](http://stackoverflow.com/questions/35439313/how-to-install-plv8-in-postgresql-9-5-on-centos-6-7) and nobody helped me. Motivation that I am not single guy faced this issue. IMHO it will be good to add it in documentation.

**Comment by JerrySievert** [comment]
i've updated the documentation slightly, but going to leave this open for now until there is more documentation.

**Comment by bendiy** [comment]
@JerrySievert This can be closed now:
https://github.com/plv8/plv8/blob/master/doc/plv8.md#installing-plv8
