### ISSUE TITLE
Linker Error in v8/mksnapshot during make static

### ISSUE THREAD

**Issue by aravindet** [plv8/plv8#167]
```
  LINK(target) /home/aravind/dev/plv8-1.5.0/build/v8-git-mirror-4.3.66/out/native/mksnapshot
/home/aravind/dev/plv8-1.5.0/build/v8-git-mirror-4.3.66/third_party/binutils/Linux_x64/Release/bin/ld.gold: error: /usr/lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib64/crti.o: unsupported reloc 42 against global symbol __gmon_start__
/usr/lib64/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib64/crti.o(.init+0x7): error: unsupported reloc 42
clang: error: linker command failed with exit code 1 (use -v to see invocation)
tools/gyp/mksnapshot.target.native.mk:247: recipe for target '/home/aravind/dev/plv8-1.5.0/build/v8-git-mirror-4.3.66/out/native/mksnapshot' failed
make[3]: *** [/home/aravind/dev/plv8-1.5.0/build/v8-git-mirror-4.3.66/out/native/mksnapshot] Error 1
make[3]: Leaving directory '/home/aravind/dev/plv8-1.5.0/build/v8-git-mirror-4.3.66/out'
Makefile:304: recipe for target 'native' failed
make[2]: *** [native] Error 2
```

I'm using GCC 5.3.0.

**Comment by JerrySievert** [comment]
can you let me know what version of plv8 you are attempting to install, as well as the os you are installing it on?  also, are you compiling with `make static` or just with `make`? (i'm guessing `make static`, but want to make sure)

this looks like an issue in v8, but i can at least try to track it down if i can reproduce it.

**Comment by aravindet** [comment]
PLv8 1.5.0, which I downloaded (through .tar.gz) from GitHub’s releases page.

I’m using `make static`. I run Arch, and AUR has v8 at version 5.1. I believe that version is not supported?

[This](https://bbs.archlinux.org/viewtopic.php?id=209871) seems to be the same v8 build error. They fixed this by using a version of binutils other than that bundled with v8. Requires a minor Makefile change I believe.

**Comment by bendiy** [comment]
I had this same issue trying to `make static` plv8 version 1.5.4 on Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-51-generic x86_64) with gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) today.

I had to:
```
mv ./build/v8-git-mirror-4.3.66/third_party/binutils/Linux_x64/Release/bin/ld.gold ./build/v8-git-mirror-4.3.66/third_party/binutils/Linux_x64/Release/bin/ld.gold.OLD
ln -s /usr/bin/ld.gold ./build/v8-git-mirror-4.3.66/third_party/binutils/Linux_x64/Release/bin/ld.gold
```

This seems to be related to #193.
