### ISSUE TITLE
Not building

### ISSUE THREAD

**Issue by 9662** [plv8/plv8#176]
```
$ cat /etc/os-release 
NAME=openSUSE
VERSION="Tumbleweed"
VERSION_ID="20160126"
PRETTY_NAME="openSUSE Tumbleweed (20160126) (x86_64)"
ID=opensuse
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:opensuse:20160126"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
ID_LIKE="suse"
```

```
$ gcc --version
gcc (SUSE Linux) 5.2.1 20151008 [gcc-5-branch revision 228597]
```

```
$ zypper info v8-devel


Information for package v8-devel:
---------------------------------
Repository: Databases (openSUSE_Tumbleweed)
Name: v8-devel
Version: 4.8.294-185.4
Arch: x86_64
Vendor: obs://build.opensuse.org/server:database
Installed: Yes
Status: up-to-date
Installed Size: 337.6 KiB
Summary: Development headers and libraries for v8
Description: 
  V8 is Google\'s open source JavaScript engine. This package contains
  development headers and libraries for v8.
```

```
$ zypper info postgresql94-devel
Loading repository data...
Reading installed packages...


Information for package postgresql94-devel:
-------------------------------------------
Repository: repo-oss
Name: postgresql94-devel
Version: 9.4.6-1.1
Arch: x86_64
Vendor: openSUSE
Installed: Yes
Status: up-to-date
Installed Size: 4.7 MiB
Summary: PostgreSQL development header files and libraries
Description: 
  PostgreSQL is an advanced object-relational database management system
  that supports an extended subset of the SQL standard, including
  transactions, foreign keys, subqueries, triggers, and user-defined
  types and functions.
  This package contains the header files and libraries needed to compile
  C applications which will directly interact with a PostgreSQL database
  management server and the ECPG Embedded C Postgres preprocessor. You
  need to install this package if you want to develop applications in C
  which will interact with a PostgreSQL server.
```

```
$ tar -xzvf v1.4.8.tar.gz
$ cd plv8-1.4.8
$ make
```

Results in these errors: [log.txt](https://github.com/plv8/plv8/files/230552/log.txt)

**Comment by JerrySievert** [comment]
i am sorry that you are having trouble building, but that version of v8 will not build against that version of plv8.

this is the matrix:

plv8 version|v8 version
---|---
1.4.x|3.14
1.5.x|4.0-4.3
2.0.0-dev|4.4-4.10

due to the major changes under the hood in v8, it is not possible for new versions of v8 to work against older versions of plv8 and vice-versa.

1.4.8 is maintained for linux distro maintainers to allow for older versions of v8 that ship with those OS's to be used and still have fixes backported.

1.5.3 is the current stable release of plv8, against 4.0-4.3 of v8, which provides more es6 support.

2.0.0-dev is the development branch against the same level of v8 as node.js, but has open feature requests before being released.

for the version of v8 that you are using, you would want to build against 2.0.0-dev (master).

**Comment by 9662** [comment]
Ok, cheers. Will give v2.0.0-dev a spin in the next few days.

**Comment by JerrySievert** [comment]
@9662 you can also `make static` and it will download the correct version of v8 and compile it statically.

also, @ruimarinho put in a pull request that takes the default static build to 5.1 for 2.0.0-dev, so that's even better (i'll need to update the matrix)

**Comment by 9662** [comment]
Hi @JerrySievert. I did also try static and it failed with different errors.

I regret that I did not collect those, but from memory where errors in the V8 code, possibly related to compiler version incompatibility. If I have the opportunity, I'll re-run `make static`.

**Comment by JerrySievert** [comment]
@9662 there is possibility of compiler incompatibility.  modern v8 requires g++-4.8.2 and above, or a modern version of clang, in order to compile.

which os/version are you using?

**Comment by 9662** [comment]
> which os/version are you using?

[Tumbleweed 20160126](#issue-150162601) at the time of reporting (updated two days ago though). GCC 5.2.1, and off the top of my head, the static compile failing could very well have been a compiler compatibility issue with the V8 code. I have not investigated though.
