### ISSUE TITLE
Release of 2.0?

### ISSUE THREAD

**Issue by pkajaba** [plv8/plv8#178]
Hello, I would like to ask - can you release 2.0 version? I want to package latest version into Fedora, but in rawhide there is V8 in version 5.1.

I can take git snapshot, but If you made release I would be really glad.

**Comment by JerrySievert** [comment]
these are the tasks that still need to be completed before a 2.0 release:

https://github.com/plv8/plv8/issues?q=is%3Aopen+is%3Aissue+milestone%3A%222.0+Release%22

most important of those (from my view) is the debugger, which broke entirely via a v8 update.

i am trying to find the time to close these issues, but don't feel comfortable releasing until then.

**Comment by pkajaba** [comment]
Sure, Thanks for the answer.

Do you have any ETA for fixing these issues?

**Comment by JerrySievert** [comment]
i'm trying to find the time, but am essentially working by myself on this project right now.

**Comment by pkajaba** [comment]
OK, i try to help you, but I am noob in JS. Do you have any tips how to start with it?
