### ISSUE TITLE
OSX: Wrong relative path to v8-platform.h in include/libplatform/libplatform.h

### ISSUE THREAD

**Issue by jmealo** [plv8/plv8#179]
**The fix for this issue is here:**
https://bugs.chromium.org/p/v8/issues/detail?id=3654

I'm not sure which path you'd like to take, but simply changing that line in libplatform.h as suggested in the ticket fixed that error for me on OSX 10.11.4.

The plugin failed to load; so there's still more work to be done:

```
CREATE EXTENSION plv8;
ERROR:  could not load library "/usr/local/lib/postgresql/plv8.so": dlopen(/usr/local/lib/postgresql/plv8.so, 10): Symbol not found: _V8_Fatal
  Referenced from: /usr/local/lib/postgresql/plv8.so
  Expected in: flat namespace
 in /usr/local/lib/postgresql/plv8.so
```

I also tried `make static` which took much longer, but also eventually failed.

**Comment by JerrySievert** [comment]
which version of plv8 are you using?

**Comment by jmealo** [comment]
@JerrySievert I cloned from git. That got it to build but it failed when I tried to load it. Fixing this is still the first step though I suppose?

**Comment by JerrySievert** [comment]
odd, i do my development on osx 10.11.4 - will pull down a fresh copy tonight.

see also: https://travis-ci.org/plv8/plv8

**Comment by JerrySievert** [comment]
also, when you tried to `make` with the shared v8 library, which version of v8 were you using?

**Comment by JerrySievert** [comment]
so here's the output i get with `make static`:

https://gist.github.com/JerrySievert/c83b7d3b04ce3fbc6c2986581691bef0

i would love to figure out what the differences are between your environment and mine

**Comment by mnd999** [comment]
Same problem here.

**Comment by JerrySievert** [comment]
closing as this is so out of date at this point it isn't funny
