### ISSUE TITLE
Dropping support for CoffeScript and LiveScript

### ISSUE THREAD

**Issue by ruimarinho** [plv8/plv8#180]
Is there any interest in the community on maintaining both dialects under plv8?

**Comment by JerrySievert** [comment]
that might be best answered on the mailing list - as i don't know the usage of either of those.

**Comment by pyramation** [comment]
We should definitely drop! ES6/ES7 have made coffeescript irrelevant.

**Comment by JerrySievert** [comment]
It will happen, but after plv8u, which has been low on my priority list at the moment.
