### ISSUE TITLE
Add v8_inspector support with documentation on using Blink/Chrome devtools for debugging

### ISSUE THREAD

**Issue by jmealo** [plv8/plv8#186]
I propose that the end goal for debugging is v8_inspector integration/support.
[v8_inspector](https://github.com/pavelfeldman/v8_inspector)

I think this would be the most approachable way to make debugging available pl/v8 endusers.

**See also:**
#131

**Subject matter experts:**
https://github.com/nodejs/diagnostics/issues/60#issuecomment-237765788

**Comment by bnoordhuis** [comment]
v8_inspector was merged into V8 recently.  It would make sense for plv8 to make the jump to V8 5.8.

Documentation on integrating the inspector can be found here: https://github.com/v8/v8/wiki/Debugging-over-the-V8-Inspector-API

**Comment by JerrySievert** [comment]
@bnoordhuis thanks again for your help and insight!

**Comment by jmealo** [comment]
@bnoordhuis: @JerrySievert: I'd love to see remote debugging back in pl/v8. Any news on that front? I'm bringing on some interns for the summer and I can't let them loose on pl/v8 without remote debugging :)

**Comment by bnoordhuis** [comment]
The biggest obstacle (I think) is that Chrome DevTools talks over HTTP+WebSockets.  That means you need a web server in plv8 that speaks those protocols.  You can probably get away with implementing an ad hoc subset but still.

The web server could be moved into a standalone process (like a node.js script) that talks to plv8 over a UNIX socket or communicates through a table.  I'm happy to mentor anyone willing to work on it but I currently don't have time myself.

**Comment by jmealo** [comment]
@bnoordhuis: UNIX sockets seems reasonable to me. I can help on the Node/PostgreSQL with a service or script if someone can get a socket listening for the debugger protocol.

Side note: I believe we need to upgrade V8 before this is possible?

I want to make sure debugging is as easy as installing in common environments. I don't think that installing Node to debug plv8 is unreasonable.

**Comment by JerrySievert** [comment]
This also moves us directly out of being a trusted extension, which cannot happen (see the untrusted thread).  I have a branch that I started the debugger work on, but backed away until I can get an untrusted split.

**Comment by JerrySievert** [comment]
As an aside @jmealo, I've been writing socket code since the 80's, that's not my concern :)

I highly recommend a perusal through the untrusted ticket that lays everything out as far as requirements- being able to stay on RDS is a must.
