### ISSUE TITLE
How do I create bytea properly?

### ISSUE THREAD

**Issue by unoexperto** [plv8/plv8#189]
Hey guys!

I couldn't find answer in documentation. So sorry for writing here. I'm not sure I create `bytea` result correctly.

Here is my test function

```
CREATE OR REPLACE FUNCTION test(input text) RETURNS bytea AS $$
        var i = 0;
        var arr = [];

        do {
            arr.push(input.charAt(i++));
        } while (i < input.length);

        return arr;
$$ LANGUAGE plv8 IMMUTABLE STRICT;
```

which I test using

```
select test('10.1111/anae.13562');
```

I get `bytea` of 94 bytes. I expect 18. I saved given LOB and I see first two bytes have 18 (length of my source string). Then bunch of repeating 010000 bytes and source string at the end.

I'm testing it with Amazon RDS with postgresql 9.5 (with plv8 1.4.3)

What am I missing ?

**Update:**

Looks like I figured out how it creates BYTEA. For example for this function

```
CREATE OR REPLACE FUNCTION test2(input bytea) RETURNS bytea AS $$
    return '          '.split('');
$$ LANGUAGE plv8 IMMUTABLE STRICT;
```

It produces
`E'\\x0A000040 01000080 01000000 01000000 01000000 01000000 01000000 01000000 01000000 01000000 01000000 20202020202020202020';
`

So it contains length in lower bytes of first DWORD (which for some reason has 0x40 in higher byte), which is followed by 0x80000001 and then followed by `Len-1` of 0x1. Then it's followed by bytes of actual source string.

**Comment by unoexperto** [comment]
@JerrySievert Could you please clarify what to do ?

Thanks!

**Comment by JerrySievert** [comment]
the best I can do is point to the documentation on it:

https://github.com/plv8/plv8/blob/master/doc/plv8.md#typed-array

I haven't used the `bytea` type with plv8, and unfortunately the `bytea` code is long before my time.   I might be able to help figure it out though.

**Comment by dboris** [comment]
Any update on this issue?
I am testing with
```
CREATE OR REPLACE FUNCTION create_array(bytes_size integer) RETURNS bytea AS
$$
    var a = new Array(bytes_size).fill(0);
    plv8.elog(NOTICE, 'Array length:', a.length);
    return a;
$$ LANGUAGE plv8;
```

Calling this function:

```
boris=> select length(create_array(10));
NOTICE:  Array length: 10
 length 
--------
    122
(1 row)
```

Why this length? How can I access the elements as unsigned bytes?

**Comment by JerrySievert** [comment]
`length()` is a string function in postgres, not a generic length, it's scanning and trying to find the end of a string, which is normally denoted by `\0`.

you're also converting an `Array` to a `bytea`, so this is likely nothing that you want to do.

what are you trying to accomplish, and maybe I can help you from there.

**Comment by dboris** [comment]
I am storing large bit vectors in a `bytea`. Most of the bits are 0, so I initialize the `bytea` with 0s. I need to set some bits to 1. Using `set_bit` in a loop in `plpgsql` function seems quite slow. I guess the whole array gets copied in each `set_bit` call. I was hoping to improve the performance of this operation using `plv8` function instead. My problem is I cannot return the JS array. I've tried `Uint32Array` too, unsuccessfully.

**Comment by JerrySievert** [comment]
likely you're running into a conversion between unicode and bytes.

**Comment by dboris** [comment]
I wonder if there is some way to cast the `buffer` property of a `Uint32Array` to a data structure that can be correctly converted to `bytea` when returned by the function. Any idea how to get raw bytes out of a `plv8` function?

**Comment by JerrySievert** [comment]
it's doing a `getInternalField()` call on the `v8` structure, and returning a pointer to the internal value.  likely this is not what you want.  internally,  a `bytea` `OID` gets converted into `v8::Uint8Array`.

not sure where the length is being set, though.

**Comment by JerrySievert** [comment]
my guess without getting too deep into code is that it should be setting the length header - I'll see if that makes a difference likely tomorrow.

**Comment by JerrySievert** [comment]
if you want to try https://github.com/JerrySievert/plv8.git you should be able to use something like:

```
CREATE OR REPLACE FUNCTION create_array(bytes_size integer) RETURNS bytea AS
$$
    var a = new Array(bytes_size).fill(0);
    plv8.elog(NOTICE, 'Array length:', a.length);
    return a;
$$ LANGUAGE plv8;
```

give it a run, see if it does what you're expecting.  I have one border case for conversion to work out, at which point new tests will be written, and this will be a PR into plv8 mainline.

**Comment by dboris** [comment]
Awesome! Will give it a try tomorrow.

**Comment by JerrySievert** [comment]
as for @unoexperto's original question, I finally have an answer - `Array` is larger than 1 byte per element.  once this is fixed, switching to `Uint8Array` should work just fine.

**Comment by dboris** [comment]
I am observing a regression in accepting `bytea` as function parameter:
```
CREATE OR REPLACE FUNCTION get_array_length(a bytea) RETURNS int4 AS
$$
    return a.length;
$$ LANGUAGE plv8 IMMUTABLE STRICT;
```
```
select get_array_length(create_array(10));
NOTICE:  Array length: 10
ERROR:  array size exceeds the maximum allowed (134217727)
```

**Comment by JerrySievert** [comment]
that doesn't shock me, as I didn't spend any time in that code, and there are no tests for the `BYTEA` paths.

I've been testing to see how far back the issue with `BYTEA` goes, as it would be dependent on `v8` versions, and the `v8` support for differing types of arrays - I'll likely put out some patched versions in the next day or so, as these get fixed.

**Comment by JerrySievert** [comment]
see:

```
test=# select plv8_version();
 plv8_version
--------------
 2.0.3
(1 row)

test=# CREATE OR REPLACE FUNCTION get_array_length(a bytea) RETURNS int4 AS
test-# $$
test$#     return a.length;
test$# $$ LANGUAGE plv8 IMMUTABLE STRICT;
CREATE FUNCTION
test=# select get_array_length('hello world'::bytea);
 get_array_length
------------------
               11
(1 row)
```

whereas the bug for `Uint8Array` goes back as far as 2.0.3.

**Comment by JerrySievert** [comment]
I found it, i left one of my changes behind.

go ahead and get the update from git, and you should see it fixed.

I'll work on getting several tests written in not too long.

**Comment by dboris** [comment]
I can confirm my old code works correctly now and rewriting the `plpgsql` function that uses `set_bit` resulted in a nice performance improvement using `plv8`. Problem solved. Good job!

**Comment by JerrySievert** [comment]
can you quantify your speed difference for all of my hard work? :)

**Comment by dboris** [comment]
The `plv8` function is about 3 times faster :)

**Comment by JerrySievert** [comment]
awesome!  I'll backport the changes for those stuck on older versions as well.
