### ISSUE TITLE
How I can read file from local file system?

### ISSUE THREAD

**Issue by arturgspb** [plv8/plv8#190]
Hi! How I can read file from local file system easy?

**Comment by JerrySievert** [comment]
PLV8 is a "Trusted" language in postgres, which means it does not have access to the file system or to the network.

see: https://www.postgresql.org/docs/current/static/plperl-trusted.html

for an explanation.

There has been talk about building an untrusted version, but there's some more to do before we get there.

**Comment by arturgspb** [comment]
Thx, a lot!

**Comment by EvanCarroll** [comment]
Can we at least make milestone for a pl/v8u something like `v3` open an issue for it, and then dupe these onto that issue. It seems we have a lot of people trying to work around this.

**Comment by JerrySievert** [comment]
@EvanCarroll open an issue, and I'll create a milestone around it

**Comment by JerrySievert** [comment]
(as a trivia aside, my first foray into pl/v8 was building an untrusted version on it)

**Comment by EvanCarroll** [comment]
https://github.com/plv8/plv8/issues/222
