### ISSUE TITLE
Static build of newer v8 versions

### ISSUE THREAD

**Issue by emrul** [plv8/plv8#192]
Seems like the static libs have changed for newer v8 versions - I've compiled 5.6.184 on Linux using this Makefile.v8 https://github.com/emrul/plv8/blob/master/Makefile.v8

Sharing here in case anyway wants a newer V8.

Note: 5.6.184 is the current Linux DEV (https://omahaproxy.appspot.com) so treat accordingly.

**Comment by JerrySievert** [comment]
will look to see what has changed and update if need be.
