### ISSUE TITLE
Fedora 24 doesn't install properly. *workaround*

### ISSUE THREAD

**Issue by justintocci** [plv8/plv8#193]
Possibly helpful:

http://blog.endpoint.com/2013/11/using-javascript-in-postgresql.html

https://omahaproxy.appspot.com/

http://www.php-javascript.com/documentation/v8

What worked for me

dnf update
dnf install git
dnf install ncurses-compat-libs
dnf install gcc-c++
dnf install redhat-rpm-config
git clone https://github.com/plv8/plv8.git
Now make the following changes:

#define delete    delete_
//#define namespace namespace_
#define typeid    typeid_
//#define typename  typename_
//#define using   using_
mv ./build/v8-git-mirror-5.1.281.14/third_party/binutils/Linux_x64/Release/bin/ld.gold ./build/v8-git-mirror-5.1.281.14/third_party/binutils/Linux_x64/Release/bin/ld.gold.OLD
ln -s /usr/bin/ld.gold ./build/v8-git-mirror-5.1.281.14/third_party/binutils/Linux_x64/Release/bin/ld.gold
to the following files:

plv8.cc
plv8_type.cc
plv8_func.cc
Back to commands:

make static
make install

passwd postgres
su - postgres
initdb -D data -UTF8 -U postgres
pg_ctl -D data start
psql --host=127.0.0.1

CREATE EXTENSION plv8;
CREATE EXTENSION plv8;

CREATE FUNCTION test_v8(text) RETURNS text as $BODY$ return $1.substring(0,5); $BODY$ LANGUAGE plv8;

SELECT test_v8('1234567890'); // should return 12345

If someone could simplify this for Fedora users I'm sure they would be grateful.

**Comment by JerrySievert** [comment]
closing, all versions up to date.

**Comment by justintocci** [comment]
## On Fedora:

dnf update
dnf install git
dnf install ncurses-compat-libs
dnf install gcc-c++
dnf install redhat-rpm-config

wget https://github.com/plv8/plv8/archive/v1.5.4.tar.gz
tar -xzf v1.5.4.tar.gz
cd plv8-1.5.4

make static

### Error:

/usr/lib/gcc/x86_64-redhat-linux/6.2.1/../../../../lib64/crti.o(init+0x7): error: unsupported reloc 42 clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Comment:

Removing the need to comment out the "#define" lines in the .cc files helps a lot. Would be great if we didn't need to re-link the ld.gold file.

### Workaround:

Move a file
mv ./build/v8-git-mirror-4.3.66/third_party/binutils/Linux_x64/Release/bin/ld.gold ./build/v8-git-mirror-4.3.66/.third_party/binutils/Linux_x64/Release/bin/ld.gold.OLD

Link It
ln -s /usr/bin/ld.gold ./build/v8-git-mirror-4.3.66/third_party/binutils/Linux_x64/Release/bin/ld.gold

### Continue:

make static
make install

passwd postgres
su - postgres
initdb -D data -UTF8 -U postgres
pg_ctl -D data start
psql --host=127.0.0.1

CREATE EXTENSION plv8;

CREATE FUNCTION test_v8(text) RETURNS text as $BODY$ return $1.substring(0,5); $BODY$ LANGUAGE plv8;

SELECT test_v8('1234567890'); // should return 12345

**Comment by JerrySievert** [comment]
unfortunately, it using its own version of binutils is an upstream issue.  there are a couple of things you can try:

1. use the OS provided v8 (but memory says that it does not support all of the features, getting that fixed would be the best option - was it snapshot that was missing?)
2. open up an issue against v8, see if they'd be willing the fix their build system (or offer advice) to be able to correctly link against modern gcc/g++
3. open up an issue with gcc/g++ to get the linker fixed across versions
4. use the 2.0-dev (master) branch, which uses a modern version of v8
