### ISSUE TITLE
Install guide.

### ISSUE THREAD

**Issue by minimok** [plv8/plv8#194]
Have you ever installed this yourself?

What did you do???

Write it down!!!

**Comment by bendiy** [comment]
@JerrySievert This can be closed now:
https://github.com/plv8/plv8/blob/master/doc/plv8.md#installing-plv8

**Comment by anneb** [comment]
The install guide (now) says:
make installcheck

before:
sudo make install

The installcheck fails (or tests the previous install) in this order
