### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by seonixx** [plv8/plv8#195]
Attempting to compile with make static on mac OS 10.12.

> clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk'
> clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
> clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk'
> clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
> ld: warning: directory not found for option '-L/opt/local/Current/lib'
> ld: warning: directory not found for option '-L/opt/local/20150618/lib'
> ld: library not found for -lstdc++
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[1]: *** [plv8.so] Error 1
> make: *** [static] Error 2

Can anyone suggest what the issue might be? Am I missing lstdc++?

**Comment by JerrySievert** [comment]
while I get the deprecation notice as well, it appears that you are missing some libraries, as this should not be a fatal issue.

(note, I've compiled on both a MacBook Pro that has been upgraded as well as a brand new fresh install).

that said, try changing lines 70 and 71 in `Makefile.v8` to:

```
		CCFLAGS += -stdlib=libc++
		SHLIB_LINK += -stdlib=libc++
```

then `make clean` followed by `make static`.

this took the deprecation warning away from my, but I will need to spend some more time before determining if this is the proper fix.

**Comment by seonixx** [comment]
@JerrySievert thanks. I've made that mod and done a clean make.

Now I'm getting...

> /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.v8
> env CXXFLAGS=-fPIC CFLAGS=-fPIC /Applications/Xcode.app/Contents/Developer/usr/bin/make -C build/v8-git-mirror-5.1.281.14 native
> make[3]: Nothing to be done for `all'.
> test -f build/v8-git-mirror-5.1.281.14/out/native/libv8_base.a || \
> 		ln -s /Users/simon/Library/plv8/build/v8-git-mirror-5.1.281.14/out/native/obj.target/tools/gyp/libv8_base.a \
> 			build/v8-git-mirror-5.1.281.14/out/native/libv8_base.a
> test -f build/v8-git-mirror-5.1.281.14/out/native/libv8_nosnapshot.a || \
> 		ln -s /Users/simon/Library/plv8/build/v8-git-mirror-5.1.281.14/out/native/obj.target/tools/gyp/libv8_nosnapshot.a \
> 			build/v8-git-mirror-5.1.281.14/out/native/libv8_nosnapshot.a
> test -f build/v8-git-mirror-5.1.281.14/out/native/libv8_libbase.a || \
> 		ln -s /Users/simon/Library/plv8/build/v8-git-mirror-5.1.281.14/out/native/obj.target/tools/gyp/libv8_libbase.a \
> 			build/v8-git-mirror-5.1.281.14/out/native/libv8_libbase.a
> test -f build/v8-git-mirror-5.1.281.14/out/native/libv8_libplatform.a || \
> 		ln -s /Users/simon/Library/plv8/build/v8-git-mirror-5.1.281.14/out/native/obj.target/tools/gyp/libv8_libplatform.a \
> 			build/v8-git-mirror-5.1.281.14/out/native/libv8_libplatform.a
> test -f build/v8-git-mirror-5.1.281.14/out/native/libicui18n.a || \
> 		ln -s /Users/simon/Library/plv8/build/v8-git-mirror-5.1.281.14/out/native/obj.target/third_party/icu/libicui18n.a \
> 			build/v8-git-mirror-5.1.281.14/out/native/libicui18n.a
> test -f build/v8-git-mirror-5.1.281.14/out/native/libicuuc.a || \
> 		ln -s /Users/simon/Library/plv8/build/v8-git-mirror-5.1.281.14/out/native/obj.target/third_party/icu/libicuuc.a \
> 			build/v8-git-mirror-5.1.281.14/out/native/libicuuc.a
> test -f build/v8-git-mirror-5.1.281.14/out/native/libicudata.a || \
> 		ln -s /Users/simon/Library/plv8/build/v8-git-mirror-5.1.281.14/out/native/obj.target/third_party/icu/libicudata.a \
> 			build/v8-git-mirror-5.1.281.14/out/native/libicudata.a
> sed -e 's/^#undef PLV8_VERSION/#define PLV8_VERSION "2.0.0-dev"/' plv8_config.h.in > plv8_config.h
> g++ -Wall -O2 -std=c++11 -fno-rtti  -stdlib=libc++ -stdlib=libstdc++ -I. -I./ -I/Library/PostgreSQL/9.5/include/postgresql/server -I/Library/PostgreSQL/9.5/include/postgresql/internal -I/opt/local/20150618/include/libxml2  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include -fPIC -c -o plv8.o plv8.cc
> In file included from plv8.cc:8:
> ./plv8.h:12:10: fatal error: 'v8.h' file not found
> #include <v8.h>
>          ^
> 1 error generated.
> make[1]: *** [plv8.o] Error 1
> make: *** [static] Error 2

Any ideas? Thanks in advance.

**Comment by JerrySievert** [comment]
looks like something didn't get checked out and in the path correctly from the `make static` portion that downloads v8.

try:

```
$ rm -rf build
$ make static
```

which should attempt to download and build `v8` again.

**Comment by seonixx** [comment]
@JerrySievert I removed the entire build, made those mods to the Makefile, but I'm getting the same v8.h file not found on make static. Any other ideas? Thanks.

**Comment by JerrySievert** [comment]
can you share the first few lines of your `make static`?

```
 !  ~/w/plv8  ➦ 2aca0a0 $  make clean
rm -f plv8.so   libplv8.a  libplv8.pc
rm -f plv8_config.h plv8.control plv8--1.5.4.sql plcoffee.control plcoffee--1.5.4.sql plls.control plls--1.5.4.sql coffee-script.cc livescript.cc
rm -f plv8.o plv8_type.o plv8_func.o plv8_param.o coffee-script.o livescript.o
rm -rf results/ regression.diffs regression.out tmp_check/ log/
 ~/w/plv8  ➦ 2aca0a0 $  make static
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.v8
mkdir -p build
cd build; git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
Cloning into 'depot_tools'...
remote: Sending approximately 22.39 MiB ...
remote: Total 18410 (delta 11759), reused 18410 (delta 11759)
Receiving objects: 100% (18410/18410), 22.39 MiB | 7.13 MiB/s, done.
Resolving deltas: 100% (11759/11759), done.
Checking connectivity... done.
cd build; fetch v8; cd v8; git checkout 4.3.66; gclient sync
Running: gclient root
```
