### ISSUE TITLE
Update pgxn to 1.5.4

### ISSUE THREAD

**Issue by TheAngryByrd** [plv8/plv8#197]
Could you push the latest version 1.5.4 to pdxn (http://pgxn.org/dist/plv8/)? 

Thanks! :)

**Comment by JerrySievert** [comment]
on a new laptop, and unable to get logged into PGXN - working on it, will update when possible.

**Comment by JerrySievert** [comment]
there you go.

**Comment by TheAngryByrd** [comment]
🎸
