### ISSUE TITLE
Compiling branch master on Ubuntu 16.10 gives relocation error, recompile with -fPIC

### ISSUE THREAD

**Issue by jayk1961** [plv8/plv8#201]
Here's what I get. Ubuntu 16.10, gcc-6.2.0. I tried making sure everything compiled with -fPIC and it produced the same error. How do I get around it?

g++ -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -g -DLINUX_OOM_ADJ=0 -O2 -DMAP_HUGETLB=0x40000 -fpic -shared -o plv8.so plv8.o plv8_type.o plv8_func.o plv8_param.o coffee-script.o livescript.o -L/opt/PostgresPlus/9.5AS/lib -L/opt/local/20150616/181474c6-228d-4d58-b663-17981352ebce/lib -L/opt/local/20150616/181474c6-228d-4d58-b663-17981352ebce/lib  -L/opt/local/Current/lib -L/opt/local/20150616/181474c6-228d-4d58-b663-17981352ebce/lib  -Wl,--as-needed -Wl,-rpath,'/opt/PostgresPlus/9.5AS/lib',--enable-new-dtags  -lv8 -lv8 
/usr/bin/ld: plv8.o: relocation R_X86_64_PC32 against undefined symbol `_ZL12plv8_xact_cb9XactEventPvb' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
/opt/PostgresPlus/9.5AS/lib/pgxs/src/makefiles/../../src/Makefile.shlib:311: recipe for target 'plv8.so' failed
make: *** [plv8.so] Error 1

**Comment by JerrySievert** [comment]
which version of plv8 are you targeting?

and can you confirm which version of `v8` you are compiling against?  if you're using the system `v8` (3.14), it *will not work* with anything newer than plv8 1.4.*

**Comment by jayk1961** [comment]
I checked out the master version, so it would be the latest. Will it compile without a system version installed? The installed version is 1.4.5.

**Comment by JerrySievert** [comment]
Default system version on my ubuntu 16.10 is 3.14, which will build against 1.4.5.  The 1.4 branch is maintained solely for Debian/ubuntu, which is years behind on libv8.

V8 made some major changes multiple times between versions, and 1.5 compiles against 4.5, and master compiles against 5.1 (in line with current nodejs versions).

If you want speed and modern features, I'd recommend just running make static which will download and compile a modern version of v8.

**Comment by jayk1961** [comment]
I removed the system installed version to see if it would compile without it. I get the relocation error.

**Comment by JerrySievert** [comment]
Did you try with make static?

I've successfully compiled on 16.10.

**Comment by jayk1961** [comment]
This is the error I get when running make static:

 make static
make -f Makefile.v8
make[1]: Entering directory '/wl2k/src/bustabit/plv8'
env CXXFLAGS=-fPIC CFLAGS=-fPIC make -C build/v8-git-mirror-5.1.281.14
native
make[2]: Entering directory
'/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.1.281.14'
make[3]: Entering directory
'/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.1.281.14/out'
  LINK(target)
/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.1.281.14/out/native/mksnapshot
/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.1.281.14/third_party/binutils/Linux_x64/Release/bin/ld.gold:
error:
/usr/lib/gcc/x86_64-linux-gnu/6.2.0/../../../x86_64-linux-gnu/crt1.o:
unsupported reloc 41 against global symbol __libc_start_main
/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.1.281.14/third_party/binutils/Linux_x64/Release/bin/ld.gold:
error:
/usr/lib/gcc/x86_64-linux-gnu/6.2.0/../../../x86_64-linux-gnu/crti.o:
unsupported reloc 42 against global symbol __gmon_start__
/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.1.281.14/third_party/binutils/Linux_x64/Release/bin/ld.gold:
error: /usr/lib/x86_64-linux-gnu/libc_nonshared.a(atexit.oS): unsupported
reloc 42 against global symbol __dso_handle
/usr/lib/gcc/x86_64-linux-gnu/6.2.0/../../../x86_64-linux-gnu/crti.o(.init+0x7):
error: unsupported reloc 42
/usr/lib/gcc/x86_64-linux-gnu/6.2.0/../../../x86_64-linux-gnu/crt1.o:function
_start: error: unsupported reloc 41
/usr/lib/x86_64-linux-gnu/libc_nonshared.a(atexit.oS):function atexit:
error: unsupported reloc 42
clang: error: linker command failed with exit code 1 (use -v to see
invocation)
tools/gyp/mksnapshot.target.native.mk:267: recipe for target
'/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.1.281.14/out/native/mksnapshot'
failed
make[3]: ***
[/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.1.281.14/out/native/mksnapshot]
Error 1
make[3]: Leaving directory
'/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.1.281.14/out'
Makefile:319: recipe for target 'native' failed
make[2]: *** [native] Error 2
make[2]: Leaving directory
'/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.1.281.14'
Makefile.v8:35: recipe for target
'build/v8-git-mirror-5.1.281.14/out/native/libv8_snapshot.a' failed
make[1]: *** [build/v8-git-mirror-5.1.281.14/out/native/libv8_snapshot.a]
Error 2
make[1]: Leaving directory '/wl2k/src/bustabit/plv8'
Makefile:153: recipe for target 'static' failed
make: *** [static] Error 2

**Comment by JerrySievert** [comment]
looks to be an upstream issue with v8 - I'm going to see where they fixed the tools, and bump master up to above this version.

**Comment by JerrySievert** [comment]
see: https://bbs.archlinux.org/viewtopic.php?id=209871

**Comment by jayk1961** [comment]
Gotcha. It's a binutils (ld-gold?) problem. Let me know when it will be safe to try again.

**Comment by JerrySievert** [comment]
yup exactly.  v8 uses its own build chain to compile everything, and sometimes causes additional issues between versions.  whee?

**Comment by jayk1961** [comment]
Cleared directory and re-cloned. Same problem/error.


sc01:/wl2k/src/bustabit/plv8# make static
make -f Makefile.v8
make[1]: Entering directory '/wl2k/src/bustabit/plv8'
env CXXFLAGS=-fPIC CFLAGS=-fPIC make -C build/v8-git-mirror-5.1.281.14
native
make[2]: Entering directory
'/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.1.281.14'
make[3]: Entering directory
'/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.1.281.14/out'
  LINK(target)
/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.1.281.14/out/native/mksnapshot
/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.1.281.14/third_party/binutils/Linux_x64/Release/bin/ld.gold:
error:
/usr/lib/gcc/x86_64-linux-gnu/6.2.0/../../../x86_64-linux-gnu/crt1.o:
unsupported reloc 41 against global symbol __libc_start_main
/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.1.281.14/third_party/binutils/Linux_x64/Release/bin/ld.gold:
error:
/usr/lib/gcc/x86_64-linux-gnu/6.2.0/../../../x86_64-linux-gnu/crti.o:
unsupported reloc 42 against global symbol __gmon_start__
/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.1.281.14/third_party/binutils/Linux_x64/Release/bin/ld.gold:
error: /usr/lib/x86_64-linux-gnu/libc_nonshared.a(atexit.oS): unsupported
reloc 42 against global symbol __dso_handle
/usr/lib/gcc/x86_64-linux-gnu/6.2.0/../../../x86_64-linux-gnu/crti.o(.init+0x7):
error: unsupported reloc 42
/usr/lib/gcc/x86_64-linux-gnu/6.2.0/../../../x86_64-linux-gnu/crt1.o:function
_start: error: unsupported reloc 41
/usr/lib/x86_64-linux-gnu/libc_nonshared.a(atexit.oS):function atexit:
error: unsupported reloc 42
clang: error: linker command failed with exit code 1 (use -v to see
invocation)
tools/gyp/mksnapshot.target.native.mk:267: recipe for target
'/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.1.281.14/out/native/mksnapshot'
failed
make[3]: ***
[/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.1.281.14/out/native/mksnapshot]
Error 1
make[3]: Leaving directory
'/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.1.281.14/out'
Makefile:319: recipe for target 'native' failed
make[2]: *** [native] Error 2
make[2]: Leaving directory
'/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.1.281.14'
Makefile.v8:35: recipe for target
'build/v8-git-mirror-5.1.281.14/out/native/libv8_snapshot.a' failed
make[1]: *** [build/v8-git-mirror-5.1.281.14/out/native/libv8_snapshot.a]
Error 2
make[1]: Leaving directory '/wl2k/src/bustabit/plv8'
Makefile:145: recipe for target 'static' failed
make: *** [static] Error 2
sc01:/wl2k/src/bustabit/plv8#

**Comment by JerrySievert** [comment]
you need to clone from my fork: https://github.com/JerrySievert/plv8 as I have not merged it in yet.

you're still getting `5.1.281.14`, whereas you should be getting `5.4.500.43` (see https://github.com/JerrySievert/plv8/blob/master/Makefile.v8#L10).

I have confirmation locally, and from travis-ci that things are working, but I want to make sure your issue is solved before I merge.

```shell
$ git clone https://github.com/JerrySievert/plv8.git
Cloning into 'plv8'...
remote: Counting objects: 1282, done.
remote: Total 1282 (delta 0), reused 0 (delta 0), pack-reused 1282
Receiving objects: 100% (1282/1282), 594.42 KiB | 464.00 KiB/s, done.
Resolving deltas: 100% (864/864), done.
$ cd plv8
$ make static
```

**Comment by jayk1961** [comment]
Still popping up:

sc01:/wl2k/src/bustabit/plv8# make static
make -f Makefile.v8
make[1]: Entering directory '/wl2k/src/bustabit/plv8'
env CXXFLAGS=-fPIC CFLAGS=-fPIC make -C build/v8-git-mirror-5.4.500.43
native
make[2]: Entering directory
'/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.4.500.43'
make[3]: Entering directory
'/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.4.500.43/out'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory
'/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.4.500.43/out'
make[2]: Leaving directory
'/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.4.500.43'
test -f build/v8-git-mirror-5.4.500.43/out/native/libv8_base.a || \
        ln -s
/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.4.500.43/out/native/obj.target/src/libv8_base.a
\
                build/v8-git-mirror-5.4.500.43/out/native/libv8_base.a
test -f build/v8-git-mirror-5.4.500.43/out/native/libv8_nosnapshot.a || \
        ln -s
/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.4.500.43/out/native/obj.target/src/libv8_nosnapshot.a
\
                build/v8-git-mirror-5.4.500.43/out/native/libv8_nosnapshot.a
test -f build/v8-git-mirror-5.4.500.43/out/native/libv8_libbase.a || \
        ln -s
/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.4.500.43/out/native/obj.target/src/libv8_libbase.a
\
                build/v8-git-mirror-5.4.500.43/out/native/libv8_libbase.a
test -f build/v8-git-mirror-5.4.500.43/out/native/libv8_libplatform.a || \
        ln -s
/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.4.500.43/out/native/obj.target/src/libv8_libplatform.a
\

build/v8-git-mirror-5.4.500.43/out/native/libv8_libplatform.a
test -f build/v8-git-mirror-5.4.500.43/out/native/libv8_libsampler.a || \
        ln -s
/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.4.500.43/out/native/obj.target/src/libv8_libsampler.a
\
                build/v8-git-mirror-5.4.500.43/out/native/libv8_libsampler.a
test -f build/v8-git-mirror-5.4.500.43/out/native/libicui18n.a || \
        ln -s
/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.4.500.43/out/native/obj.target/third_party/icu/libicui18n.a
\
                build/v8-git-mirror-5.4.500.43/out/native/libicui18n.a
test -f build/v8-git-mirror-5.4.500.43/out/native/libicuuc.a || \
        ln -s
/wl2k/src/bustabit/plv8/build/v8-git-mirror-5.4.500.43/out/native/obj.target/third_party/icu/libicuuc.a
\
                build/v8-git-mirror-5.4.500.43/out/native/libicuuc.a
g++ -Wall -Wmissing-prototypes -Wpointer-arith
-Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute
-Wformat-security -fno-strict-aliasing -fwrapv -g -DLINUX_OOM_ADJ=0 -O2
-fPIC -DMAP_HUGETLB=0x40000 -fpic -shared -o plv8.so plv8.o plv8_type.o
plv8_func.o plv8_param.o coffee-script.o livescript.o
-L/usr/lib/x86_64-linux-gnu
-L/opt/local/20150616/181474c6-228d-4d58-b663-17981352ebce/lib
-L/opt/local/20150616/181474c6-228d-4d58-b663-17981352ebce/lib
 -L/opt/local/Current/lib
-L/opt/local/20150616/181474c6-228d-4d58-b663-17981352ebce/lib
 -Wl,--as-needed -Wl,-rpath,'/usr/lib/x86_64-linux-gnu',--enable-new-dtags
 build/v8-git-mirror-5.4.500.43/out/native/libv8_base.a
build/v8-git-mirror-5.4.500.43/out/native/libv8_nosnapshot.a
build/v8-git-mirror-5.4.500.43/out/native/libv8_libplatform.a
build/v8-git-mirror-5.4.500.43/out/native/libv8_libbase.a
build/v8-git-mirror-5.4.500.43/out/native/libv8_libsampler.a
build/v8-git-mirror-5.4.500.43/out/native/libicui18n.a
build/v8-git-mirror-5.4.500.43/out/native/libicuuc.a -lv8_libplatform
-Lbuild/v8-git-mirror-5.4.500.43/out/native -lrt
/usr/bin/ld: plv8.o: relocation R_X86_64_PC32 against undefined symbol
`_ZL12plv8_xact_cb9XactEventPvb' can not be used when making a shared
object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
/usr/lib/postgresql/9.5/lib/pgxs/src/makefiles/../../src/Makefile.shlib:311:
recipe for target 'plv8.so' failed
make[1]: *** [plv8.so] Error 1
make[1]: Leaving directory '/wl2k/src/bustabit/plv8'
Makefile:145: recipe for target 'static' failed
make: *** [static] Error 2
sc01:/wl2k/src/bustabit/plv8#

**Comment by jayk1961** [comment]
Scratch that. It is now built.

**Comment by jayk1961** [comment]
Ok, it built but failed when added to postgres:

============== running regression test queries        ==============
test init-extension           ... ok
test plv8                     ... FAILED
test plv8-errors              ... ok
test inline                   ... ok
test json                     ... ok
test startup_pre              ... ok
test startup                  ... ok
test varparam                 ... ok
test json_conv                ... ok
test jsonb_conv               ... ok
test window                   ... ok
test guc                      ... ok
test es6                      ... ok
test arraybuffer              ... ok
test composites               ... ok
test currentresource          ... ok
test dialect                  ... ok


What is branch 1.5 host operating system? 1.5 is the most current, is that
correct? I don't need to be running debian/ubuntu.

**Comment by JerrySievert** [comment]
1.5 is the most current released version, but master (2.0) is pretty darned stable.

can you post the output of `regressions.diff`, I'm curious what the failed test was.

**Comment by jayk1961** [comment]
Most of the issues I was having were either my fault or simple little
fixes. I was able to pretty much get PLV8 from github to compile, both with
"make" and "make static". That's the master-2.0 version, correct?

Now, using postgres-9.5 it works fine. And I believe postgres-9.6 worked as
well. I am using enterprisedb postgres and I built both the dynamic and
static library successfully. When I tried to create the PLV8 extension, I
get the following:

root=# CREATE EXTENSION PLV8;
ERROR:  could not load library "/wl2k/PostgresPlus/9.5AS/lib/plv8.so":
/wl2k/PostgresPlus/9.5AS/lib/plv8.so: undefined symbol:
_ZN2v87Context3NewEPNS_7IsolateEPNS_22ExtensionConfigurationENS_5LocalINS_14ObjectTemplateEEENS5_INS_5ValueEEE


This seems like a common relocation error, but I have no idea how to fix
it. PLV8 was built against the dev & library files for enterprisedb 9.5AS
(Advanced Server).

This website:

https://www.enterprisedb.com/blog/compiling-plv8-postgres-plus-advanced-server

explains how to build PLV8 1.5-dev1 on Postgres EnterpriseDB 9.1 and
higher. I checked out ubuntufix, 1.5, and the 1.4 branch and none of them
compiled, they had too many errors on my Ubuntu 16.10 box. So I'm sticking
with the master version. Do you know how to resolve the undefined symbol
version I am getting with EnterpriseDB AdvancedServer 9.5?

**Comment by JerrySievert** [comment]
1.5-dev1 is about 2 years old at this point, and I've actually never heard of Postgres "Advanced Server" - are you sure you did a `make install`?

`make installcheck` should give you an output of the tests, can you please copy those here?

**Comment by Melab** [comment]
> yup exactly. v8 uses its own build chain to compile everything, and sometimes causes additional issues between versions. whee?

If Google's own toolchain can cause compilation errors between versions, then they surely should have caught that for stable commits (e.g., checking out tag `4.8.47` of V8), right?

**Comment by JerrySievert** [comment]
> If Google's own toolchain can cause compilation errors between versions, then they surely should have caught that for stable commits (e.g., checking out tag 4.8.47 of V8), right?

no.
