### ISSUE TITLE
ES6 support

### ISSUE THREAD

**Issue by romansky** [plv8/plv8#203]
What is the status of ES6 support? 
Tried using `Array.prototype.find` for example, doesn't work.
Is this going to be supported in V2?
Looks like V2 is in stand still, is it not?

**Comment by JerrySievert** [comment]
```
[local] jerry@test=# DO LANGUAGE plv8 $$ Array.prototype.find(function () {});  $$;
DO
Time: 0.266 ms
```
latest PR updates to match nodejs 7, not sure how much further I can take it without v8 updating.
