### ISSUE TITLE
Creating extension crashes postmaster

### ISSUE THREAD

**Issue by devrimgunduz** [plv8/plv8#210]
Hi,

When I try to create plv8 2.0.0 extension against PostgreSQL 9.6.2, postmaster crashes. Below is a snippet from the PostgreSQL logs

#
# Fatal error in ../src/snapshot/natives-external.cc, line 122
# Check failed: holder_.
#

==== C stack trace ===============================

 1: V8_Fatal
 2: 0x7fcf4410b586
 3: v8::internal::Heap::CreateInitialObjects()
 4: v8::internal::Heap::CreateHeapObjects()
 5: v8::internal::Isolate::Init(v8::internal::Deserializer*)
 6: v8::Isolate::New(v8::Isolate::CreateParams const&)
 7: _PG_init
 8: 0x7e60f7
 9: load_external_function
10: fmgr_c_validator
11: OidFunctionCall1Coll
12: ProcedureCreate
13: CreateFunction
14: 0x6e93fe
15: standard_ProcessUtility
16: 0x584a2d
17: 0x585a86
18: CreateExtension
19: 0x6e8f49
20: standard_ProcessUtility
21: 0x6e57f4
22: 0x6e6305
23: PortalRun
24: PostgresMain
25: 0x470a65
26: PostmasterMain
27: main
28: __libc_start_main
29: _start
< 2017-02-19 10:43:33.714 GMT > LOG:  server process (PID 13036) was terminated by signal 4: Illegal instruction
< 2017-02-19 10:43:33.714 GMT > DETAIL:  Failed process was running: create extension plv8;

Can you please take a look?

Thanks!

**Comment by JerrySievert** [comment]
did you build with `make static`, or are you using a system libv8?

**Comment by devrimgunduz** [comment]
Hi,

It is a plain make -- and v8 version is:

$ rpm -qv v8
v8-5.2.258-7.fc25.x86_64

Regards, Devrim

**Comment by JerrySievert** [comment]
you'll need a newer v8 version - there have been some major breaking changes between seemingly close versions.  also, it seems that something is a little funky with the redhat build of libv8.

`make static` builds version 5.4.500.43, and is the recommended method for building.  just make sure you're building against the release, not against master.

**Comment by JerrySievert** [comment]
after you `make install`, you can verify by running the standard Postgres testing mechanism:

`make installcheck`

you should see output that looks like this:

```
============== running regression test queries        ==============
test init-extension           ... ok
test plv8                     ... ok
test plv8-errors              ... ok
test inline                   ... ok
test json                     ... ok
test startup_pre              ... ok
test startup                  ... ok
test varparam                 ... ok
test json_conv                ... ok
test jsonb_conv               ... ok
test window                   ... ok
test guc                      ... ok
test es6                      ... ok
test arraybuffer              ... ok
test composites               ... ok
test currentresource          ... ok
test dialect                  ... ok

======================
 All 17 tests passed.
======================
```

(this is using the same version of v8 as node.js, which also builds a static v8, and that test output is 2.0.0 against postgres 9.6)

**Comment by devrimgunduz** [comment]
$ make installcheck
/usr/pgsql-9.6/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/pgsql-9.6/bin'    --dbname=contrib_regression init-extension plv8 plv8-errors inline json startup_pre startup varparam json_conv jsonb_conv window guc es6 arraybuffer composites currentresource dialect
(using postmaster on Unix socket, port 5496)
============== dropping database "contrib_regression" ==============
DROP DATABASE
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test init-extension           ... FAILED (test process exited with exit code 2)
test plv8                     ... FAILED (test process exited with exit code 2)
test plv8-errors              ... FAILED (test process exited with exit code 2)
test inline                   ... FAILED (test process exited with exit code 2)
test json                     ... FAILED (test process exited with exit code 2)
test startup_pre              ... FAILED (test process exited with exit code 2)
test startup                  ... FAILED (test process exited with exit code 2)
test varparam                 ... FAILED (test process exited with exit code 2)
test json_conv                ... FAILED (test process exited with exit code 2)
test jsonb_conv               ... FAILED (test process exited with exit code 2)
test window                   ... FAILED (test process exited with exit code 2)
test guc                      ... FAILED (test process exited with exit code 2)
test es6                      ... FAILED (test process exited with exit code 2)
test arraybuffer              ... FAILED (test process exited with exit code 2)
test composites               ... FAILED (test process exited with exit code 2)
test currentresource          ... FAILED (test process exited with exit code 2)
test dialect                  ... FAILED (test process exited with exit code 2)

========================
 17 of 17 tests failed. 
========================

**Comment by JerrySievert** [comment]
was this after running `make static` and `make install`?

**Comment by devrimgunduz** [comment]
This is after make install, and against Fedora's v8.

I read your comment about Red Hat's v8, but RPMs try to stick with OS-supplied packages. Otherwise, many people won't install them :(

Regards,

**Comment by JerrySievert** [comment]
RedHat's/Fedora's v8 simply won't work with PLV8 (or node.js for that matter), the error that you are seeing is strictly a v8 issue, and only tangentially related to PLV8 (in that PLV8 initializes the v8 engine, the crash that you are seeing is part of that initialization).

the only way that PLV8 will work on Fedora/RedHat is to compile using `make static`, which will download 5.4.500.43, build it with Google's tools (building v8 requires very specific versions of compilers, which are downloaded at build time by the v8 build script).

doing this will build PLV8 with a static version of v8, and link with it - same mechanism as node.js when compiling.

I applaud the package maintainers for trying to get to a more modern version of v8 (ubuntu/debian us 3.14, which is 4 years old at this point, and not compatible with any newer version of PLV8 past 1.4), but it seems that the version that is built is not compatible for embedding - you will not get it to work.

once you `make static`, (which will likely take about 40 minutes to build), you will see it working, as v8 will have been correctly configured, built, and will be a version that is compatible with PLV8.

**Comment by devrimgunduz** [comment]
Yeah, it compiled and worked fine with make static. 

Thanks for the prompt responses. I think we should close this issue.

Regards, Devrim

**Comment by JerrySievert** [comment]
glad to hear it's working!  one of the reasons why we're tracking the same versions of v8 is to make it easier on maintainers wherever possible - this is the same reason why PLV8 1.4 is maintained as well.

hopefully, v8 itself will become more stable over time, and distro maintainers can move to something more modern.
