### ISSUE TITLE
plv8 swallows error stack

### ISSUE THREAD

**Issue by bendiy** [plv8/plv8#211]
If PostgreSQL throws an error up the stack from a `plv8.execute(...)`, the actual error stack is swallowed and hidden. When using `plpgsql`, the actual error line is reported.

Here's an example to demonstrate this:
```sql
CREATE OR REPLACE FUNCTION public._anerror()
  RETURNS boolean AS
$BODY$
BEGIN

  RAISE EXCEPTION 'my error';

  RETURN true;

END;
$BODY$
LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public._callsanerror()
  RETURNS boolean AS
$BODY$
DECLARE
  something boolean;
BEGIN
  something := _anerror();

  RETURN something;
END;
$BODY$
  LANGUAGE plpgsql;
```

Then call `_callsanerror()` function either directly or through `plpgsql`:
```sql
SELECT _callsanerror();
```

Outputs the message:
```
ERROR:  my error
CONTEXT:  PL/pgSQL function _callsanerror() line 5 at assignment
********** Error **********

ERROR: my error
SQL state: P0001
Context: PL/pgSQL function _callsanerror() line 5 at assignment
```

```sql
DO $$
BEGIN
  SELECT _callsanerror();
END;
$$ LANGUAGE plpgsql;
```

Outputs the message:
```
ERROR:  my error
CONTEXT:  PL/pgSQL function _callsanerror() line 5 at assignment
SQL statement "SELECT _callsanerror()"
PL/pgSQL function inline_code_block line 3 at SQL statement
********** Error **********

ERROR: my error
SQL state: P0001
Context: PL/pgSQL function _callsanerror() line 5 at assignment
SQL statement "SELECT _callsanerror()"
PL/pgSQL function inline_code_block line 3 at SQL statement
```

When called from `plv8`, the relevate stack line that actually threw the error is swallowed:
```sql
DO $$
  plv8.execute("SELECT _callsanerror();");
$$ LANGUAGE plv8;
```

Outputs the message:
```
ERROR:  my error
DETAIL:  undefined() LINE 2:   plv8.execute("SELECT _callsanerror();");
********** Error **********

ERROR: my error
SQL state: XX000
Detail: undefined() LINE 2:   plv8.execute("SELECT _callsanerror();");
```
No reference to `Context: PL/pgSQL function _callsanerror() line 5 at assignment`.

Is there any way to make use of `PG_EXCEPTION_CONTEXT` and return the full stack?
https://www.postgresql.org/docs/current/static/plpgsql-control-structures.html#PLPGSQL-EXCEPTION-DIAGNOSTICS

**Comment by JerrySievert** [comment]
it hasn't been super high priority - I will try to spend some time on it, but if anyone else wants to send a PR, I'd be happy to look at it.

**Comment by bendiy** [comment]
Calling:
```sql
    RAISE EXCEPTION USING
      MESSAGE = 'A First Name is required.',
      DETAIL = 'A detailed message??',
      HINT = 'Do this to avoid that.',
      COLUMN = 'firstName'
      ;
```

Right now, the error object looks like:
```json
{
  "column_name":"firstName",
  "constraint_name":null,
  "datatype_name":null,
  "message": "A First Name is required.",
  "schema_name":null,
  "sqlerrcode":"P0001",
  "stack": "some stack trace here...",
  "table_name":null
}
```
It would be nice to also include the following:
`DETAIL`
`HINT`

**Comment by bendiy** [comment]
Error messages are reported here:
https://github.com/plv8/plv8/blob/57db50d0dade7a840a8f325e5d0c89ef7fc71466/plv8.cc#L1769-L1773

**Comment by bendiy** [comment]
Looking at how [psycopg2](https://github.com/psycopg/psycopg2/blob/496cef80c4d6f23bd3b3d602ea4c7828005753f3/psycopg/pqpath.c#L743-L744) does it, they use `libpg` and call `PQerrorMessage()`:
https://www.postgresql.org/docs/current/static/libpq-status.html#LIBPQ-PQERRORMESSAGE

**Comment by bendiy** [comment]
PostgreSQL's `CopyErrorData()` has:
`detail`
`detail_log`
`hint`
`context`
`internalquery`
`assoc_context`
https://doxygen.postgresql.org/elog_8c_source.html#l01497
And a few more that might exist:
https://doxygen.postgresql.org/elog_8h_source.html#l00329

I think `edata->context` is the stack:
https://doxygen.postgresql.org/elog_8h.html#ad811b6bbae02e9f946cef448df4f6701

That can be added here:
https://github.com/plv8/plv8/blob/57db50d0dade7a840a8f325e5d0c89ef7fc71466/plv8_func.cc#L262
