### ISSUE TITLE
Failed to create ICU collator, are ICU data files missing?

### ISSUE THREAD

**Issue by hsyed** [plv8/plv8#213]
I'm currently developing with plv8 2.0 using the docker images from the following repository [clkao/docker-postgres-plv8](https://github.com/clkao/docker-postgres-plv8). When I tried to load something requiring icu support the backend crashes. 

Initially I thought the build might need tuning or that the image might need to be further configured but I just can't get it to work. The following snippet will trigger the backend crash. 

I have an issue open on the docker repo as well #https://github.com/clkao/docker-postgres-plv8/issues/24.
```
DO LANGUAGE plv8 $$
var options =
  { year: "numeric", month: "long", day: "numeric",
    hour: "2-digit", minute: "2-digit",
    timeZoneName: "short", timeZone: "UTC" };
var portugueseTime =
  new Intl.DateTimeFormat(["pt-BR", "pt-PT"], options);
$$;
```

**Comment by JerrySievert** [comment]
it is compiled with icu, and v8 is giving a `EXC_BAD_INSTRUCTION` exception.  it's deep inside of v8, and I'm trying to track it down.

**Comment by JerrySievert** [comment]
v8 does not seem to put the ICU data files in a good place if you are building with the copy of ICU that is bundled.

you have a couple of options:

* compile with the system ICU by setting `use_system_icu=1` in `icu.gyp`
* check out `master` in https://github.com/JerrySievert/plv8

if you choose the latter, you will want to look at `contrib/README.md` and follow the instructions there.  note, this is a development branch, and is currently building against v8 5.8.301.
