### ISSUE TITLE
Latest `plv8_start_proc` change to check `has_function_privilege_name` fails if the function has parameters

### ISSUE THREAD

**Issue by bendiy** [plv8/plv8#217]
@JerrySievert 
Your change here:
https://github.com/plv8/plv8/commit/c25ba0dd6de7e08e062606007e89f7c870974027#diff-6df1ac89a50d497c41daa4c6dcb7c875R1440

breaks our init function. Its signature is:
```sql
CREATE OR REPLACE FUNCTION xt.js_init(
    debug boolean DEFAULT false,
    initialize boolean DEFAULT false)
  RETURNS void AS
$BODY$
  ...
```

Before this change, that is now in plv8 version `1.4.9`, `.1.5.6.` and `2.0.1` (`2.0.2`??), this function worked fine as the defaults of false were used when it called `xt.js_init()`.

The `has_function_privilege_name` check has to be called with the exact signature. The default concatenates `()`:
```c++
			char proc[NAMEDATALEN + 32];
			strcpy(proc, plv8_start_proc);
			strcat(proc, "()");
```
Which throws an error.

That matches running this query:
```sql
SELECT has_function_privilege('xt.js_init()', 'EXECUTE');
 > ERROR:  function "xt.js_init()" does not exist
```
When we really need to run:
```sql
SELECT has_function_privilege('xt.js_init(boolean, boolean)', 'EXECUTE');
```

~We have a workaround, which is to define an overload function:~
```
-- This doesn't work. See comment below.
CREATE OR REPLACE FUNCTION xt.js_init()
  RETURNS void AS
$BODY$
BEGIN
  PERFORM xt.js_init(false, false);
END;
$BODY$
  LANGUAGE plpgsql VOLATILE;
```

Can this privilege check be re-worked to support a `start_proc` function with parameters?

`apt-get` is now delivering version `1.4.9` and this is an API breaking change that is causing production systems to fail after an `apt-get upgrade` to `1.4.9`.

**Comment by JerrySievert** [comment]
Yes. I can look for a method signature and try against that, but won't have working internet access until tomorrow at the earliest. 

The change (back-ported) was a security fix - once things are propagated further, I'll make an announcement.

**Comment by bendiy** [comment]
Thanks!

**Comment by bendiy** [comment]
1. We can't use an overload because `plv8` doesn't support multiple functions with the same name and different parameters.
2. We can't use a `plpgsql` function because the `start_proc` execution checks for `plv8` language only functions.
3. We can't move `xt.js_init` to a new name and wrap it because we have too much code that calls it directly and some of it passes parameters `true`.

That leaves us with only one workaround that I can see, which is adding a `xt.js_init_fix()` plv8 wrapper function and setting `plv8.start_proc = 'xt.js_init_fix'`.

```
CREATE OR REPLACE FUNCTION xt.js_init_fix()
  RETURNS void AS
$BODY$
  plv8.execute("SELECT xt.js_init(false, false);");
$BODY$
  LANGUAGE plv8 VOLATILE;
```

For production servers, I think it's going to be easier to remove the plv8 install from using `apt-get` and manually install `1.4.8` until a new version with a fix is released.

**Comment by JerrySievert** [comment]
testing a fix now, then will backport if it is successful.  at that point I'll contact the Debian maintainers and ask for them to get it out.

if all goes well, should have a release tomorrow.

**Comment by JerrySievert** [comment]
confirmed to work, will cut releases tomorrow morning.

**Comment by bendiy** [comment]
Awesome. Thanks Jerry!

**Comment by JerrySievert** [comment]
it's amazing what one can get done when they're unemployed :)

**Comment by JerrySievert** [comment]
1.4.10, 1.5.7, 2.0.3 all released, I've notified the Debian maintainer, so going to close this.
