### ISSUE TITLE
2.1.0 crashes postmaster

### ISSUE THREAD

**Issue by devrimgunduz** [plv8/plv8#231]
Hi,

I'm getting the following in PG logs. This is not new on 2.1.0, I also got this on 2.0.3. This happens on Fedora 25 PG 9.6 while running "CREATE EXTENSION plv8;"

FWIW: v8-5.2.258 is installed:

#
# Fatal error in ../src/snapshot/natives-external.cc, line 122
# Check failed: holder_.
#

==== C stack trace ===============================

 1: V8_Fatal
 2: 0x7f46af4d6586
 3: v8::internal::Heap::CreateInitialObjects()
 4: v8::internal::Heap::CreateHeapObjects()
 5: v8::internal::Isolate::Init(v8::internal::Deserializer*)
 6: v8::Isolate::New(v8::Isolate::CreateParams const&)
 7: _PG_init
 8: 0x7e6a27
 9: load_external_function
10: fmgr_c_validator
11: OidFunctionCall1Coll
12: ProcedureCreate
13: CreateFunction
14: 0x6e9b6e
15: standard_ProcessUtility
16: 0x7f46f2e2f0a7
17: 0x584c35
18: 0x585c86
19: CreateExtension
20: 0x6e96b9
21: standard_ProcessUtility
22: 0x7f46f2e2f0a7
23: 0x6e5f64
24: 0x6e6a75
25: PortalRun
26: PostgresMain
27: 0x470b85
28: PostmasterMain
29: main
30: __libc_start_main
31: _start
< user= db= host= pid=7389 time=2017-07-10 12:25:27.201 BST > LOG:  server process (PID 20761) was terminated by signal 4: Illegal instruction
< user= db= host= pid=7389 time=2017-07-10 12:25:27.201 BST > DETAIL:  Failed process was running: CREATE EXTENSION plv8 ;
< user= db= host= pid=7389 time=2017-07-10 12:25:27.201 BST > LOG:  terminating any other active server processes

**Comment by JerrySievert** [comment]
As noted in a couple of other issues, you should not be using the fedora v8 library, it is broken and does not work. 

You need to compile with make static, or roll your own copy of v8.
