### ISSUE TITLE
plv8 install and postgres

### ISSUE THREAD

**Issue by gittempo** [plv8/plv8#236]
anybody write me some steps to install plv8 and configure correctly to work with postgres.

i have postgres version 9.5 installed on ubuntu box
plv8 version is 1.4.6

anyone please help me with step by step commands so i get rid of this error / bug
and i get this error

error: buffer XXXX is not owned by resource owner TopTransaction

BTW how do i upgrade plv8 to 1.4.7 or above?

**Comment by blueeag** [comment]
https://github.com/plv8/plv8/issues/164#issuecomment-331968574
