### ISSUE TITLE
Wish request: add typescript support

### ISSUE THREAD

**Issue by egandro** [plv8/plv8#238]
Please add Typescript support as additional language.

**Comment by JerrySievert** [comment]
not likely to happen.

**Comment by egandro** [comment]
If I will do it, would you add it?

**Comment by JerrySievert** [comment]
No

**Comment by egandro** [comment]
Any reason for this "no"?

**Comment by JerrySievert** [comment]
a few, actually.

a) there's been a push to remove extra-language support from the extension, which will end up occurring, since supporting multiple "languages" that compile to javascript themselves is not only an extra burden but ends up being a lot more pain to maintain for extremely limited upside

b) there are no source maps, and since you can already compile to javascript, there's really no upside to this

c) you are literally the only person to ever ask for this, and to add that level of support to a project for a single request is a ton of work, especially given a and b.

**Comment by nbering** [comment]
As a TypeScript user myself, I think time would be better spent in creating tooling support to make compilation and deployment of plv8 procedures really easy. I agree with @JerrySievert's points. It all runs as JavaScript in the end anyway. Compiling TypeScript to JavaScript is a waste of CPU and RAM on a database server.

**Comment by JerrySievert** [comment]
thanks @nbering as the person who ends up maintaining this extension, I very much appreciate another opinion on it :)

**Comment by JerrySievert** [comment]
I do like typescript, don't get me wrong - it's just such a burden to support, especially when I'm looking to simplify everything ...

**Comment by alitaheri** [comment]
I write everything in typescript. Yet I believe not only we shouldn't add typescript but also that we should remove other languages. I'm sure a migration guide, an extra script or something with a major version would ease the pain. But we should definitely make the library smaller and easier to maintain.

**Comment by JerrySievert** [comment]
Going to close this. 

Language removal will only occur on a major version, likely when plv8u support is merged back in (slowly happening but moving forward), but any scripts or documentation around this would be welcome.

**Comment by egandro** [comment]
I have a working version :)

I precompile Typescript to JS and automaticually wrap it to SQL using EJS templates per function.

This is very sweet. There is also some Typings for the plv8 domain.

I have to recompile plv8 with external v8 debugger support. (Currently I am using a Docker image: clkao/postgres-plv8:9.6-2.0).

If the debugger support is enabled, typescript mappings will work out of the box via chrome debugger.

I still wish some node-ish enviornment with (automatic) installation of external packages. I also would love to have a plv8 driver for sequelize. That's the most annoying thing for the time now.

The postgres JSON is not automaticually wrapped to the Typescript interfaces - it works out of the box for strings and objects but not for bool, date and number - sequelizejs has some code for this - that can be easily used for plv8.

More work on this if we stick with postgres on this project.
