### ISSUE TITLE
fail to run make

### ISSUE THREAD

**Issue by gzliudan** [plv8/plv8#240]
I guess the reason is that google's web site is blocked in China.

make static
make -f Makefile.v8
make[1]: Entering directory `/root/plv8-2.1.0'
mkdir -p build
cd build; git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
Cloning into 'depot_tools'...
fatal: unable to access 'https://chromium.googlesource.com/chromium/tools/depot_tools.git/': Failed connect to chromium.googlesource.com:443; Connection timed out
make[1]: *** [build/depot_tools] Error 128
make[1]: Leaving directory `/root/plv8-2.1.0'
make: *** [static] Error 2

**Comment by JerrySievert** [comment]
plv8 doesn't control google's hosts, but v8 relies on them.  nothing we can do to help other than say, "try again"
