### ISSUE TITLE
Key order of returned json results from plv8.execute

### ISSUE THREAD

**Issue by a-mckinley** [plv8/plv8#242]
Hi,

I have a question about the key order of results returned by plv8.execute().  If I iterate over the keys of a row via Object.keys() I seem to get the a key order that matches the original select query.  Is this behaviour guaranteed by plv8.execute()?

**Comment by JerrySievert** [comment]
`Object.keys()` does not guarantee any order, but you should be getting an array of objects back from the query:

```
[local] jerry@test=# do $$ plv8.elog(NOTICE, JSON.stringify(plv8.execute("SELECT * FROM foo"))); $$ LANGUAGE plv8;
NOTICE:  00000: [{"bar":"123"},{"bar":"abc"}]
LOCATION:  plv8_Elog, plv8_func.cc:361
DO
Time: 0.815 ms
```
