### ISSUE TITLE
is it possible to spawn a child process with child_process within a stored proc ?

### ISSUE THREAD

**Issue by max-l** [plv8/plv8#243]
is it possible to spawn an external process from plv8 ? 

I tried calling this :
    require('child_process').child_process.execSync(cmd)

and require('child_process') is returning undefined...

**Comment by JerrySievert** [comment]
no, plv8 is a trusted extension, meaning you cannot shell out, nor open socket or file connections.

**Comment by nbering** [comment]
@max-l plv8 is not the same as NodeJS. They are both build on the same JavaScript runtime (Google's V8 enging), but `child_process` is a module provided by NodeJS.
