### ISSUE TITLE
Thoughts about adding a memoize utility function?

### ISSUE THREAD

**Issue by deinspanjer** [plv8/plv8#249]
I was wondering if others think it might be useful to add memoize to plv8.

Something simple like the one defined in lodash seems like it would be quite useful to me:
https://github.com/lodash/lodash/blob/4.17.4/lodash.js#L10554

The issue is around JS functions and data structures defined in plv8 functions which are expensive to create and get called many times in the context of a single session.
At the moment, unless I've missed something obvious, the only real choices are to either hide the data in the plv8 global object as a new member, or execute a dynamic create function that captures the data and then use plv8.find_function() on that.

**Comment by JerrySievert** [comment]
not going to happen, as this could be a major security hole on the database-side.  even though the memoization would only last through one session, a single session can mean changes of roles throughout the session, thus allowing leakage across roles and security contexts.

while something could be written to interface with the security model that postgres provides, there would need to be a lot of code written to essentially emulate it.

stashing that in the the global object could also open you up to leakage, you need to be aware of what you're putting in there, and what other roles could have access to it in the session.

see https://github.com/plv8/plv8/blob/master/plv8.cc#L1488 for a little more context of where to begin in the postgres security model.

**Comment by deinspanjer** [comment]
Thank you very much for the feedback.

**Comment by asah** [comment]
fyi hiding in the global plv8 object worked great for me... 5x speedup (end to end!) for a system using d3.js loaded through your require() implementation. https://github.com/JerrySievert/plv8-modules
