### ISSUE TITLE
plv8.execute( sql [, args] ) on windows returns error

### ISSUE THREAD

**Issue by zsheep** [plv8/plv8#250]
I'm not sure this is correct place to direct this too or it should be directed to 

http://www.postgresonline.com/journal/archives/379-PLV8-binaries-for-PostgreSQL-10-windows-both-32-bit-and-64-bit.html

With Postgresql 10 and Postgresql 10.1 EDB binaries,  64 bit windows 2012,  
`do $$
var sql = 'Select * from item  limit $1';
r = plv8.execute(sql, [ 10 ] );
return;
$$
language plv8`

Returns the following Error  
ERROR:  Error: there is no parameter $1
DETAIL:  undefined() LINE 3: r = plv8.execute(sql, [ 10 ] );
SQL state: XX000

doing it this way does not create an error
`do $$
var sql = 'Select * from item  limit 10';
r = plv8.execute(sql );
return;
$$
language plv8`

Also tried using plv8.prepare( sql, [, typenames] ) with PreparedPlan.execute( [args] )

it causes the same error.  

Thanks for your attention.

**Comment by JerrySievert** [comment]
what you're seeing is a postgres error from your query.  you cannot use a bind parameter for the `limit`.  this will not work on any version of postgres, under any operating system.

you can verify this for yourself by attempting to execute the same prepared statement from the environment of your choice.

**Comment by zsheep** [comment]
My fault bad example  i was trying to create a short example  should have 

been

do $$
var sql = 'Select * from item_id = $1';
r = plv8.execute(sql, [ 10 ] );
return 
$$
language plv8

**Comment by JerrySievert** [comment]
your second example isn't valid sql.

try adding a table name and a `where` clause, and I think that you will find that it works.

```
sensors=# do $$
var sql = 'Select * from metrics where sensor_id = $1';
r = plv8.execute(sql, [ 10 ] );
return
$$
language plv8;
DO
```

**Comment by zsheep** [comment]
[http://www.magwerks.com/filedrop/vendor/postgreql/snapshot.jpg](url)

**Comment by JerrySievert** [comment]
which version of plv8 are you using?

**Comment by zsheep** [comment]
its the binaries created by  Postgresql Journal
http://www.postgresonline.com/journal/archives/379-PLV8-binaries-for-PostgreSQL-10-windows-both-32-bit-and-64-bit.html

**Comment by zsheep** [comment]
which reads 1.4.10

**Comment by JerrySievert** [comment]
the 1.4 version is several years old, 2.1.0 is the current version.

**Comment by zsheep** [comment]
what are you saying??  i have to build the windows binaries???

**Comment by JerrySievert** [comment]
I'm saying that you're using an unsupported version, and that I can confirm that the query I sent you works under a modern version of plv8 (I'm not going to try to compile 1.4, as it is unsupported).

**Comment by zsheep** [comment]
Hello Sir

Trying to compile  plv8 with VS 2017  the current tool used to build PG 
10.1 on windows

I'm getting an error C2466  on line 1024   file plv8_func.cc

Handle<v8::Value> emptyargs[] = {};

this error boils down to difference between g++ and ms c++ compilers.

https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2466?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C2466)%26rd%3Dtrue

To make the error go away setting the array to 1 as below

Handle<v8::Value> emptyargs[1] = {};

I have no idea how the function call to V8 engine are going to react to 
array size of 1???

does the g++ compiler treat the empty arrays as nulls or empty pointers 
or makes them size 1??



FYI changing the compiler settings in VS 2017 to ignore empty arrays 
causes allot more errors

**Comment by JerrySievert** [comment]
that would be a difference between msvc and pretty much every other compiler out there (I don't develop with g++, I use clang++) - if you're using 2017, you should be able to use the clang compiler.

otherwise, it might be worth trying the branch referenced here: https://github.com/plv8/plv8/pull/239
