### ISSUE TITLE
variable case sesntive problem

### ISSUE THREAD

**Issue by hellower** [plv8/plv8#252]
--------------------------------------------------------------------------
test environtment
--------------------------------------------------------------------------
centos6 + postgresql 10.1 + plv8 2.1.0
select * From plv8_version();
sql> 2.1.0
--------------------------------------------------------------------------

**1) good result**
DROP FUNCTION plv8_test3(TEXT,TEXT);
CREATE OR REPLACE FUNCTION plv8_test3(a_sql text ,b text)
RETURNS text AS $$
  return a_sql+b;
$$ LANGUAGE plv8;

SELECT plv8_test3('x','y'); 

result
-- 
xy

**2) ERROR!!! - aSQL ???**
DROP FUNCTION plv8_test3(TEXT,TEXT);
CREATE OR REPLACE FUNCTION plv8_test3(aSQL text ,b text)
RETURNS text AS $$
  return aSQL+b;
$$ LANGUAGE plv8;

SELECT plv8_test3('x','y'); 

ERROR!!
-------------------

ERROR:  ReferenceError: aSQL is not defined
CONTEXT:  plv8_test3() LINE 2:   return aSQL+b;
********** Error **********

ERROR: ReferenceError: aSQL is not defined
SQL state: XX000
Context: plv8_test3() LINE 2:   return aSQL+b;

sorry for poor english.

**Comment by JerrySievert** [comment]
that is correct.  `plv8` uses the parameter names that postgres provides it.  you can see for yourself by executing a simple query:

```
[local] jerry@test=# select * from pg_proc where proname = 'plv8_test3';
┌─[ RECORD 1 ]────┬────────────────┐
│ proname         │ plv8_test3     │
│ pronamespace    │ 2200           │
│ proowner        │ 10             │
│ prolang         │ 16399          │
│ procost         │ 100            │
│ prorows         │ 0              │
│ provariadic     │ 0              │
│ protransform    │ -              │
│ proisagg        │ f              │
│ proiswindow     │ f              │
│ prosecdef       │ f              │
│ proleakproof    │ f              │
│ proisstrict     │ f              │
│ proretset       │ f              │
│ provolatile     │ v              │
│ proparallel     │ u              │
│ pronargs        │ 2              │
│ pronargdefaults │ 0              │
│ prorettype      │ 25             │
│ proargtypes     │ 25 25          │
│ proallargtypes  │ ¤              │
│ proargmodes     │ ¤              │
│ proargnames     │ {asql,b}       │
│ proargdefaults  │ ¤              │
│ protrftypes     │ ¤              │
│ prosrc          │               ↵│
│                 │ return aSQL+b;↵│
│                 │                │
│ probin          │ ¤              │
│ proconfig       │ ¤              │
│ proacl          │ ¤              │
└─────────────────┴────────────────┘
```

as you can see, `proargnames` is `{asql,b}`, which is set by postgres when the function is created.  Postgres itself is case-insensitive.

**Comment by hellower** [comment]
thanks!!
