### ISSUE TITLE
timestamp with time zone auto-converted to UTC? Bug or feature?

### ISSUE THREAD

**Issue by cschwaderer** [plv8/plv8#256]
I have noticed that times seems to be converted to UTC if I fetch them inside an SQL query which is wrapped in `plv8.execute`

Consider this test table with just one row with id 1 and `CURRENT_TIMESTAMP` as `imestamp with time zone`:

```
DROP TABLE IF EXISTS  plv8_time_test;
CREATE TABLE plv8_time_test (id integer, my_time timestamp with time zone);
INSERT INTO plv8_time_test (id,my_time) VALUES(1,CURRENT_TIMESTAMP);
```

Now running `SELECT my_time FROM plv8_time_test;` results in the expected output `2018-02-21 08:03:47.936697+01`.

However, if I do 

```
DO $$
 plv8.elog(INFO,JSON.stringify(plv8.execute('SELECT my_time FROM plv8_time_test;')[0].my_time));
$$ LANGUAGE plv8

```

I'll get `2018-02-21T07:03:47.936Z` - which is not what I want.
Is this a bug or a feature?

I'm using `PostgreSQL 9.6.1 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.3.1-14ubuntu2) 5.3.1 20160413, 64-bit` and plv8 Version 1.4.8.

**Comment by JerrySievert** [comment]
`psql` is adjusting the time from a `timestamp with time zone` in UTC to a local time zone for you when it knows the type, for your viewing pleasure.  when you do the execution with `plv8`, with a `DO` statement, `psql` does not know the type, and thus returns exactly what is sent to it, not adjusting if for you.

you can see the same behavior if you use a direct client:

```
> pg.connect('postgres://localhost/test', function (err, con) { con.query('select * from test', function () { console.log(arguments[1].rows); }); });
undefined
> [ anonymous { time: 2018-02-21T17:13:47.356Z } ]
```

as an aside, the version of `plv8` you are running is VERY old, and is compiled against `v8` version `3.14`, which is 5 years old.  if you can, I'd highly recommend updating to something a bit more current, such as `2.3.0`, which is compiled against `v8` `6.4.388.40`; v8 is quite a bit different/faster at this point, as well as having fixed a lot of bugs from the previous 5 years.

**Comment by JerrySievert** [comment]
just to help make sure you can see how `psql` is what is causing you to see what you're seeing:

```
[local] jerry@test=# CREATE FUNCTION plv8_test ( ) RETURNS TIMESTAMP WITH TIME ZONE AS $$
return plv8.execute('SELECT time FROM test')[0].time;
$$ language plv8;
CREATE FUNCTION
Time: 2.385 ms
[local] jerry@test=# select plv8_test();
┌────────────────────────────┐
│         plv8_test          │
├────────────────────────────┤
│ 2018-02-21 09:13:47.356-08 │
└────────────────────────────┘
(1 row)

Time: 2.066 ms
```

**Comment by cschwaderer** [comment]
Thank you so much for your detailed answer! I think I got the point. However, to 100% rule out that plv8 as the reason for my trouble here, let me give you a more realistic set-up. Sorry, more code, but please bear with me!

In real life, I'm using indeed Node.js and pg. And the problem is the same: Wrapping the `SELECT` inside plv8 will result in different time format. Probably, as you said, because pg will do some conversion here.

So, we create the test table as last time, but this time two functions: one vanilla SQL and one plv8. Both return just `my_time` from `plv8_time_test;`.
```

DROP TABLE IF EXISTS  plv8_time_test;
CREATE TABLE plv8_time_test (id integer, my_time timestamp with time zone);
INSERT INTO plv8_time_test (id,my_time) VALUES(1,CURRENT_TIMESTAMP);

CREATE OR REPLACE FUNCTION public.time_test_sql()
  RETURNS SETOF record AS
$BODY$
 SELECT my_time FROM plv8_time_test;
$BODY$ LANGUAGE sql STABLE;

CREATE OR REPLACE FUNCTION public.time_test_plv8()
  RETURNS json AS
$BODY$
 return plv8.execute("SELECT my_time FROM plv8_time_test")[0].my_time;
$BODY$ LANGUAGE plv8 STABLE;
```

Now, we set up a simple Node.js script which will access Postgres via the `pg` module. (In order to run it, we have to install `pg` - for example with a `package.json` like so:
```
{  "dependencies": {  "pg": "https://github.com/JedI-O/node-postgres.git#v6.1.5"  } }
```
and run `npm install` in that folder.)

Then, in the same directory, we have a small JavaScript file:

```
var pg = require('pg');

var config = {
  host: 'localhost',
  port: 5432,
  database: '<<<NAME OF DB>>>',
  user: '<<<USER NAME>>>',
  password: <<<PASSWORD>>>',
  max: 50,
  idleTimeoutMillis: 30000
};

var clientPool = new pg.Pool(config);

clientPool.on('error', function (err, client) {
  console.log('PostgreSQL client error: ' + JSON.stringify(err),'error','normal');
});

clientPool.connect(function(connectClientError, client, done) {
   
    client.query('SELECT time_test_sql();', [], function(queryError, result) {
          if(queryError) {
              console.log("ERROR!");
              console.log(queryError);
              process.exit(1);
          }
          else {
            console.log("time_test_sql: ");
            console.log(result.rows[0]);
            
            client.query('SELECT time_test_plv8();', [], function(queryError, result) {
                done();
                if(queryError) {
                    console.log("ERROR!");
                    console.log(queryError);
                    process.exit(1);
                }
                else {
                    console.log("time_test_plv8: ");
                    console.log(result.rows[0]);
                    process.exit(0);
                }
             });
            
          }
        });
});
```
After having connected to Postgres, it will just execute both functions. The results I get are:
```
time_test_sql: 
anonymous { time_test_sql: '("2018-02-22 **07:24:19.541459+01**")' }
time_test_plv8: 
anonymous { time_test_plv8: '2018-02-22T**06:24:19.541Z'** }
```

Updating to plv8 2.x is a good point. I've put that on my task list.

**Comment by JerrySievert** [comment]
you do realize two things, right?

1) `pg` does conversion between `sql` and `javascript` types

2) you are returning two DIFFERENT types between the `plsql` stored procedure and `plv8` stored procedure, so `pg` is treating them differently (see https://github.com/brianc/node-pg-types) - the JSONOID is 114, the RECORDARRAYOID (setof record) is 2287, which breaks down into an array of 2249.

apples to oranges, I would expect that any flawed test like this would return different values.

while `plv8` does do limited type conversion, in order to convert from postgres data types to javascript datatypes, and back, it does it in an extremely consistent way that does not modify the data type in between.

you can audit for yourself:

* plv8.execute: https://github.com/plv8/plv8/blob/master/plv8_func.cc#L452-L456
* from postgres to javascript:https://github.com/plv8/plv8/blob/master/plv8_type.cc#L451
* from javascript to postgres: https://github.com/plv8/plv8/blob/master/plv8_type.cc#L229
