### ISSUE TITLE
Date Casting and Timestamp Precision

### ISSUE THREAD

**Issue by bs85** [plv8/plv8#259]
I ran into this issue today, where I have columns that are `TIMESTAMP DEFAULT CURRENT_TIMESTAMP`, which generate timestamps with 6 digits precision by default.

Running those through plv8 truncates them to 3 digits, meaning any BEFORE INSERT/UPDATE plv8 trigger with a return value will truncate those timestamps.

I personally don't need the precision, my fix was to convert my columns to TIMESTAMP(3). Would an option to treat timestamps as string be considered though?

**Comment by JerrySievert** [comment]
hm. as you know, javascript doesn't have the precision up to 6 digits, so I can't see about some higher precision conversion (which would have been my first choice).

unfortunately, changing the functionality of plv8 itself would be a major change for all users, so I'm not really willing to do that, but the good news is that you can make the change using casting.

I'm not sure if this is the solution you are looking for, but it should work:

```
CREATE FUNCTION some_date_in_2018 (in_date VARCHAR) RETURNS TIMESTAMP AS $$
  var parsed = Date.parse(in_date);
  var d = new Date(parsed);

  if (d.getFullYear() === 2018) {
    return in_date;
  } else {
    return null;
  }
$$ LANGUAGE plv8;
```

```
psql> SELECT some_date_in_2018(NOW()::VARCHAR);
┌────────────────────────────┐
│     some_date_in_2018      │
├────────────────────────────┤
│ 2018-03-15 13:04:42.564534 │
└────────────────────────────┘
(1 row)
```

and can even try:

```
psql> SELECT some_date_in_2018((NOW() - interval '1 year')::VARCHAR);
```

which should return `NULL`.

would that work for you?

**Comment by JerrySievert** [comment]
this, of course, would be a little more complicated with a trigger, but a small wrapper around the trigger should work fairly well, as long as it's very lightweight.

**Comment by bs85** [comment]
I agree that the current behavior is probably best in general, I was just curious if you had come across the problem and had ideas about possible ways to handle it.

Thanks for the ideas, and for now I'll stick to TIMESTAMP(3) to make sure the truncating doesn't create unnecessary noise!

**Comment by JerrySievert** [comment]
well, `VARCHAR` would work, if all else fails.  just have to use casting ... maybe something for the future.

I do wonder if some of the microtime stuff might work - I can do some investigation, since we're using v8 and won't have to go cross-platform.

I'm going to go ahead and re-open this, just as an investigation ticket.
