### ISSUE TITLE
need help with new postgres10 + plv8 v2.3.0 build

### ISSUE THREAD

**Issue by pyramation** [plv8/plv8#260]
Hey, super close to getting this to work! As a last resort, I'm posting here to see if I can get some help :)

As you can see, I'm running into an error that's missing some libraries
https://travis-ci.org/pyramation/postgres-plv8/builds/354860826#L2272

specifically, the error is
```sh
/usr/bin/ld: cannot find -lc++
```

in the `Makefile` for the linux option, you'll see `-lc++` is added here: https://github.com/plv8/plv8/blob/377216eea27bc1e6ba7d185e82ae20f12c61865b/Makefile#L65

Let me know if you have ideas of which libs I need to install, thanks in advance for any help!

**Comment by JerrySievert** [comment]
Simple. You’re missing the library it’s trying to link to - install its package. 

I think it’s libc++-dev but double check the docs under building.  I’m on my phone responding or I’d just provide a link.

**Comment by pyramation** [comment]
awesome! Thank you! Finally got it to work. One thing which was weird though, is that I had to add locales to get the docker to work (although it's more like a docker issue)

```
RUN echo en_US.UTF-8 UTF-8 > /etc/locale.gen
RUN echo LANG=en_US.UTF-8 > /etc/locale.conf && locale-gen
```

I'll be publishing it soon! Currently running tests using postgres10 and plv8 v2.3.0 🤘🏻

**Comment by pyramation** [comment]
https://hub.docker.com/r/pyramation/postgres-plv8/

**Comment by bendiy** [comment]
`sudo apt-get install libc++-dev`
