### ISSUE TITLE
Discussion forum / mailing list?

### ISSUE THREAD

**Issue by nileshtrivedi** [plv8/plv8#261]
[Off-topic]

Neither the GItHub repo, nor the PGXN page points to any page where discussions - which don't qualify as feature requests or bug reports - can be had. Do you have a mailing list? Gitter room? Would be a good idea to mention it on the README page.

**Comment by JerrySievert** [comment]
there's not much discussion on it:

https://groups.google.com/forum/#!forum/plv8js

**Comment by nileshtrivedi** [comment]
Perhaps because it's not easy to find. :-)

Here's the pull request in case you'd like to include this link in the README: https://github.com/plv8/plv8/pull/262
