### ISSUE TITLE
urlparse not found

### ISSUE THREAD

**Issue by jamesvanleuven** [plv8/plv8#266]
OSX High Sierra
PostgreSQL 10.3
Python3/Python2
liburl3

are what are installed... this is a problem.
PS: the same issues are occurring on Ubuntu 17.10 and CentOS 7

```
$ make install
mkdir -p build
cd build; git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
Cloning into 'depot_tools'...
remote: Sending approximately 18.53 MiB ...
remote: Counting objects: 2, done
remote: Finding sources: 100% (2/2)
remote: Total 25630 (delta 18638), reused 25629 (delta 18638)
Receiving objects: 100% (25630/25630), 18.53 MiB | 10.68 MiB/s, done.
Resolving deltas: 100% (18638/18638), done.
cd build; fetch v8; cd v8; git checkout 6.4.388.40; gclient sync ; tools/dev/v8gen.py x64.release -- is_component_build=false v8_static_library=true v8_use_snapshot=true v8_use_external_startup_data=false v8_enable_i18n_support=false
  File "/Users/james/plv8-2.3.1/build/depot_tools/fetch.py", line 65
    print 'Running: %s' % (' '.join(pipes.quote(x) for x in cmd))
                      ^
SyntaxError: invalid syntax
/bin/sh: line 0: cd: v8: No such file or directory
fatal: Not a git repository (or any of the parent directories): .git
Bootstrapping cipd client for mac-amd64 from https://chrome-infra-packages.appspot.com/client?platform=mac-amd64&version=git_revision:ae28364c740acff97ae118adcb2808b6cb5129c5...
Traceback (most recent call last):
  File "/Users/james/plv8-2.3.1/build/depot_tools/gclient.py", line 99, in <module>
    import urlparse
ModuleNotFoundError: No module named 'urlparse'
/bin/sh: tools/dev/v8gen.py: No such file or directory
make: *** [build/v8] Error 127
```

**Comment by JerrySievert** [comment]
`python` needs to be python 2, please verify by running `python --version` that you are running python 2 by default.

if you are, you may still need perquisites for the v8 build:

```
$ sudo easy_install urlparse
```

**Comment by jamesvanleuven** [comment]
I'm running `python 3.6.4` by default
we use a lot of Anaconda, so...

**Comment by jamesvanleuven** [comment]
```
$ sudo easy_install urlparse
Password:
Searching for urlparse
Reading https://pypi.python.org/simple/urlparse/
Couldn't find index page for 'urlparse' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or working download links found for urlparse
error: Could not find suitable distribution for Requirement.parse('urlparse')

```

**Comment by jamesvanleuven** [comment]
```
$ python --version
Python 3.6.4
$ which python
/usr/local/bin/python
$ which python2
/usr/local/bin/python2
$ which python3
/usr/local/bin/python3

```

**Comment by jamesvanleuven** [comment]
It's not working with the `Python2` switch either
```
$ sudo python2 -m easy_install urlparse
Searching for urlparse
Reading https://pypi.python.org/simple/urlparse/
Couldn't find index page for 'urlparse' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or working download links found for urlparse
error: Could not find suitable distribution for Requirement.parse('urlparse')
```

**Comment by JerrySievert** [comment]
that is correct, and it will not work with `python2` - all of google's build tools (and there are a lot of them) require `python` to be python 2 - it's a prerequisite for building v8 that cannot be worked around as far as I know.

you need to have the installed `python` version be 2, otherwise you will not be able to build.

you may be able to change this by altering your path to include the system python `/usr/bin/python` to be first in your path - likely you have `/usr/local/bin` in your path before `/usr/bin`.

**Comment by jamesvanleuven** [comment]
yes - i was reading on that... I'll take a look at it, and try that approach and let you know... it's a little disconcerting though - not anyone's "fault" persay, but you know... python2.7 has been around for almost a decade - one would think that in the internet of things we'd move past it, now that 3.6 is a legit build

**Comment by JerrySievert** [comment]
google has control of v8 and its build process.  it has changed in the past (they've changed the build system over time, requiring any projects using v8 to be required to change their build), but until they move all of their build tools to python 3, there's nothing we can do.

if you pay enough attention, you'll see that they'll also be downloading all of their own compiler suite, not using what's local on your machine.

**Comment by JerrySievert** [comment]
here is the google issue you can comment on: https://bugs.chromium.org/p/gyp/issues/detail?id=36

fyi, the whole node ecosystem requires python 2 for any building of native extensions - they're in the same boat.

**Comment by jamesvanleuven** [comment]
yes sorry I didn't respond. I repaired the issue re python versions, and everything is peachy once more
