### ISSUE TITLE
why [plv8.execution_timeout] warning?

### ISSUE THREAD

**Issue by hellower** [plv8/plv8#287]
???
WARNING: unrecognized configuration parameter "plv8.execution_timeout"

**I. my compile otption**
$ make EXECUTION_TIMEOUT=1

**II. environment**

$ uname -a
Linux test 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[postgres@test:/opt/PostgreSQL/10/data]
$ cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 
[postgres@test:/opt/PostgreSQL/10/data]

[postgres@test:/opt/PostgreSQL/10/data]
$ grep plv8.execution_timeout postgresql.conf 
plv8.execution_timeout=300   # 5 minutes
[postgres@test:/opt/PostgreSQL/10/data]
$ 

SQL> \dx

                                          List of installed extensions
+-----------+---------+------------+----------------------------------------------------------------------------+
|   Name    | Version |   Schema   |                                Description                                 |
+-----------+---------+------------+----------------------------------------------------------------------------+
| adminpack | 1.0     | pg_catalog | administrative functions for PostgreSQL                                    |
| plv8      | 2.3.4   | pg_catalog | PL/JavaScript (v8) trusted procedural language                             |
+-----------+---------+------------+----------------------------------------------------------------------------+
(6 rows)

tarantula@[local]:5432:tarantula(23:47:07)
SQL> 

test@[local]:5432:test(23:44:24)
SQL> select * from tnt_getnamespace('mypg');   ---  plv8 function
**_WARNING:  unrecognized configuration parameter "plv8.execution_timeout"   ?????????????_**
+-----------+--------------------------------------------------------------------------------------------------------------+
| namespace |                                                     jval                                                     |
+-----------+--------------------------------------------------------------------------------------------------------------+
| mypg      | {"dt":"2018-04-29T14:48:47.790Z","dbkind":"pgs","url":"http://api.test.kr:8080/api/mypg","vernum":10.3} |
+-----------+--------------------------------------------------------------------------------------------------------------+
(1 row)

Time: 154.346 ms
test@[local]:5432:test(23:44:28)
SQL> show  plv8.execution_timeout
test-# ;
+------------------------+
| plv8.execution_timeout |
+------------------------+
| 300                    |
+------------------------+
(1 row)

Time: 0.305 ms
test@[local]:5432:test(23:44:59)
SQL> select version();
+---------------------------------------------------------------------------------------------------------+
|                                                 version                                                 |
+---------------------------------------------------------------------------------------------------------+
| PostgreSQL 10.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18), 64-bit |
+---------------------------------------------------------------------------------------------------------+
(1 row)

Time: 0.510 ms
test@[local]:5432:test(23:45:16)
SQL>

**Comment by JerrySievert** [comment]
can you verify that you restarted postgres after installing the version of plv8 compiled with execution timeout enabled?

```
[local] jerry@test=# do $$ while(1); $$ language plv8;
ERROR:  XX000: execution timeout exceeded
LOCATION:  rethrow, plv8.cc:2012
Time: 10091.406 ms (00:10.091)
[local] jerry@test=# show plv8.execution_timeout;
┌────────────────────────┐
│ plv8.execution_timeout │
├────────────────────────┤
│ 10                     │
└────────────────────────┘
(1 row)

Time: 0.525 ms
```

```
$ grep -i execution /usr/local/var/log/postgres.log
1641676:2018-06-15 08:33:05.071 PDT [41535] ERROR:  execution timeout exceeded
1641730:2018-06-15 08:44:53.744 PDT [42351] ERROR:  execution timeout exceeded
```

**Comment by hellower** [comment]
pg_ctl stop -w -mf
pg_ctl start -w

after restart 
----------------------

[postgres@test:/opt/PostgreSQL/10/data]
$ psql -U tarantula -d tarantula

Current Host Server Date Time : Sat Jun 16 00:52:00 KST 2018 

Administrative queries:

                        :settings       -- Server Settings
                        :conninfo       -- Server connections
                        :activity       -- Server activity
                        :locks          -- Lock info
                        :waits          -- Waiting queires
                        :dbsize         -- Database Size
                        :tablesize      -- Tables Size
                        :uselesscol     -- Useless columns
                        :uptime         -- Server uptime
                        :menu           -- Help Menu
                        \h              -- Help with SQL commands
                        \?              -- Help with psql commands

Development queries:

                        :sp             -- Current Search Path
                        :clear          -- Clear screen
                        :ll             -- List

psql.bin (10.3)
Type "help" for help.

tarantula@[local]:5432:tarantula(00:52:00)
SQL> show plv8.execution_timeout
;
+------------------------+
| plv8.execution_timeout |
+------------------------+
| 10                     |
+------------------------+
(1 row)

Time: 0.568 ms
tarantula@[local]:5432:tarantula(00:52:05)
SQL> do $$ while(1); $$ language plv8;
WARNING:  unrecognized configuration parameter "plv8.execution_timeout"

...... hang .......

**Comment by JerrySievert** [comment]
are you sure that the version of plv8 that is compiled with execution timeout is the version installed?

you can verify by running `strings` against the installed version:

```
$ strings plv8-2.3.4.so | grep -i "execution timeout"
V8 execution timeout.
The default value is 300 seconds.  This allows you to override the default execution timeout.
execution timeout exceeded
```

**Comment by hellower** [comment]
[postgres@150-95-134-42:/opt/PostgreSQL/10/lib/postgresql]$ ls  plv8*
plv8-2.3.4.so
plv8-2.3.3.so
...

two file exists !! my fault!!

thanks for your support!!
