### ISSUE TITLE
version 2.3.5 compile error (2.3.4 good)

### ISSUE THREAD

**Issue by hellower** [plv8/plv8#288]
[postgres@150-95-134-42:/usr/local/src/plv8-2.3.5]
$ cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 
[postgres@150-95-134-42:/usr/local/src/plv8-2.3.5]
$ psql

psql.bin (10.3)
Type "help" for help.

postgres@[local]:5432:postgres(01:11:12)
SQL> select version();
+---------------------------------------------------------------------------------------------------------+
|                                                 version                                                 |
+---------------------------------------------------------------------------------------------------------+
| PostgreSQL 10.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18), 64-bit |
+---------------------------------------------------------------------------------------------------------+
(1 row)

Time: 87.979 ms
postgres@[local]:5432:postgres(01:11:15)

[postgres@150-95-134-42:/usr/local/src/plv8-2.3.5]
$ make EXECUTION_TIMEOUT=1
...........
g++ -Wall -O2 -std=c++11 -fno-rtti  -DEXECUTION_TIMEOUT -Ibuild/v8/include -Ibuild/v8 -std=c++11 -I. -I./ -I/opt/PostgreSQL/10/include/postgresql/server -I/opt/PostgreSQL/10/include/postgresql/internal -I/opt/local/Current/include -D_GNU_SOURCE  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include -fPIC -c -o plv8.o plv8.cc
plv8.cc:193:11: error: ‘Protection’ has not been declared
           Protection protection) override {}
           ^
plv8.cc:149:8: error: ‘void* Plv8ArrayBufferAllocator::Reserve(size_t)’ marked override, but does not override
  void* Reserve(size_t length) override {
        ^
plv8.cc:188:6: error: ‘void Plv8ArrayBufferAllocator::Free(void*, size_t, v8::ArrayBuffer::Allocator::AllocationMode)’ marked override, but does not override
 void Free(void *data, size_t size, v8::ArrayBuffer::Allocator::AllocationMode) override {
      ^
plv8.cc:192:7: error: ‘void Plv8ArrayBufferAllocator::SetProtection(void*, size_t, int)’ marked override, but does not override
  void SetProtection(void* data, size_t length,
       ^
plv8.cc: In function ‘void* Breakout(void*)’:
plv8.cc:535:2: error: ‘TerminateExecution’ is not a member of ‘v8::V8’
  v8::V8::TerminateExecution(plv8_isolate);
  ^
plv8.cc: In function ‘void signal_handler(int)’:
plv8.cc:552:2: error: ‘TerminateExecution’ is not a member of ‘v8::V8’
  v8::V8::TerminateExecution(plv8_isolate);
  ^
plv8.cc: In function ‘v8::Local<v8::Value> DoCall(v8::Handle<v8::Function>, v8::Handle<v8::Object>, int, v8::Handle<v8::Value>*)’:
plv8.cc:564:12: error: no matching function for call to ‘v8::TryCatch::TryCatch()’
  TryCatch  try_catch;
            ^
plv8.cc:564:12: note: candidate is:
In file included from plv8.h:12:0,
                 from plv8.cc:8:
build/v8/include/v8.h:8679:12: note: v8::TryCatch::TryCatch(v8::Isolate*)
   explicit TryCatch(Isolate* isolate);
            ^
build/v8/include/v8.h:8679:12: note:   candidate expects 1 argument, 0 provided
plv8.cc: In function ‘Datum CallTrigger(FunctionCallInfo, plv8_exec_env*)’:
plv8.cc:882:13: error: no matching function for call to ‘v8::TryCatch::TryCatch()’
  TryCatch   try_catch;
             ^
plv8.cc:882:13: note: candidate is:
In file included from plv8.h:12:0,
                 from plv8.cc:8:
build/v8/include/v8.h:8679:12: note: v8::TryCatch::TryCatch(v8::Isolate*)
   explicit TryCatch(Isolate* isolate);
            ^
build/v8/include/v8.h:8679:12: note:   candidate expects 1 argument, 0 provided
plv8.cc: In function ‘char* CompileDialect(const char*, Dialect)’:
plv8.cc:1225:12: error: no matching function for call to ‘v8::TryCatch::TryCatch()’
  TryCatch  try_catch;
            ^
plv8.cc:1225:12: note: candidate is:
In file included from plv8.h:12:0,
                 from plv8.cc:8:
build/v8/include/v8.h:8679:12: note: v8::TryCatch::TryCatch(v8::Isolate*)
   explicit TryCatch(Isolate* isolate);
            ^
build/v8/include/v8.h:8679:12: note:   candidate expects 1 argument, 0 provided
plv8.cc: In function ‘v8::Local<v8::Function> CompileFunction(v8::Persistent<v8::Context>&, const char*, int, const char**, const char*, bool, bool, Dialect)’:
plv8.cc:1399:12: error: no matching function for call to ‘v8::TryCatch::TryCatch()’
  TryCatch  try_catch;
            ^
plv8.cc:1399:12: note: candidate is:
In file included from plv8.h:12:0,
                 from plv8.cc:8:
build/v8/include/v8.h:8679:12: note: v8::TryCatch::TryCatch(v8::Isolate*)
   explicit TryCatch(Isolate* isolate);
            ^
build/v8/include/v8.h:8679:12: note:   candidate expects 1 argument, 0 provided
plv8.cc: In function ‘v8::Local<v8::Function> find_js_function(Oid)’:
plv8.cc:1458:14: error: no matching function for call to ‘v8::TryCatch::TryCatch()’
   TryCatch   try_catch;
              ^
plv8.cc:1458:14: note: candidate is:
In file included from plv8.h:12:0,
                 from plv8.cc:8:
build/v8/include/v8.h:8679:12: note: v8::TryCatch::TryCatch(v8::Isolate*)
   explicit TryCatch(Isolate* isolate);
            ^
build/v8/include/v8.h:8679:12: note:   candidate expects 1 argument, 0 provided
plv8.cc: In function ‘void GetGlobalContext(v8::Persistent<v8::Context>&)’:
plv8.cc:1587:15: error: no matching function for call to ‘v8::TryCatch::TryCatch()’
    TryCatch   try_catch;
               ^
plv8.cc:1587:15: note: candidate is:
In file included from plv8.h:12:0,
                 from plv8.cc:8:
build/v8/include/v8.h:8679:12: note: v8::TryCatch::TryCatch(v8::Isolate*)
   explicit TryCatch(Isolate* isolate);
            ^
build/v8/include/v8.h:8679:12: note:   candidate expects 1 argument, 0 provided
plv8.cc: In function ‘v8::Local<v8::ObjectTemplate> GetGlobalObjectTemplate()’:
plv8.cc:1666:53: error: no matching function for call to ‘v8::ObjectTemplate::New()’
   Local<ObjectTemplate> templ = ObjectTemplate::New();
                                                     ^
plv8.cc:1666:53: note: candidates are:
In file included from plv8.h:12:0,
                 from plv8.cc:8:
build/v8/include/v8.h:5963:32: note: static v8::Local<v8::ObjectTemplate> v8::ObjectTemplate::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<ObjectTemplate> New(
                                ^
build/v8/include/v8.h:5963:32: note:   candidate expects 2 arguments, 0 provided
build/v8/include/v8.h:6172:32: note: static v8::Local<v8::ObjectTemplate> v8::ObjectTemplate::New(v8::internal::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<ObjectTemplate> New(internal::Isolate* isolate,
                                ^
build/v8/include/v8.h:6172:32: note:   candidate expects 2 arguments, 0 provided
plv8.cc:1681:53: error: no matching function for call to ‘v8::ObjectTemplate::New()’
   Handle<ObjectTemplate> plv8 = ObjectTemplate::New();
                                                     ^
plv8.cc:1681:53: note: candidates are:
In file included from plv8.h:12:0,
                 from plv8.cc:8:
build/v8/include/v8.h:5963:32: note: static v8::Local<v8::ObjectTemplate> v8::ObjectTemplate::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<ObjectTemplate> New(
                                ^
build/v8/include/v8.h:5963:32: note:   candidate expects 2 arguments, 0 provided
build/v8/include/v8.h:6172:32: note: static v8::Local<v8::ObjectTemplate> v8::ObjectTemplate::New(v8::internal::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<ObjectTemplate> New(internal::Isolate* isolate,
                                ^
build/v8/include/v8.h:6172:32: note:   candidate expects 2 arguments, 0 provided
plv8.cc: In member function ‘Datum Converter::ToDatum(v8::Handle<v8::Value>, Tuplestorestate*)’:
plv8.cc:1813:12: error: no matching function for call to ‘v8::TryCatch::TryCatch()’
  TryCatch  try_catch;
            ^
plv8.cc:1813:12: note: candidate is:
In file included from plv8.h:12:0,
                 from plv8.cc:8:
build/v8/include/v8.h:8679:12: note: v8::TryCatch::TryCatch(v8::Isolate*)
   explicit TryCatch(Isolate* isolate);
            ^
build/v8/include/v8.h:8679:12: note:   candidate expects 1 argument, 0 provided
make: *** [plv8.o] Error 1
[postgres@150-95-134-42:/usr/local/src/plv8-2.3.5]

**Comment by JerrySievert** [comment]
it looks like you're compiling against the wrong version of `v8`.

can you do 2 things?

1. verify that there are no ubuntu v8 packages installed
2. verify that `build/v8` has the correct version of `v8` checked out, a `git status` in that directory should show `HEAD detached at 6.4.388.40`

**Comment by hellower** [comment]
[postgres@150-95-134-42:/usr/local/src/plv8-2.3.5]
$ cd build/v8
[postgres@150-95-134-42:/usr/local/src/plv8-2.3.5/build/v8]
$ git status
# HEAD detached at origin/master
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   tools/link_clicker.extension/icon.png
#       modified:   tools/turbolizer/hide-selected.png
#       modified:   tools/turbolizer/hide-unselected.png
#       modified:   tools/turbolizer/layout-icon.png
#       modified:   tools/turbolizer/left-arrow.png
#       modified:   tools/turbolizer/live.png
#       modified:   tools/turbolizer/right-arrow.png
#       modified:   tools/turbolizer/search.png
#       modified:   tools/turbolizer/search2.png
#       modified:   tools/turbolizer/turbolizer.png
#       modified:   tools/turbolizer/types.png
#       modified:   tools/turbolizer/upload-icon.png
#
no changes added to commit (use "git add" and/or "git commit -a")
[postgres@150-95-134-42:/usr/local/src/plv8-2.3.5/build/v8]
$ rpm -qa|grep plv8
[postgres@150-95-134-42:/usr/local/src/plv8-2.3.5/build/v8]
$

**Comment by JerrySievert** [comment]
yeah, that doesn't look like `v8` is at the correct version if it's on `origin/master`.  `v8`'s api changes radically between versions, which is one of the reasons `plv8` is pegged to a specific version (as is node.js).

did `v8` download and configure itself during the initial `make`, or did you use something that already existed?  it looks like the former did not occur.

**Comment by hellower** [comment]
I'm retrying  it like below..

[root@150-95-134-42:/root]
# rpm -qa|grep v8
[root@150-95-134-42:/root]
# su - postgres
[postgres@150-95-134-42:/opt/PostgreSQL/src]
$ wget https://github.com/plv8/plv8/archive/v2.3.5.tar.gz
--2018-06-16 01:25:19--  https://github.com/plv8/plv8/archive/v2.3.5.tar.gz
Resolving github.com (github.com)... 192.30.255.113, 192.30.255.112
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/plv8/plv8/tar.gz/v2.3.5 [following]
--2018-06-16 01:25:19--  https://codeload.github.com/plv8/plv8/tar.gz/v2.3.5
Resolving codeload.github.com (codeload.github.com)... 192.30.255.121, 192.30.255.120
Connecting to codeload.github.com (codeload.github.com)|192.30.255.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘v2.3.5.tar.gz’

    [         <=>                                                                                                                                                                                                           ] 9,298,535   4.35MB/s   in 2.0s   

2018-06-16 01:25:22 (4.35 MB/s) - ‘v2.3.5.tar.gz’ saved [9298535]

[postgres@150-95-134-42:/opt/PostgreSQL/src]
$ ls
v2.3.5.tar.gz
[postgres@150-95-134-42:/opt/PostgreSQL/src]
$ tar xvfz  v2.3.5.tar.gz 


[postgres@150-95-134-42:/opt/PostgreSQL/src/plv8-2.3.5]
$ pwd
/opt/PostgreSQL/src/plv8-2.3.5
[postgres@150-95-134-42:/opt/PostgreSQL/src/plv8-2.3.5]
$ make EXECUTION_TIMEOUT=1 -j8
.................
compiling now..

I'll report again when error occurred!

**Comment by JerrySievert** [comment]
can you paste the first 10 or so lines of the `make`?

**Comment by hellower** [comment]
[postgres@150-95-134-42:/opt/PostgreSQL/src/plv8-2.3.5]
$  make EXECUTION_TIMEOUT=1 -j8
mkdir -p build
echo "extern const unsigned char coffee_script_binary_data[] = {" >coffee-script.cc
cd build; git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
(od -txC -v coffee-script.js | \
sed -e "s/^[0-9]*//" -e s"/ \([0-9a-f][0-9a-f]\)/0x\1,/g" -e"\$d" ) >>coffee-script.cc
Cloning into 'depot_tools'...
echo "extern const unsigned char livescript_binary_data[] = {" >livescript.cc
(od -txC -v livescript.js | \
sed -e "s/^[0-9]*//" -e s"/ \([0-9a-f][0-9a-f]\)/0x\1,/g" -e"\$d" ) >>livescript.cc
mkdir -p upgrade
./generate_upgrade.sh 2.3.4
sed -e 's/@PLV8_VERSION@/2.3.4/g' plv8.control.common | g++ -E -P -DLANG_plv8 - > plv8.control
sed -e 's/@LANG_NAME@/plv8/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.3.4/g' | g++ -E -P -I. -I./ -I/opt/PostgreSQL/10/include/postgresql/server -I/opt/PostgreSQL/10/include/postgresql/internal -I/opt/local/Current/include -D_GNU_SOURCE  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include -DLANG_plv8 - > plv8--2.3.4.sql
sed -e 's/@PLV8_VERSION@/2.3.4/g' plv8.control.common | g++ -E -P -DLANG_plcoffee - > plcoffee.control
sed -e 's/@LANG_NAME@/plcoffee/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.3.4/g' | g++ -E -P -I. -I./ -I/opt/PostgreSQL/10/include/postgresql/server -I/opt/PostgreSQL/10/include/postgresql/internal -I/opt/local/Current/include -D_GNU_SOURCE  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include -DLANG_plcoffee - > plcoffee--2.3.4.sql
sed -e 's/@PLV8_VERSION@/2.3.4/g' plv8.control.common | g++ -E -P -DLANG_plls - > plls.control
sed -e 's/@LANG_NAME@/plls/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.3.4/g' | g++ -E -P -I. -I./ -I/opt/PostgreSQL/10/include/postgresql/server -I/opt/PostgreSQL/10/include/postgresql/internal -I/opt/local/Current/include -D_GNU_SOURCE  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include -DLANG_plls - > plls--2.3.4.sql
echo "0x00};" >>coffee-script.cc
echo "0x00};" >>livescript.cc
remote: Sending approximately 19.46 MiB ...
remote: Total 26616 (delta 19228), reused 26616 (delta 19228)
Receiving objects: 100% (26616/26616), 19.44 MiB | 16.49 MiB/s, done.
Resolving deltas: 100% (19228/19228), done.
cd build; fetch v8; cd v8; git checkout 6.4.388.40; gclient sync ; tools/dev/v8gen.py x64.release -- is_component_build=false v8_static_library=true v8_use_snapshot=true v8_use_external_startup_data=false v8_enable_i18n_support=false
Running: gclient root
..

**Comment by hellower** [comment]
[postgres@orascope:/opt/PostgreSQL/src/plv8-2.3.5]
$ make EXECUTION_TIMEOUT=1 -j8
mkdir -p build
cd build; git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
echo "extern const unsigned char coffee_script_binary_data[] = {" >coffee-script.cc
(od -txC -v coffee-script.js | \
sed -e "s/^[0-9]*//" -e s"/ \([0-9a-f][0-9a-f]\)/0x\1,/g" -e"\$d" ) >>coffee-script.cc
echo "extern const unsigned char livescript_binary_data[] = {" >livescript.cc
(od -txC -v livescript.js | \
sed -e "s/^[0-9]*//" -e s"/ \([0-9a-f][0-9a-f]\)/0x\1,/g" -e"\$d" ) >>livescript.cc
mkdir -p upgrade
Cloning into 'depot_tools'...
./generate_upgrade.sh 2.3.4
sed -e 's/@PLV8_VERSION@/2.3.4/g' plv8.control.common | g++ -E -P -DLANG_plv8 - > plv8.control
sed -e 's/@LANG_NAME@/plv8/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.3.4/g' | g++ -E -P -I. -I./ -I/opt/PostgreSQL/10/include/postgresql/server -I/opt/PostgreSQL/10/include/postgresql/internal -I/opt/local/Current/include -D_GNU_SOURCE  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include -DLANG_plv8 - > plv8--2.3.4.sql
sed -e 's/@PLV8_VERSION@/2.3.4/g' plv8.control.common | g++ -E -P -DLANG_plcoffee - > plcoffee.control
sed -e 's/@LANG_NAME@/plcoffee/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.3.4/g' | g++ -E -P -I. -I./ -I/opt/PostgreSQL/10/include/postgresql/server -I/opt/PostgreSQL/10/include/postgresql/internal -I/opt/local/Current/include -D_GNU_SOURCE  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include -DLANG_plcoffee - > plcoffee--2.3.4.sql
sed -e 's/@PLV8_VERSION@/2.3.4/g' plv8.control.common | g++ -E -P -DLANG_plls - > plls.control
sed -e 's/@LANG_NAME@/plls/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.3.4/g' | g++ -E -P -I. -I./ -I/opt/PostgreSQL/10/include/postgresql/server -I/opt/PostgreSQL/10/include/postgresql/internal -I/opt/local/Current/include -D_GNU_SOURCE  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include -DLANG_plls - > plls--2.3.4.sql
echo "0x00};" >>coffee-script.cc
echo "0x00};" >>livescript.cc
remote: Sending approximately 19.46 MiB ...
remote: Total 26616 (delta 19228), reused 26616 (delta 19228)
Receiving objects: 100% (26616/26616), 19.44 MiB | 16.04 MiB/s, done.
Resolving deltas: 100% (19228/19228), done.
cd build; fetch v8; cd v8; git checkout 6.4.388.40; gclient sync ; tools/dev/v8gen.py x64.release -- is_component_build=false v8_static_library=true v8_use_snapshot=true v8_use_external_startup_data=false v8_enable_i18n_support=false
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/v8/v8.git /opt/PostgreSQL/src/plv8-2.3.5/build/_gclient_v8_DpacZn' in '/opt/PostgreSQL/src/plv8-2.3.5/build'
Cloning into '/opt/PostgreSQL/src/plv8-2.3.5/build/_gclient_v8_DpacZn'...
remote: Sending approximately 291.83 MiB ...
remote: Counting objects: 7825, done
remote: Finding sources: 100% (165/165)
remote: Total 565862 (delta 480632), reused 565795 (delta 480632)
Receiving objects: 100% (565862/565862), 291.52 MiB | 22.37 MiB/s, done.
Resolving deltas:  60% (289626/480632)   
[0:01:00] Still working on:
[0:01:00]   v8
Resolving deltas:  75% (360523/480632)   
[0:01:10] Still working on:
[0:01:10]   v8
Resolving deltas:  78% (378114/480632)   
[0:01:20] Still working on:
[0:01:20]   v8
Resolving deltas:  86% (413424/480632)   
[0:01:30] Still working on:
[0:01:30]   v8
Resolving deltas:  91% (437484/480632)   
[0:01:40] Still working on:
[0:01:40]   v8
Resolving deltas:  97% (466463/480632)   
[0:01:50] Still working on:
[0:01:50]   v8
Resolving deltas: 100% (480632/480632), done.

[0:02:00] Still working on:
[0:02:00]   v8

[0:02:10] Still working on:
[0:02:10]   v8

[0:02:20] Still working on:
[0:02:20]   v8
Syncing projects:   0% ( 0/ 2) 
[0:02:22] Still working on:
[0:02:22]   v8
Syncing projects: 100% (23/23), done.                                   

________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' in '/opt/PostgreSQL/src/plv8-2.3.5/build'
0> Downloading v8/buildtools/linux64/clang-format...
Downloading 1 files took 6.852831 second(s)
Running hooks:  35% (10/28) luci-go_linux
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-luci -d v8/tools/luci-go/linux64' in '/opt/PostgreSQL/src/plv8-2.3.5/build'
0> Downloading v8/tools/luci-go/linux64/isolate...
Downloading 1 files took 5.865292 second(s)
Running hooks:  46% (13/28) gn_linux     
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-gn -s v8/buildtools/linux64/gn.sha1' in '/opt/PostgreSQL/src/plv8-2.3.5/build'
0> Downloading v8/buildtools/linux64/gn...
Downloading 1 files took 5.811647 second(s)
Running hooks:  50% (14/28) wasm_spec_tests
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' in '/opt/PostgreSQL/src/plv8-2.3.5/build'
0> Downloading v8/test/wasm-spec-tests/tests.tar.gz...
0> Extracting 72 entries from v8/test/wasm-spec-tests/tests.tar.gz to v8/test/wasm-spec-tests/tests
Downloading 1 files took 5.824146 second(s)
Running hooks:  53% (15/28) closure_compiler
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket chromium-v8-closure-compiler -s v8/src/inspector/build/closure-compiler.tar.gz.sha1' in '/opt/PostgreSQL/src/plv8-2.3.5/build'
0> Downloading v8/src/inspector/build/closure-compiler.tar.gz...
0> Extracting 4 entries from v8/src/inspector/build/closure-compiler.tar.gz to v8/src/inspector/build/closure-compiler
Downloading 1 files took 5.571700 second(s)
Running hooks:  64% (18/28) sysroot_x86     
________ running '/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x86' in '/opt/PostgreSQL/src/plv8-2.3.5/build'
Installing Debian sid i386 root image: /opt/PostgreSQL/src/plv8-2.3.5/build/v8/build/linux/debian_sid_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/1015a998c2adf188813cca60b558b0ea1a0b6ced/debian_sid_i386_sysroot.tar.xz
Running hooks:  71% (20/28) sysroot_x64 
________ running '/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x64' in '/opt/PostgreSQL/src/plv8-2.3.5/build'
Installing Debian sid amd64 root image: /opt/PostgreSQL/src/plv8-2.3.5/build/v8/build/linux/debian_sid_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/1015a998c2adf188813cca60b558b0ea1a0b6ced/debian_sid_amd64_sysroot.tar.xz
Running hooks:  85% (24/28) binutils            
________ running '/bin/python v8/third_party/binutils/download.py' in '/opt/PostgreSQL/src/plv8-2.3.5/build'
0> Downloading /opt/PostgreSQL/src/plv8-2.3.5/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2...
Downloading 1 files took 6.155275 second(s)
Downloading /opt/PostgreSQL/src/plv8-2.3.5/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
Extracting /opt/PostgreSQL/src/plv8-2.3.5/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
Running hooks:  89% (25/28) clang   
________ running '/bin/python v8/tools/clang/scripts/update.py' in '/opt/PostgreSQL/src/plv8-2.3.5/build'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-334100-1.tgz .......... Done.
Running hooks: 100% (28/28), done.        
Running: git submodule foreach 'git config -f $toplevel/.git/config submodule.$name.ignore all'
Running: git config --add remote.origin.fetch '+refs/tags/*:refs/tags/*'
Running: git config diff.ignoreSubmodules all

Can I ignore this error?
**error: Your local changes to the following files would be overwritten by checkout:
        tools/turbolizer/turbolizer.png
Please, commit your changes or stash them before you can switch branches.
Aborting**
Syncing projects: 100% (23/23), done.                                   
Running hooks: 100% (28/28), done.        
cd build/v8 ; env CXXFLAGS=-fPIC CFLAGS=-fPIC ninja -C out.gn/x64.release d8
ninja: Entering directory `out.gn/x64.release'
...

**Comment by JerrySievert** [comment]
```
error: Your local changes to the following files would be overwritten by checkout:
tools/turbolizer/turbolizer.png
Please, commit your changes or stash them before you can switch branches.
Aborting**
```

I've compiled `plv8` maybe 2000-3000 times, and because of that, `v8` maybe 5000-6000 times, and I've never seen that particular error message.  so, I'm going to say that it's not safe to ignore that. :)

it's telling you that there are local changes in the `v8` directory, and thus isn't going to checkout the correct branch - that's not going to work, as noted before, because of api changes between `v8` versions.

if you're willing to get your hands dirty, you can try removing the `build` directory (or move it out of the way), and try the commands by hand:

```
$ mkdir -p build
$ cd build
$ git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
$ fetch v8
$ cd v8
$ git checkout 6.4.388.40
$ gclient sync 
$ tools/dev/v8gen.py x64.release -- is_component_build=false v8_static_library=true v8_use_snapshot=true v8_use_external_startup_data=false v8_enable_i18n_support=false
```

and note any errors or warnings for each step.  you'll need `depot_tools` in your path for the `fetch` and `gclient` commands to execute.

**Comment by hellower** [comment]
I follow your guide!
$ rm -rf build
$ cd build
$ git clone ..
$ fetch v8
$ cd v8
$ **git checkout 6.4.388.40**
error: Your local changes to the following files would be overwritten by checkout:
        tools/turbolizer/turbolizer.png
Please, commit your changes or stash them before you can switch branches.
Aborting
$ 

Is my linux machie fault?
sorry for poor english

**Comment by hellower** [comment]
finally compiled !! 

git checkout -f 6.4.388.40  ( -f option !!!)

but plv8-2.3.4.so file  is made  not plv8-2.3.5.so.   (very strainge..)
anyway  compiled good

Thanks for your GREATE SUPPORT!

**Comment by JerrySievert** [comment]
yeah, I noticed that locally when I did a rebuild - trying to figure that out right now.  2.3.5 was a bug-fix maintenance update, no new features.

**Comment by JerrySievert** [comment]
I'm going to close this.
