### ISSUE TITLE
[Q] plv8.v8_flags

### ISSUE THREAD

**Issue by hellower** [plv8/plv8#289]
from manual
plv8.v8_flags | V8 engine initialization flags (e.g. --harmony for all current harmony features) | none

if  setting below
plv8.v8_flags='--max-old-space-size=2048'   # 2GB

Is this value  applied

**Comment by JerrySievert** [comment]
all `v8` specific flags can only be applied per session, given that a new `v8` instance is instantiated per postgres process.  postgres forks for each session.

**Comment by hellower** [comment]
Thank you!
