### ISSUE TITLE
postgres looking for "plv8.so", `make static && make install` creates plv8-$PLV8_VERSION.so

### ISSUE THREAD

**Issue by cwrinn** [plv8/plv8#290]
Seems to be caused by a change two months ago in the Makefile.shared:
https://github.com/plv8/plv8/commit/99261a6bed9cf50123a7b979645e53ff592b10c0

Here's my Dockerfile (clkao's is out of date, I need a newer plv8):
```dockerfile
ARG pg_major=9.4
FROM postgres:${pg_major}
ARG plv8_version=v2.3.4
ENV PLV8_VERSION=${plv8_version}

RUN buildDependencies=" \
      build-essential \
      ca-certificates \
      curl \
      git-core \
      libglib2.0-dev \
      libc++-dev \
      postgresql-server-dev-${PG_MAJOR} \
      python \
    " \
 && runDependencies=" \
      libc++1 \
    " \
 && apt-get update \
 && apt-get install -y --no-install-recommends ${buildDependencies} ${runDependencies} \
 && mkdir /tmp/build \
 && curl -o /tmp/build/${PLV8_VERSION}.tar.gz -SL "https://github.com/plv8/plv8/archive/$PLV8_VERSION.tar.gz" \
 && tar -xf /tmp/build/${PLV8_VERSION}.tar.gz -C /tmp/build \
 && cd /tmp/build/plv8-${PLV8_VERSION#?} \
 && make static \
 && make install \
 && strip /usr/lib/postgresql/${PG_MAJOR}/lib/plv8-${PLV8_VERSION#?}.so \
 && ln -s /usr/lib/postgresql/${PG_MAJOR}/lib/plv8-${PLV8_VERSION#?}.so /usr/lib/postgresql/${PG_MAJOR}/lib/plv8.so \
 && cd / \
 && apt-get purge -y --auto-remove ${buildDependencies} \
 && rm -rf /tmp/build \
           /var/lib/apt/lists/*

COPY [0-9]* /docker-entrypoint-init.db.d/
COPY [a-z]* /scripts/
```

As a workaround, I symlinked. That appears to work, tho it might not be the best solution.

**Comment by JerrySievert** [comment]
can you paste your `plv8.control` file, and verify that it's not different in `/usr/lib/postgresql/extension`?

**Comment by cwrinn** [comment]
in /usr/share/postgresql/9.4/extension:
```
## plv8 extension
comment = 'PL/JavaScript (v8) trusted procedural language'
default_version = '2.3.4'
module_pathname = '$libdir/plv8-2.3.4'
relocatable = false
schema = pg_catalog
superuser = true
```

And that is the only one in the entire fs of the container image.

**Comment by cwrinn** [comment]
Update: It appears this is not happening on a fresh database.

**Comment by JerrySievert** [comment]
I was wondering about that.

**Comment by cwrinn** [comment]
I'll close this if that fixes it, but need to wait for a maintenance window to test it. Thanks for the help.

**Comment by JerrySievert** [comment]
sounds good.

**Comment by cwrinn** [comment]
While I feel we are on the right track, this did not work. The above command also had the error.
I backed up the database, dropped it, recreated, reinstalled plv8 on it, and restored the backup.
Now all appears to be well.
