### ISSUE TITLE
macOS 10.14 Build Error

### ISSUE THREAD

**Issue by yasyf** [plv8/plv8#303]
Just a heads up that building `2.3.5` fails on macOS 10.14, because of [this Xcode version check issue](https://github.com/Homebrew/homebrew-core/issues/31616) (related to [this older issue](https://bugs.chromium.org/p/chromium/issues/detail?id=620127)). The build scripts have been fixed in `v8@6.9`, but since `plv8@2.3.5` is pinned to `v8@6.4.388.40`, the bug is still present. 

I was able to get around this by manually patching `v8@6.4.388.40` with [the commit with the fix](https://chromium.googlesource.com/chromium/src/build.git/+/4287a0d364541583a50cc91465330251460d489a%5E%21), building it, and then pointing `plv8` to this build, but it took a while to figure out.

Unfortunately, once that's solved, I get the following error message:

```bash

⚡ make
g++ -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -bundle -multiply_defined suppress -o plv8-2.3.5.so plv8.o plv8_type.o plv8_func.o plv8_param.o coffee-script.o livescript.o -L/usr/local/lib  -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -Wl,-dead_strip_dylibs   -Lbuild/v8/out.gn/x64.release/obj -Lbuild/v8/out.gn/x64.release/obj/third_party/icu -lv8_base -lv8_snapshot -lv8_libplatform -lv8_libbase -lv8_libsampler -lv8_libplatform -bundle_loader /usr/local/Cellar/postgresql/10.5/bin/postgres -Lbuild/v8/out.gn/x64.release/obj -stdlib=libc++
Undefined symbols for architecture x86_64:
  "v8::base::CallOnceImpl(long*, void (*)(void*), void*)", referenced from:
      v8::internal::JavaScriptFrame::CollectFunctionAndOffsetForICStats(v8::internal::JSFunction*, v8::internal::AbstractCode*, int) in libv8_base.a(frames.o)
      v8::internal::JavaScriptFrame::CollectTopFrameForICStats(v8::internal::Isolate*) in libv8_base.a(frames.o)
      v8::internal::CpuProfiler::CpuProfiler(v8::internal::Isolate*, v8::internal::CpuProfilesCollection*, v8::internal::ProfileGenerator*, v8::internal::ProfilerEventsProcessor*) in libv8_base.a(cpu-profiler.o)
      v8::internal::CpuProfiler::~CpuProfiler() in libv8_base.a(cpu-profiler.o)
      v8::internal::CpuProfiler::CollectSample(v8::internal::Isolate*) in libv8_base.a(cpu-profiler.o)
      v8::internal::ProfileGenerator::RecordTickSample(v8::internal::TickSample const&) in libv8_base.a(profile-generator.o)
      v8::internal::ProfileGenerator::EntryForVMState(v8::StateTag) in libv8_base.a(profile-generator.o)
      ...
  "v8::base::OS::Initialize(long long, bool, char const*)", referenced from:
      v8::internal::V8::InitializeOncePerProcessImpl() in libv8_base.a(v8.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by JerrySievert** [comment]
thanks - I'll take a look.  plv8 is developed on macOS, so I tend to try to make sure it works well on macOS before anything else.

**Comment by JerrySievert** [comment]
unfortunately, since so much changes in versions of v8, it's important to pin the specific v8 versions.

**Comment by yasyf** [comment]
yup, got that from the various other issues that occur when you try to swap out the v8 version. `6.4.388.40` _is_ the one that 2.3.5 is pinned to, though.

**Comment by JerrySievert** [comment]
yup. it was pinned there when there weren't issues with it - I'll take a look and see what I can do with getting it working regardless.

thanks for the issue.

**Comment by yasyf** [comment]
thank you! let me know how I can help :)

**Comment by JerrySievert** [comment]
ok, took a while but I have a clean build environment again - I'll update when I have some better answers.

**Comment by JerrySievert** [comment]
```
$ cd build/v8/build
$ git cherry-pick 4287a0d364541583a50cc91465330251460d489a
```

gets it compiling, I'll let you know when the compilation is complete.  if it ends up working, it should be an easy fix to patch the build process in the `Makefile`.

**Comment by JerrySievert** [comment]
looks like something weird is going on with Xcode 10 for me, it's not building the libraries like I expect.

looking at updating to either a much newer version of v8, or whether llvm itself might be a better build environment.  I'd prefer to not move to another major v8 version right now, as it's quite a lot of work validating everything across all platforms, but will do it if I need to.

would you be willing to look to see if `libv8_base.dylib` is being generated in `build/v8/out.gn/x64.release` somewhere? (either there, or in the `obj` directory inside of there).

**Comment by yasyf** [comment]
I have a `obj/libv8_base.a`, but no `libv8_base.dylib`

**Comment by JerrySievert** [comment]
want to give https://github.com/JerrySievert/plv8 a run?

**Comment by yasyf** [comment]
`/bin/sh: line 0: cd: build/config: No such file or directory`

**Comment by yasyf** [comment]
and when you change it to `cd build`, the same error as my original issue

**Comment by JerrySievert** [comment]
can you make sure the `build` directory is out of the way?

this will only work on a fresh build, given the way the v8 checkout and configuration works.

**Comment by JerrySievert** [comment]
the build process should end up looking something like this: https://travis-ci.org/JerrySievert/plv8/jobs/434815176#L1088

**Comment by JerrySievert** [comment]
this is the build output you should be seeing on macOS:

```
 ~/w/plv8   master $…  make
mkdir -p build
cd build; git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
Cloning into 'depot_tools'...
remote: Sending approximately 21.66 MiB ...
remote: Total 28497 (delta 20339), reused 28497 (delta 20339)
Receiving objects: 100% (28497/28497), 21.66 MiB | 2.92 MiB/s, done.
Resolving deltas: 100% (20339/20339), done.
cd build; fetch v8; cd v8; git checkout 6.4.388.40; gclient sync ; cd build/config ; git cherry-pick 4287a0d364541583a50cc91465330251460d489a ; cd ../.. ; tools/dev/v8gen.py x64.release -- is_component_build=false v8_static_library=true v8_use_snapshot=true v8_use_external_startup_data=false v8_enable_i18n_support=false
Running: gclient root
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/v8/v8.git /Users/jerry/work/plv8/build/_gclient_v8_XU9Srz' in '/Users/jerry/work/plv8/build'
Cloning into '/Users/jerry/work/plv8/build/_gclient_v8_XU9Srz'...
remote: Sending approximately 388.39 MiB ...
remote: Counting objects: 7755, done
remote: Finding sources: 100% (95/95)
Receiving objects:  57% (344822/597917), 136.46 MiB | 3.95 MiB/s
[0:01:00] Still working on:
[0:01:00]   v8
Receiving objects:  59% (352850/597917), 175.51 MiB | 3.63 MiB/s
[0:01:10] Still working on:
[0:01:10]   v8
Receiving objects:  60% (361244/597917), 209.94 MiB | 3.18 MiB/s
[0:01:20] Still working on:
[0:01:20]   v8
Receiving objects:  62% (372310/597917), 247.24 MiB | 3.07 MiB/s
[0:01:30] Still working on:
[0:01:30]   v8
Receiving objects:  63% (379850/597917), 281.60 MiB | 3.86 MiB/s
[0:01:40] Still working on:
[0:01:40]   v8
Receiving objects:  63% (382338/597917), 299.85 MiB | 1.46 MiB/s
[0:01:50] Still working on:
[0:01:50]   v8
Receiving objects:  65% (390130/597917), 328.40 MiB | 1.97 MiB/s
[0:02:00] Still working on:
[0:02:00]   v8
Receiving objects:  66% (397074/597917), 343.77 MiB | 1.65 MiB/s
[0:02:10] Still working on:
[0:02:10]   v8
Receiving objects:  81% (485255/597917), 362.01 MiB | 1.59 MiB/s
[0:02:20] Still working on:
[0:02:20]   v8
Receiving objects:  91% (545121/597917), 377.13 MiB | 1.61 MiB/s
[0:02:30] Still working on:
[0:02:30]   v8
Receiving objects:  96% (574001/597917), 383.76 MiB | 266.00 KiB/s
[0:02:40] Still working on:
[0:02:40]   v8
remote: Total 597917 (delta 502912), reused 597860 (delta 502912)
Receiving objects: 100% (597917/597917), 388.70 MiB | 2.50 MiB/s, done.
Resolving deltas:  29% (146041/502912)
[0:02:50] Still working on:
[0:02:50]   v8
Resolving deltas:  64% (321934/502912)
[0:03:00] Still working on:
[0:03:00]   v8
Resolving deltas:  88% (443061/502912)
[0:03:10] Still working on:
[0:03:10]   v8
Resolving deltas: 100% (502912/502912), done.

[0:03:20] Still working on:
[0:03:20]   v8

[0:03:30] Still working on:
[0:03:30]   v8

[0:03:40] Still working on:
[0:03:40]   v8

[0:03:50] Still working on:
[0:03:50]   v8

[0:04:00] Still working on:
[0:04:00]   v8

[0:04:10] Still working on:
[0:04:10]   v8
Syncing projects:   0% ( 0/ 2)
[0:04:10] Still working on:
[0:04:10]   v8
Syncing projects:  91% (21/23) v8/test/test262/data
[0:08:54] Still working on:
[0:08:54]   v8/third_party/catapult
[0:08:54]   v8/third_party/icu

[0:09:04] Still working on:
[0:09:04]   v8/third_party/catapult
[0:09:04]   v8/third_party/icu

[0:09:14] Still working on:
[0:09:14]   v8/third_party/catapult
[0:09:14]   v8/third_party/icu

[0:09:24] Still working on:
[0:09:24]   v8/third_party/catapult
[0:09:24]   v8/third_party/icu

[0:09:34] Still working on:
[0:09:34]   v8/third_party/catapult
[0:09:34]   v8/third_party/icu

[0:09:44] Still working on:
[0:09:44]   v8/third_party/catapult
[0:09:44]   v8/third_party/icu

[0:09:54] Still working on:
[0:09:54]   v8/third_party/catapult
[0:09:54]   v8/third_party/icu

[0:10:04] Still working on:
[0:10:04]   v8/third_party/catapult
[0:10:04]   v8/third_party/icu

[0:10:14] Still working on:
[0:10:14]   v8/third_party/catapult
[0:10:14]   v8/third_party/icu

[0:10:24] Still working on:
[0:10:24]   v8/third_party/catapult
[0:10:24]   v8/third_party/icu

[0:10:34] Still working on:
[0:10:34]   v8/third_party/catapult
[0:10:34]   v8/third_party/icu

[0:10:44] Still working on:
[0:10:44]   v8/third_party/catapult
[0:10:44]   v8/third_party/icu

[0:10:54] Still working on:
[0:10:54]   v8/third_party/catapult
[0:10:54]   v8/third_party/icu

[0:11:04] Still working on:
[0:11:04]   v8/third_party/catapult
[0:11:04]   v8/third_party/icu

[0:11:14] Still working on:
[0:11:14]   v8/third_party/catapult
[0:11:14]   v8/third_party/icu

[0:11:17] Still working on:
[0:11:17]   v8/third_party/catapult
[0:11:17]   v8/third_party/icu
Syncing projects: 100% (23/23), done.

________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-clang-format -s v8/buildtools/mac/clang-format.sha1' in '/Users/jerry/work/plv8/build'
0> Downloading v8/buildtools/mac/clang-format...
Downloading 1 files took 27.910733 second(s)
Hook 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-clang-format -s v8/buildtools/mac/clang-format.sha1' took 28.05 secs
Running hooks:  30% ( 9/30) luci-go_mac
________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-luci -d v8/tools/luci-go/mac64' in '/Users/jerry/work/plv8/build'
0> Downloading v8/tools/luci-go/mac64/isolate...
Downloading 1 files took 25.433583 second(s)
Hook 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-luci -d v8/tools/luci-go/mac64' took 25.62 secs
Running hooks:  40% (12/30) gn_mac
________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-gn -s v8/buildtools/mac/gn.sha1' in '/Users/jerry/work/plv8/build'
0> Downloading v8/buildtools/mac/gn...
Downloading 1 files took 18.261423 second(s)
Hook 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-gn -s v8/buildtools/mac/gn.sha1' took 18.37 secs
Running hooks:  46% (14/30) wasm_spec_tests
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' in '/Users/jerry/work/plv8/build'
0> Downloading v8/test/wasm-spec-tests/tests.tar.gz...
0> Extracting 72 entries from v8/test/wasm-spec-tests/tests.tar.gz to v8/test/wasm-spec-tests/tests
Downloading 1 files took 19.469310 second(s)
Hook 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' took 19.64 secs
Running hooks:  50% (15/30) closure_compiler
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket chromium-v8-closure-compiler -s v8/src/inspector/build/closure-compiler.tar.gz.sha1' in '/Users/jerry/work/plv8/build'
0> Downloading v8/src/inspector/build/closure-compiler.tar.gz...
0> Extracting 4 entries from v8/src/inspector/build/closure-compiler.tar.gz to v8/src/inspector/build/closure-compiler
Downloading 1 files took 24.042961 second(s)
Hook 'download_from_google_storage --no_resume --no_auth -u --bucket chromium-v8-closure-compiler -s v8/src/inspector/build/closure-compiler.tar.gz.sha1' took 24.16 secs
Running hooks:  83% (25/30) clang
________ running '/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python v8/tools/clang/scripts/update.py' in '/Users/jerry/work/plv8/build'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Mac/clang-342523-1.tgz .......... Done.
Hook '/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python v8/tools/clang/scripts/update.py' took 22.19 secs
Running hooks: 100% (30/30), done.
Running: git submodule foreach 'git config -f $toplevel/.git/config submodule.$name.ignore all'
Running: git config --add remote.origin.fetch '+refs/tags/*:refs/tags/*'
Running: git config diff.ignoreSubmodules all
Checking out files: 100% (3761/3761), done.
Previous HEAD position was 9e99297e56 [async-await] Unify handling of await closure contexts.
HEAD is now at d481edab15 Version 6.4.388.40
Syncing projects: 100% (23/23), done.

________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-luci -d v8/tools/luci-go/mac64' in '/Users/jerry/work/plv8/build'
0> Downloading v8/tools/luci-go/mac64/isolate...
Downloading 1 files took 24.255375 second(s)
Hook 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-luci -d v8/tools/luci-go/mac64' took 24.35 secs
Running hooks:  47% (11/23) gn_mac
________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-gn -s v8/buildtools/mac/gn.sha1' in '/Users/jerry/work/plv8/build'
0> Downloading v8/buildtools/mac/gn...
Downloading 1 files took 22.797204 second(s)
Hook 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-gn -s v8/buildtools/mac/gn.sha1' took 22.93 secs
Running hooks:  56% (13/23) wasm_spec_tests
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' in '/Users/jerry/work/plv8/build'
0> Downloading v8/test/wasm-spec-tests/tests.tar.gz...
0> Removed v8/test/wasm-spec-tests/tests...
0> Extracting 65 entries from v8/test/wasm-spec-tests/tests.tar.gz to v8/test/wasm-spec-tests/tests
Downloading 1 files took 18.636236 second(s)
Hook 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' took 18.77 secs
Running hooks:  86% (20/23) clang
________ running '/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python v8/tools/clang/scripts/update.py' in '/Users/jerry/work/plv8/build'
Updating Clang to 318667-1...
Downloading prebuilt clang
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Mac/clang-318667-1.tgz .......... Done.
Creating directory /Users/jerry/work/plv8/build/v8/third_party/llvm-build/Release+Asserts
clang 318667-1 unpacked
Hook '/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python v8/tools/clang/scripts/update.py' took 32.07 secs
Running hooks:  95% (22/23) regyp_if_needed
________ running '/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python v8/gypfiles/gyp_v8 --running-as-hook' in '/Users/jerry/work/plv8/build'
GYP is now disabled by default in runhooks.

If you really want to run this, either run
`python gypfiles/gyp_v8` explicitly by hand
or set the environment variable GYP_CHROMIUM_NO_ACTION=0.
Running hooks: 100% (23/23), done.

WARNING: 'v8/third_party/googletest/src' is no longer part of this client.  It is recommended that you manually remove it.


WARNING: 'v8/third_party/depot_tools' is no longer part of this client.  It is recommended that you manually remove it.


WARNING: 'v8/third_party/catapult' is no longer part of this client.  It is recommended that you manually remove it.

[detached HEAD b30228feb] [ios] Various build fixes for Xcode 10.
 Author: Justin Cohen <justincohen@google.com>
 Date: Tue Jun 5 15:30:25 2018 +0000
 2 files changed, 36 insertions(+), 11 deletions(-)
cd build/v8 ; env CXXFLAGS=-fPIC CFLAGS=-fPIC ninja -C out.gn/x64.release d8
ninja: Entering directory `out.gn/x64.release'
[1/1] Regenerating ninja files
[197/615] CXX obj/src/inspector/inspector/remote-object-id.o
```

**Comment by JerrySievert** [comment]
can you do a fresh checkout and copy the output from `make` and paste it into this issue?

**Comment by kkzz8888** [comment]
......
Running hooks: 100% (23/23), done.         

WARNING: 'v8/third_party/googletest/src' is no longer part of this client.  It is recommended that you manually remove it.


WARNING: 'v8/third_party/depot_tools' is no longer part of this client.  It is recommended that you manually remove it.


WARNING: 'v8/third_party/catapult' is no longer part of this client.  It is recommended that you manually remove it.

[detached HEAD 771a8d17c] [ios] Various build fixes for Xcode 10.
 Author: Justin Cohen <justincohen@google.com>
 Date: Tue Jun 5 15:30:25 2018 +0000
 2 files changed, 36 insertions(+), 11 deletions(-)
cd build/v8 ; env CXXFLAGS=-fPIC CFLAGS=-fPIC ninja -C out.gn/x64.release d8
ninja: Entering directory `out.gn/x64.release'
[1/1] Regenerating ninja files
[1/1] Regenerating ninja files
[615/615] LINK ./d8
sed -e 's/^#undef PLV8_VERSION/#define PLV8_VERSION "2.3.8"/' plv8_config.h.in > plv8_config.h
g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8/include -Ibuild/v8 -stdlib=libc++ -std=c++11 -I. -I./ -I/usr/local/Cellar/postgresql/10.4/include/server -I/usr/local/Cellar/postgresql/10.4/include/internal  -I/usr/local/opt/openssl/include -I/usr/local/opt/readline/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2  -fPIC -c -o plv8.o plv8.cc
In file included from plv8.cc:25:
In file included from /usr/local/Cellar/postgresql/10.4/include/server/commands/trigger.h:17:
In file included from /usr/local/Cellar/postgresql/10.4/include/server/nodes/execnodes.h:17:
In file included from /usr/local/Cellar/postgresql/10.4/include/server/access/genam.h:19:
In file included from /usr/local/Cellar/postgresql/10.4/include/server/nodes/tidbitmap.h:26:
In file included from /usr/local/Cellar/postgresql/10.4/include/server/utils/dsa.h:17:
In file included from /usr/local/Cellar/postgresql/10.4/include/server/port/atomics.h:70:
/usr/local/Cellar/postgresql/10.4/include/server/port/atomics/arch-x86.h:143:2: warning: 'register' storage class specifier is deprecated and incompatible with C++17
      [-Wdeprecated-register]
        register char _res = 1;
        ^~~~~~~~~
In file included from plv8.cc:25:
In file included from /usr/local/Cellar/postgresql/10.4/include/server/commands/trigger.h:17:
In file included from /usr/local/Cellar/postgresql/10.4/include/server/nodes/execnodes.h:31:
In file included from /usr/local/Cellar/postgresql/10.4/include/server/storage/condition_variable.h:25:
/usr/local/Cellar/postgresql/10.4/include/server/storage/s_lock.h:226:2: warning: 'register' storage class specifier is deprecated and incompatible with C++17
      [-Wdeprecated-register]
        register slock_t _res = 1;
        ^~~~~~~~~
2 warnings generated.
g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8/include -Ibuild/v8 -stdlib=libc++ -std=c++11 -I. -I./ -I/usr/local/Cellar/postgresql/10.4/include/server -I/usr/local/Cellar/postgresql/10.4/include/internal  -I/usr/local/opt/openssl/include -I/usr/local/opt/readline/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2  -fPIC -c -o plv8_type.o plv8_type.cc
g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8/include -Ibuild/v8 -stdlib=libc++ -std=c++11 -I. -I./ -I/usr/local/Cellar/postgresql/10.4/include/server -I/usr/local/Cellar/postgresql/10.4/include/internal  -I/usr/local/opt/openssl/include -I/usr/local/opt/readline/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2  -fPIC -c -o plv8_func.o plv8_func.cc
In file included from plv8_func.cc:15:
In file included from /usr/local/Cellar/postgresql/10.4/include/server/executor/spi.h:16:
In file included from /usr/local/Cellar/postgresql/10.4/include/server/commands/trigger.h:17:
In file included from /usr/local/Cellar/postgresql/10.4/include/server/nodes/execnodes.h:17:
In file included from /usr/local/Cellar/postgresql/10.4/include/server/access/genam.h:19:
In file included from /usr/local/Cellar/postgresql/10.4/include/server/nodes/tidbitmap.h:26:
In file included from /usr/local/Cellar/postgresql/10.4/include/server/utils/dsa.h:17:
In file included from /usr/local/Cellar/postgresql/10.4/include/server/port/atomics.h:70:
/usr/local/Cellar/postgresql/10.4/include/server/port/atomics/arch-x86.h:143:2: warning: 'register' storage class specifier is deprecated and incompatible with C++17
      [-Wdeprecated-register]
        register char _res = 1;
        ^~~~~~~~~
In file included from plv8_func.cc:15:
In file included from /usr/local/Cellar/postgresql/10.4/include/server/executor/spi.h:16:
In file included from /usr/local/Cellar/postgresql/10.4/include/server/commands/trigger.h:17:
In file included from /usr/local/Cellar/postgresql/10.4/include/server/nodes/execnodes.h:31:
In file included from /usr/local/Cellar/postgresql/10.4/include/server/storage/condition_variable.h:25:
/usr/local/Cellar/postgresql/10.4/include/server/storage/s_lock.h:226:2: warning: 'register' storage class specifier is deprecated and incompatible with C++17
      [-Wdeprecated-register]
        register slock_t _res = 1;
        ^~~~~~~~~
2 warnings generated.
g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8/include -Ibuild/v8 -stdlib=libc++ -std=c++11 -I. -I./ -I/usr/local/Cellar/postgresql/10.4/include/server -I/usr/local/Cellar/postgresql/10.4/include/internal  -I/usr/local/opt/openssl/include -I/usr/local/opt/readline/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2  -fPIC -c -o plv8_param.o plv8_param.cc
echo "extern const unsigned char coffee_script_binary_data[] = {" >coffee-script.cc
(od -txC -v coffee-script.js | \
	sed -e "s/^[0-9]*//" -e s"/ \([0-9a-f][0-9a-f]\)/0x\1,/g" -e"\$d" ) >>coffee-script.cc
echo "0x00};" >>coffee-script.cc
g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8/include -Ibuild/v8 -stdlib=libc++ -std=c++11 -I. -I./ -I/usr/local/Cellar/postgresql/10.4/include/server -I/usr/local/Cellar/postgresql/10.4/include/internal  -I/usr/local/opt/openssl/include -I/usr/local/opt/readline/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2  -fPIC -c -o coffee-script.o coffee-script.cc
echo "extern const unsigned char livescript_binary_data[] = {" >livescript.cc
(od -txC -v livescript.js | \
	sed -e "s/^[0-9]*//" -e s"/ \([0-9a-f][0-9a-f]\)/0x\1,/g" -e"\$d" ) >>livescript.cc
echo "0x00};" >>livescript.cc
g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8/include -Ibuild/v8 -stdlib=libc++ -std=c++11 -I. -I./ -I/usr/local/Cellar/postgresql/10.4/include/server -I/usr/local/Cellar/postgresql/10.4/include/internal  -I/usr/local/opt/openssl/include -I/usr/local/opt/readline/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2  -fPIC -c -o livescript.o livescript.cc
g++ -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -bundle -multiply_defined suppress -o plv8-2.3.8.so plv8.o plv8_type.o plv8_func.o plv8_param.o coffee-script.o livescript.o -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -Wl,-dead_strip_dylibs   -Lbuild/v8/out.gn/x64.release/obj -Lbuild/v8/out.gn/x64.release/obj/third_party/icu -lv8_base -lv8_snapshot -lv8_libplatform -lv8_libbase -lv8_libsampler -lv8_libplatform -bundle_loader /usr/local/Cellar/postgresql/10.4/bin/postgres -Lbuild/v8/out.gn/x64.release/obj -stdlib=libc++
Undefined symbols for architecture x86_64:
  "v8::base::CallOnceImpl(long*, void (*)(void*), void*)", referenced from:
      v8::internal::JavaScriptFrame::CollectFunctionAndOffsetForICStats(v8::internal::JSFunction*, v8::internal::AbstractCode*, int) in libv8_base.a(frames.o)
      v8::internal::JavaScriptFrame::CollectTopFrameForICStats(v8::internal::Isolate*) in libv8_base.a(frames.o)
      v8::internal::CpuProfiler::CpuProfiler(v8::internal::Isolate*, v8::internal::CpuProfilesCollection*, v8::internal::ProfileGenerator*, v8::internal::ProfilerEventsProcessor*) in libv8_base.a(cpu-profiler.o)
      v8::internal::CpuProfiler::~CpuProfiler() in libv8_base.a(cpu-profiler.o)
      v8::internal::CpuProfiler::CollectSample(v8::internal::Isolate*) in libv8_base.a(cpu-profiler.o)
      v8::internal::ProfileGenerator::RecordTickSample(v8::internal::TickSample const&) in libv8_base.a(profile-generator.o)
      v8::internal::ProfileGenerator::EntryForVMState(v8::StateTag) in libv8_base.a(profile-generator.o)
      ...
  "v8::base::OS::Initialize(long long, bool, char const*)", referenced from:
      v8::internal::V8::InitializeOncePerProcessImpl() in libv8_base.a(v8.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [plv8-2.3.8.so] Error 1

**Comment by JerrySievert** [comment]
it appears that it's not including `src/base/platform/platform-posix.cc` in the build, which is odd since it is compiling and passing tests for me.

**Comment by JerrySievert** [comment]
a couple of things to try:

add `v8_monolithic=true` to line 19 of `Makefile`.

if that doesn't change anything, edit `build/v8/src/v8.gyp`, lines `2073` and `2099`, add a trailing comma to `'base/platform/platform-posix.cc'`.

**Comment by kkzz8888** [comment]
does not seem to change anything. I am using 2.3.8 branch as I mentioned above.

**Comment by JerrySievert** [comment]
as noted, it's building great for me with Xcode 10, which leaves one difference - I'm still on high Sierra, not on Mojave:

```
Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

it will take a few days for me to get up to Mojave.

**Comment by kkzz8888** [comment]
no problem, I can wait. thanks!

**Comment by JerrySievert** [comment]
I'm on Mojave now (wow, dark mode is ... dark), and it's still building just fine from scratch for me.

now we should look for any differences in environment beyond that.

can you paste `build/v8/out.gn/x64.release/args.gn` here, as well as the output of `which clang++`,  `clang++ --version`, `python --version`

**Comment by JerrySievert** [comment]
and just to make sure, you don't have something silly like the gcc/g++ suite installed, do you?

**Comment by kkzz8888** [comment]
args.gn:
is_debug = false
target_cpu = "x64"

# Additional command-line args:
is_component_build=false
v8_static_library=true
v8_use_snapshot=true
v8_use_external_startup_data=false
v8_monolithic=true
v8_enable_i18n_support=false

which clang++:
/usr/bin/clang++

python --version
Python 2.7.10

**Comment by JerrySievert** [comment]
can you include the output of `clang++ --version`?

**Comment by kkzz8888** [comment]
clang++ --version:

Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by JerrySievert** [comment]
it took about 7 hours to download v8 (I'm on a very slow satellite link), and a few hours to get plv8 ported, but give:

https://github.com/JerrySievert/plv8 - branch `r3.0alpha` a try - you must be on that repo and branch, you should be able to check `Makefile` line `10` and see `7.0.276.20`.

**Comment by kkzz8888** [comment]
thanks! I am able to build. Would this be compatible with v8 6.9 which I have for my mac:
brew info v8:
v8: stable 6.9.427.22 (bottled)
Google's JavaScript engine
https://github.com/v8/v8/wiki
/usr/local/Cellar/v8/5.1.281.47 (33 files, 753.6MB)
  Poured from bottle on 2017-11-12 at 14:04:55
/usr/local/Cellar/v8/6.9.427.22 (31 files, 34MB) *
  Poured from bottle on 2018-09-29 at 16:53:39
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/v8.rb
==> Dependencies
Build: python@2 ✔
==> Requirements
Required: macOS >= 10.11 ✔
==> Analytics
install: 3,593 (30d), 3,250 (90d), 13,619 (365d)
install_on_request: 2,296 (30d), 2,847 (90d), 11,483 (365d)
build_error: 0 (30d)

**Comment by JerrySievert** [comment]
no. v8 is not meant to be distributed as a shared object - each project has different requirements, and is meant to only be embedded.
