### ISSUE TITLE
No rule to make target 'plv8.bc'

### ISSUE THREAD

**Issue by mattaylor** [plv8/plv8#304]
Trying to build v2.3.7 with Postgres 11 on docker, and my build breaks on `No rule to make target 'plv8.bc'`

Any help much appreciated.

This is my Dockerfile ...
```
FROM postgres:11

ENV PLV8_VERSION=v2.3.7 

RUN buildDependencies="build-essential \
    libc++-dev \
    libc++abi-dev \
    ca-certificates \
    curl \
    python \
    pkg-config \
    glib2.0 \
    apt-utils \
    git-core \
    postgresql-server-dev-$PG_MAJOR" \
  && apt-get update \
  && apt-get install -y --no-install-recommends ${buildDependencies} \
  && mkdir -p /tmp/build \
  && curl -o /tmp/build/${PLV8_VERSION}.tar.gz -SL "https://github.com/plv8/plv8/archive/$PLV8_VERSION.tar.gz" \
  && cd /tmp/build \
  && tar -xzf /tmp/build/${PLV8_VERSION}.tar.gz -C /tmp/build/ \
  && cd /tmp/build/plv8-${PLV8_VERSION#?} \
  && make \
  && make install \
  && strip /usr/lib/postgresql/${PG_MAJOR}/lib/plv8.so \
  && cd / \
  && apt-get clean \
  && apt-get remove -y  ${buildDependencies} appapp\
  && apt-get autoremove -y \
  && rm -rf /tmp/build /var/lib/apt/lists/*
```

And this is end of my build output...

```
[653/665] CXX obj/d8/d8-js.o
[654/665] CXX obj/v8_snapshot/experimental-extras-libraries.o
[655/665] CXX obj/v8_snapshot/extras-libraries.o
[656/665] CXX obj/d8/d8-posix.o
[657/665] CXX obj/d8/d8-console.o
[658/665] CXX obj/v8_snapshot/libraries.o
[659/665] CXX obj/v8_snapshot/setup-isolate-deserialize.o
[660/665] CXX obj/v8_snapshot/snapshot.o
[661/665] AR obj/libv8_snapshot.a
[662/665] STAMP obj/v8_maybe_snapshot.stamp
[663/665] STAMP obj/v8.stamp
[664/665] CXX obj/d8/d8.o
[665/665] LINK ./d8
sed -e 's/^#undef PLV8_VERSION/#define PLV8_VERSION "2.3.7"/' plv8_config.h.in > plv8_config.h
g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8/include -Ibuild/v8 -std=c++11 -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5 -fPIC -c -o plv8.o plv8.cc
g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8/include -Ibuild/v8 -std=c++11 -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5 -fPIC -c -o plv8_type.o plv8_type.cc
g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8/include -Ibuild/v8 -std=c++11 -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5 -fPIC -c -o plv8_func.o plv8_func.cc
g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8/include -Ibuild/v8 -std=c++11 -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5 -fPIC -c -o plv8_param.o plv8_param.cc
echo "extern const unsigned char coffee_script_binary_data[] = {" >coffee-script.cc
(od -txC -v coffee-script.js | \
sed -e "s/^[0-9]*//" -e s"/ \([0-9a-f][0-9a-f]\)/0x\1,/g" -e"\$d" ) >>coffee-script.cc
echo "0x00};" >>coffee-script.cc
g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8/include -Ibuild/v8 -std=c++11 -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5 -fPIC -c -o coffee-script.o coffee-script.cc
echo "extern const unsigned char livescript_binary_data[] = {" >livescript.cc
(od -txC -v livescript.js | \
sed -e "s/^[0-9]*//" -e s"/ \([0-9a-f][0-9a-f]\)/0x\1,/g" -e"\$d" ) >>livescript.cc
echo "0x00};" >>livescript.cc
g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8/include -Ibuild/v8 -std=c++11 -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5 -fPIC -c -o livescript.o livescript.cc
g++ -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -shared -o plv8-2.3.7.so plv8.o plv8_type.o plv8_func.o plv8_param.o coffee-script.o livescript.o -L/usr/lib/x86_64-linux-gnu  -Wl,-z,relro -Wl,-z,now -L/usr/lib/llvm-6.0/lib  -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--as-needed  -Lbuild/v8/out.gn/x64.release/obj -Lbuild/v8/out.gn/x64.release/obj/third_party/icu -lv8_base -lv8_snapshot -lv8_libplatform -lv8_libbase -lv8_libsampler -lv8_libplatform -Lbuild/v8/out.gn/x64.release/obj -lrt -std=c++11 -lc++
mkdir -p upgrade
./generate_upgrade.sh 2.3.7
sed -e 's/@PLV8_VERSION@/2.3.7/g' plv8.control.common | g++ -E -P -DLANG_plv8 - > plv8.control
sed -e 's/@LANG_NAME@/plv8/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.3.7/g' | g++ -E -P -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5 -DLANG_plv8 - > plv8--2.3.7.sql
sed -e 's/@PLV8_VERSION@/2.3.7/g' plv8.control.common | g++ -E -P -DLANG_plcoffee - > plcoffee.control
sed -e 's/@LANG_NAME@/plcoffee/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.3.7/g' | g++ -E -P -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5 -DLANG_plcoffee - > plcoffee--2.3.7.sql
sed -e 's/@PLV8_VERSION@/2.3.7/g' plv8.control.common | g++ -E -P -DLANG_plls - > plls.control
sed -e 's/@LANG_NAME@/plls/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.3.7/g' | g++ -E -P -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5 -DLANG_plls - > plls--2.3.7.sql
make: *** No rule to make target 'plv8.bc', needed by 'all'.  Stop.
ERROR: Service 'pgsql' failed to build: The command '/bin/sh -c buildDependencies="build-essential     libc++-dev  libc++abi-dev ca-certificates     curl     python     pkg-config     glib2.0     apt-utils     git-core     postgresql-server-dev-$PG_MAJOR"   && apt-get update   && apt-get install -y --no-install-recommends ${buildDependencies}   && mkdir -p /tmp/build   && curl -o /tmp/build/${PLV8_VERSION}.tar.gz -SL "https://github.com/plv8/plv8/archive/$PLV8_VERSION.tar.gz"   && cd /tmp/build   && tar -xzf /tmp/build/${PLV8_VERSION}.tar.gz -C /tmp/build/   && cd /tmp/build/plv8-${PLV8_VERSION#?}   && make   && make install   && strip /usr/lib/postgresql/${PG_MAJOR}/lib/plv8.so   && cd /   && apt-get clean   && apt-get remove -y  ${buildDependencies} appapp  && apt-get autoremove -y   && rm -rf /tmp/build /var/lib/apt/lists/*' returned a non-zero code: 2
```

**Comment by JerrySievert** [comment]
can you tell me which version of `g++` you're using?

**Comment by JerrySievert** [comment]
```
$ cd build/v8/build
$ git cherry-pick 4287a0d364541583a50cc91465330251460d489a
```

that gets it compiling - I'll let you know when the compilation is complete.

**Comment by JerrySievert** [comment]
also, does this happen to be alpine?

**Comment by mattaylor** [comment]
I was able to build and deploy 2.3.7 on PG 10 after a few adjustments using the following docker file..
(not pg 11 yet)
```
FROM postgres:10

ENV PLV8_VERSION=2.3.7

RUN buildDependencies="build-essential \
    libc++-dev \
    libc++abi-dev \
    ca-certificates \
    curl \
    python \
    pkg-config \
    glib2.0 \
    apt-utils \
    git-core \
    postgresql-server-dev-$PG_MAJOR" \
  && apt-get update \
  && apt-get install -y --no-install-recommends libc++1 ${buildDependencies} \
  && mkdir -p /tmp/build \
  && curl -o /tmp/build/v${PLV8_VERSION}.tar.gz -SL "https://github.com/plv8/plv8/archive/v$PLV8_VERSION.tar.gz" \
  && cd /tmp/build \
  && tar -xzf /tmp/build/v${PLV8_VERSION}.tar.gz -C /tmp/build/ \
  && cd /tmp/build/plv8-${PLV8_VERSION} \
  && make \
  && make install \
  && strip /usr/lib/postgresql/${PG_MAJOR}/lib/plv8-${PLV8_VERSION}.so \
  && cd / \
  && apt-get clean \
  && apt-get remove -y  ${buildDependencies} \
  && apt-get autoremove -y \
  && rm -rf /tmp/build /var/lib/apt/lists/*
```

**Comment by mattaylor** [comment]
Do I need libunwind?

**Comment by JerrySievert** [comment]
I'm not sure why you would, unless it's a dependency of pg10 - it's not a dependency of plv8 or v8.

**Comment by mattaylor** [comment]
it made no differences anyway - same error on pg11

**Comment by JerrySievert** [comment]
I'm updating to pg11 to verify compilation without a docker image, but I'm working with less than 1mbit of bandwidth, so it's taking quite a long time to get everything downloaded and updated.

**Comment by JerrySievert** [comment]
it's building and passing all tests on pg11 for me, outside of a docker environment.  do you have a way to build it outside of docker?

**Comment by mattaylor** [comment]
not at present.
Are you building from a clean vm? Do have any additional insight into additional dependencies that might be missing from the above docker env?
Is `plv8.bc` a LLVM bitcode file?
Is this be related to JIT compilation support in pg11 ?
I'll try building via docker again with `llvm-4.0`  added to my buildDependecies.

**Comment by JerrySievert** [comment]
clean vm, fresh git clone of postgres, on the pg11 tag, fresh checkout of plv8.

can you include your `./configure` options from pg11?  I'm just using `--prefix`

**Comment by mattaylor** [comment]
yey!
add llvm-4.0 to my dependencies solved it!

**Comment by mattaylor** [comment]
spoke to soon - same issue.

**Comment by JerrySievert** [comment]
issue is upstream in pg11 with llvm turned on - they made an assumption that all c++ files end with `.cpp`.

you can fix this temporarily by adding:

```
%.bc : %.cc
	$(COMPILE.cxx.bc) $(CCFLAGS) $(CPPFLAGS) -fPIC -c -o $@ $<
```

around line 104 in `Makefile.shared`

**Comment by mattaylor** [comment]
I can only build from this repo, so I'll have to wait until there is an official fix. 
Has a ticket been logged with pg, or will you be patching `Makefile.shared` as above?

**Comment by JerrySievert** [comment]
I’ve opened a bug on pg, but the person responsible is extreme defensive, so I’m not sure how far it will go (it was introduced as part of the jit addition).

I’ll also be patching as above. 

In the mean time, I’ve also updated v8 to 7.0 and added bigint support. Likely I’ll release 2.3.9 followed quickly by 3.0 (which is currently in about alpha state)

**Comment by mattaylor** [comment]
thx for your help

**Comment by mattaylor** [comment]
Im curious as to what you're cooking up for 3.0. Is there any more info about this anywhere?

**Comment by JerrySievert** [comment]
so far:

* `v8` 7.0
* `BigInt` support

working on:

* debugger
* better `wasm` support

we'll see what makes it in when I end up cutting a release.

is there something specific that you'd like to see?

**Comment by JerrySievert** [comment]
btw, there is a mailing list, where behavior for `BigInt` was posted, but it is very quiet there.

**Comment by mattaylor** [comment]
eg.. 
`DO $$ async { plv8.execute.async('select clock_timestamp()) } $$ LANGUAGE plv8`;

**Comment by JerrySievert** [comment]
that would require adding additional threading and blocking of thread completion, which I'm scared would introduce instability and bad side-effects.  my concern is unhandled callbacks or events that might end up as essentially an infinite loop that will effectively kill the connection and potentially cause locks further down in postgres itself.

**Comment by colin-anderson** [comment]
@mattaylor we have a working build of plv8 2.3.8 against Postgres 11.1 on debian:stretch-slim [here](https://github.com/IonxSolutions/docker-images/tree/master/postgres-plv8/11.1), which uses @JerrySievert's `Makefile.shared` patch.

Note there are 2 Dockerfiles - the `Dockerfile.build` one will build everything from scratch, whereas `Dockerfile` uses prebuilt plv8 binaries (built using `Dockerfile.build') so the build doesn't timeout on Docker Hub. If you just want to grab the binaries, they are hosted [here](https://www.ionxsolutions.com/files/plv8/2.3.8).

**Comment by mattaylor** [comment]
thanks - will check it out.

**Comment by JerrySievert** [comment]
2.3.9 released with this patch, going to close this now.

**Comment by ppKrauss** [comment]
Hi, about BigInt Javascript new native datatype, and the cast for PostgreSQL's  numeric datatype, some news?  There are some internal optimization in the cast process?  And bout INT8 (named "bigint" by PostgreSQL), no confusion?  and about  PostgreSQL internal representation of JSONb numbers, they are like numeric or float numvers?

**Comment by JerrySievert** [comment]
`BigInt` support went live in 3.0alpha 7 months ago.  `BigInt` types from Javascript are converted to pg `INT8`, `INT8` maps back to `BigInt`, and `BigInt` can map back to `NUMERIC`.

pg's internal `JSONB` representation of numbers uses the `NUMERIC` type internally, and thus can be larger than Javascript's `Number` type, but as `BigInt` explicitly does not serialize or deserialize with `JSON`, it still rounds to `Number.MAX_VALUE`.  you can see why by reading the following thread: https://github.com/tc39/proposal-bigint/issues/24

when this is resolved, plv8 will change to match.

until then, `BigInt` is supported, but it is a breaking change, hence being in 3.0 and not being backported.
