### ISSUE TITLE
Possible for SWIG?

### ISSUE THREAD

**Issue by ppKrauss** [plv8/plv8#306]
There are some successful strategies of  compiler-level interface that [connects by SWIG](http://www.swig.org/compat.html) programs written in C and C++ with interpreted languages, like Perl and Javascript. If this project is adapted to SWIG it will run with V8, NodeJS, etc. so multipling the options... Well, I'm unfamiliar with SWIG and language wrappers, make sense?

**Comment by JerrySievert** [comment]
plv8 is specifically a _trusted_ language extension, which essentially sandboxes execution and does not allow for any external system level communication.

the functionality provided by plv8 beyond this is specifically limited in scope:

* query/windowing functions via SPI
* logging using the postgres logging facility

there is not currently a _untrusted_ version of plv8, so this does not make sense.  likely, if there were, it would use the same v8 interfaces used by node, or a wrapper like [nan](https://github.com/nodejs/nan) to provide this functionality.
