### ISSUE TITLE
cursor.fetch leaks memory

### ISSUE THREAD

**Issue by GoogleCodeExporter** [plv8/plv8#64]
```
https://t.co/ijdGoRWQji

Originally reported by Makoto YUI

It seems the object returned by Converter::ToValue is not garbage-collected in 
the loop.
```

Original issue reported on code.google.com by `umi.tan...@gmail.com` on 11 Apr 2013 at 7:29

**Comment by JerrySievert** [comment]
leaving this open for investigation.

**Comment by JerrySievert** [comment]
@myui it appears that you originally reported this before the migration?  unfortunately the URL no longer works, is there anything you can share in this regard, so that we can get it fixed?

thanks much!

**Comment by eugwne** [comment]
This code eats a lot of memory ( generate series 300000 consumes 1,5-2Gb)
```SQL
do $$
var plan = plv8.prepare( 'select v from generate_series(1,300000) as v' );
var cursor = plan.cursor();
while (cursor.fetch()) {}
cursor.close();
plan.free();
plv8.elog(NOTICE, 'done');
$$ language plv8
```
Not sure about gc values, but I couldn't find any usage of SPI_freetuptable for SPI_tuptable after SPI_cursor_fetch

**Comment by JerrySievert** [comment]
i'm happy to take a look at it this week, or if you have the time/energy you're welcome to tackle it.

thanks for the great example!

**Comment by JerrySievert** [comment]
also looks like SPI_finish is missing

**Comment by JerrySievert** [comment]
when i add another 0 to generate_series(), i can definitely see the GC kicking in.
