### ISSUE TITLE
In trigger bigint value of field is constant and wrong 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [plv8/plv8#77]
```
What steps will reproduce the problem?

1. Create table

CREATE TABLE table1 (
  id BIGSERIAL,
  name varchar(50)
  CONSTRAINT objects_pkey PRIMARY KEY(id)
)

CREATE SEQUENCE table1_id_seq
  INCREMENT 1 MINVALUE -9223372036854775808
  MAXVALUE 9223372036854775807 START -9223372036854775808
  CACHE 1;

ALTER SEQUENCE bo.objects_id_seq RESTART WITH -9223372036854775807;



2. create view and trigger for DELETE, INSERT OR UPDATE

CREATE OR REPLACE VIEW table1_view
AS
  SELECT table1.id,
         table1.name
  FROM table1

CREATE OR REPLACE FUNCTION table1_delete_trigger (
)
RETURNS trigger AS
$body$
  plv8.elog(NOTICE, JSON.stringify(OLD));
  return null;
$body$
LANGUAGE 'plv8'
VOLATILE
CALLED ON NULL INPUT
SECURITY INVOKER
COST 100;


3. Insert some rows into table1 and then try delete from table1

delete from table1 where id = -9223372036854775807


Y'll see in console 
NOTICE:  {"id":-9223372036854776000,"name":"some name"}

-9223372036854776000 - appears always whatever row y'll delete



What is the expected output? What do you see instead?
expected to have correct value of bigint in OLD and NEW structures



What version of the product are you using? On what operating system?
PostgreSQL 9.3beta2, compiled by Visual C++ build 1600, 64-bit


Please provide any additional information below.


```

Original issue reported on code.google.com by `vovapjat...@gmail.com` on 29 Jun 2013 at 11:22

**Comment by skabbes** [comment]
Any update on this?  Using bigint is broken in very subtle ways :(

I'm happy to help if you point me in the right direction.

**Comment by JerrySievert** [comment]
there are only so many bits for numbers in ecmascript - how do you propose the conversion occurs?

i can probably point you in the right direction, once that's answered!

**Comment by skabbes** [comment]
The problem as I see it is that if you use bigint with <52 bits everything works and is great, but once you cross that threshold things all of a sudden start to break.

I think there are a few potential solutions:
1. Use a BigInteger package like: https://www.npmjs.com/package/big-integer, or mongoDb's solution [Long](https://mongodb.github.io/node-mongodb-native/api-bson-generated/long.html)
2. Use strings
3. Don't support bigint, int8, fixed precision decimal at all

If you take [node-postgres](https://github.com/brianc/node-postgres) as an example, they represent them as base10 strings.

I strings are the "node" way, but also anyone who wants to do math on a bigint, (or a decimal type for that matter) is going to pull in another library, so maybe that is cause to add one.

**Comment by JerrySievert** [comment]
@umitanuki can you weigh in?  i'd be hesitant to rely on an external library, if we can avoid that.

**Comment by JerrySievert** [comment]
as an aside, my personal preference would be base10 strings if > 51 bits (since there is precedent already), but that's not my decision :)

**Comment by skabbes** [comment]
I think I prefer base10 strings too, but it feels wrong to have value-dependent type mapping.  A wrapper class around a number could possibly override `valueOf` to retain backwards compatibility.

**Comment by skabbes** [comment]
@JerrySievert could you just point me at the code where I might change this? Regardless of the solution, I'd like to poke around.

**Comment by JerrySievert** [comment]
At a beer festival right now, or I'd get you the line #'s but figured I'd at least get you moving in the right direction.

Most type coercion occurs in plv8_type.cc - I can probably get you line numbers tomorrow if you still need.

**Comment by skabbes** [comment]
I'll figure it out from there. I certainly didn't mean to keep you from beer!



—

**Comment by umitanuki** [comment]
The base10 string sounds good.  I also don't like it breaks at some point silently, rather than being a bit hard to use or possibly being slow.  But I'm afraid I'm still not following the solution completely.  Do you mean the precedence is here? https://github.com/brianc/node-postgres/blob/master/lib/defaults.js#L48  

I guess you want to tweak code around https://github.com/plv8/plv8/blob/master/plv8_type.cc#L279

**Comment by skabbes** [comment]
Ya, other libraries don't even attempt to parse 8 bit integers.





https://github.com/sequelize/sequelize/issues/1774




—

**Comment by JerrySievert** [comment]
if we want to make sure that making a change does not break things, it could be a run-time configuration:

https://github.com/plv8/plv8/blob/master/plv8.cc#L257-L267

this would allow for previous (broken, but documented) behavior to be the default, and sane, but slower behavior to be feasible.

thoughts?

**Comment by skabbes** [comment]
To be honest, probably the best thing to do if backwards compatibility is important would be to have a separate type. int8string or something 



—

**Comment by umitanuki** [comment]
Isn't it just to convert the number to string and then to 64 bit integer?  Then it would be slow but doesn't break anything.

**Comment by JerrySievert** [comment]
let's investigate this for 2.0

**Comment by emrul** [comment]
V8 now gets BigInt support https://developers.google.com/web/updates/2018/05/bigint

**Comment by JerrySievert** [comment]
yup. going to have to figure out how to best get that fit in.

likely toward a breaking change, with lots of documentation.

**Comment by JerrySievert** [comment]
it looks like 64 bit numbers are going to be easy to support, but looking for a clear way to handle ver large numbers - will likely need to spend some time in the node source code and see if they are handling conversion through the c++/javascript membrane.  it looks like I can use a string to go from javascript into c++, but currently only finding methods for 64 bit numbers going from c++ to javascript.  I want to avoid creating a JSON object if I can.

**Comment by JerrySievert** [comment]
note: the spec lives here - https://tc39.github.io/proposal-bigint/#sec-numeric-types

**Comment by cschwaderer** [comment]
I'm facing problems with plv8 and big integers, too and I'm somehow lost in this thread. So, let me ask a simple follow up question:

Problem:

Using 1.4.8
```
DO $$
 plv8.elog(INFO,plv8.execute('SELECT $1 AS mynumber;',[1324215868541576444])[0].mynumber);
$$ LANGUAGE plv8;
```
Expected output: `1324215868541576444`
Actual output: `1324215868541576400`

It seems plv8 somehow "rounds" the big number.

Has this problem been solved already in versions newer than my current 1.4.8? If not: will it be solved soon?

**Comment by JerrySievert** [comment]
this should be eventually solved when a version of `v8` that has `BigInt` support is integrated into `plv8`.  there is no timeframe for this currently.

you can see the same issue in `node`:

```
> var a = 1324215868541576444;
undefined
> a
1324215868541576400
```

**Comment by JerrySievert** [comment]
I have some experimental `BigInt` support in plv8 3.0alpha (not pushed up yet).

the only issue so far is that in 64 bit numbers, I'm forced to have plv8 make a choice as to the type, and there's possibility of losing precision when the type is `NUMERIC`, though it seems to be working well for `BIGINT`.

I'm going to add array support, and some more tests, then will push up to the master repo.

**Comment by JerrySievert** [comment]
discussion started: https://groups.google.com/forum/#!topic/plv8js/1_gVZ2pR2iE

**Comment by JerrySievert** [comment]
3.0 alpha has bigint support, closing this.
