### ISSUE TITLE
ERROR:  PL/v8 functions cannot return type event_trigger

### ISSUE THREAD

**Issue by GoogleCodeExporter** [plv8/plv8#86]
```
subj

```

Original issue reported on code.google.com by `vovapjat...@gmail.com` on 13 Feb 2014 at 2:19

**Comment by kabbi** [comment]
Hey, any update on this?
As a workaround other languages may be used, like calling plv8 code from plpgsql, but that looks awful and I don't understand why triggers are supported and event triggers are not.

**Comment by JerrySievert** [comment]
not yet, i can add this to the 2.0 milestone, but we are close enough to 1.5 that i don't want to push it that early.

i agree, i'd love to see plv8 handle triggers, and will attempt to make it happen sooner rather than later.
